// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ActionEffect,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  actionId: __t.u32().name("action_id"),
  sequenceIndex: __t.i32().name("sequence_index"),
  get actionEffect() {
    return ActionEffect.name("action_effect");
  },
});
