// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { ActionAppearance } from "./action_appearance_type";
import { EventContext, Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `action_appearances`.
 *
 * Obtain a handle from the [`actionAppearances`] property on [`RemoteTables`],
 * like `ctx.db.actionAppearances`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.actionAppearances.on_insert(...)`.
 */
export class ActionAppearancesTableHandle {
  tableCache: TableCache<ActionAppearance>;

  constructor(tableCache: TableCache<ActionAppearance>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<ActionAppearance> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `actionId` unique index on the table `action_appearances`,
   * which allows point queries on the field of the same name
   * via the [`ActionAppearancesActionIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.actionAppearances.actionId().find(...)`.
   *
   * Get a handle on the `actionId` unique index on the table `action_appearances`.
   */
  actionId = {
    // Find the subscribed row whose `actionId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): ActionAppearance | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.actionId, col_val)) {
          return row;
        }
      }
    },
  };
  /**
   * Access to the `name` unique index on the table `action_appearances`,
   * which allows point queries on the field of the same name
   * via the [`ActionAppearancesNameUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.actionAppearances.name().find(...)`.
   *
   * Get a handle on the `name` unique index on the table `action_appearances`.
   */
  name = {
    // Find the subscribed row whose `name` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: string): ActionAppearance | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.name, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: ActionAppearance) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: ActionAppearance) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: ActionAppearance) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: ActionAppearance) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: ActionAppearance, newRow: ActionAppearance) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: ActionAppearance, newRow: ActionAppearance) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
