// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
// A namespace for generated variants and helper functions.
export namespace ActionType {
  // These are the generated variant types for each variant of the tagged union.
  // One type is generated per variant and will be used in the `value` field of
  // the tagged union.
  export type Buff = { tag: "Buff" };
  export type Attack = { tag: "Attack" };
  export type Move = { tag: "Move" };
  export type Inventory = { tag: "Inventory" };
  export type Equip = { tag: "Equip" };

  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  export const Buff = { tag: "Buff" };
  export const Attack = { tag: "Attack" };
  export const Move = { tag: "Move" };
  export const Inventory = { tag: "Inventory" };
  export const Equip = { tag: "Equip" };

  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createSumType([
      new SumTypeVariant("Buff", AlgebraicType.createProductType([])),
      new SumTypeVariant("Attack", AlgebraicType.createProductType([])),
      new SumTypeVariant("Move", AlgebraicType.createProductType([])),
      new SumTypeVariant("Inventory", AlgebraicType.createProductType([])),
      new SumTypeVariant("Equip", AlgebraicType.createProductType([])),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: ActionType): void {
      ActionType.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): ActionType {
      return ActionType.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

// The tagged union or sum type for the algebraic type `ActionType`.
export type ActionType = ActionType.Buff | ActionType.Attack | ActionType.Move | ActionType.Inventory | ActionType.Equip;

export default ActionType;

