// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { ActionStateComponent } from "./action_state_component_type";
import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `action_state_components`.
 *
 * Obtain a handle from the [`actionStateComponents`] property on [`RemoteTables`],
 * like `ctx.db.actionStateComponents`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.actionStateComponents.on_insert(...)`.
 */
export class ActionStateComponentsTableHandle {
  tableCache: TableCache<ActionStateComponent>;

  constructor(tableCache: TableCache<ActionStateComponent>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<ActionStateComponent> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `entityId` unique index on the table `action_state_components`,
   * which allows point queries on the field of the same name
   * via the [`ActionStateComponentsEntityIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.actionStateComponents.entityId().find(...)`.
   *
   * Get a handle on the `entityId` unique index on the table `action_state_components`.
   */
  entityId = {
    // Find the subscribed row whose `entityId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): ActionStateComponent | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.entityId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: ActionStateComponent) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: ActionStateComponent) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: ActionStateComponent) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: ActionStateComponent) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: ActionStateComponent, newRow: ActionStateComponent) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: ActionStateComponent, newRow: ActionStateComponent) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
