// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { ActorArchetype } from "./actor_archetype_type";
import { ActionsComponent as __ActionsComponent } from "./actions_component_type";
import { AllegianceComponent as __AllegianceComponent } from "./allegiance_component_type";
import { AppearanceFeaturesComponent as __AppearanceFeaturesComponent } from "./appearance_features_component_type";
import { AttackComponent as __AttackComponent } from "./attack_component_type";
import { BaselineComponent as __BaselineComponent } from "./baseline_component_type";
import { EpComponent as __EpComponent } from "./ep_component_type";
import { HpComponent as __HpComponent } from "./hp_component_type";
import { LocationComponent as __LocationComponent } from "./location_component_type";
import { TraitsComponent as __TraitsComponent } from "./traits_component_type";

import { EventContext, Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `actor_archetypes`.
 *
 * Obtain a handle from the [`actorArchetypes`] property on [`RemoteTables`],
 * like `ctx.db.actorArchetypes`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.actorArchetypes.on_insert(...)`.
 */
export class ActorArchetypesTableHandle {
  tableCache: TableCache<ActorArchetype>;

  constructor(tableCache: TableCache<ActorArchetype>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<ActorArchetype> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `entityId` unique index on the table `actor_archetypes`,
   * which allows point queries on the field of the same name
   * via the [`ActorArchetypesEntityIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.actorArchetypes.entityId().find(...)`.
   *
   * Get a handle on the `entityId` unique index on the table `actor_archetypes`.
   */
  entityId = {
    // Find the subscribed row whose `entityId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): ActorArchetype | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.entityId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: ActorArchetype) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: ActorArchetype) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: ActorArchetype) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: ActorArchetype) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }
}
