// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { ActionsComponent as __ActionsComponent } from "./actions_component_type";
import { AllegianceComponent as __AllegianceComponent } from "./allegiance_component_type";
import { AppearanceFeaturesComponent as __AppearanceFeaturesComponent } from "./appearance_features_component_type";
import { AttackComponent as __AttackComponent } from "./attack_component_type";
import { BaselineComponent as __BaselineComponent } from "./baseline_component_type";
import { EpComponent as __EpComponent } from "./ep_component_type";
import { HpComponent as __HpComponent } from "./hp_component_type";
import { LocationComponent as __LocationComponent } from "./location_component_type";
import { TraitsComponent as __TraitsComponent } from "./traits_component_type";

export type ActorArchetype = {
  entityId: bigint,
  actions: __ActionsComponent,
  allegiance: __AllegianceComponent,
  appearanceFeatures: __AppearanceFeaturesComponent,
  attack: __AttackComponent,
  baseline: __BaselineComponent,
  ep: __EpComponent,
  hp: __HpComponent,
  location: __LocationComponent,
  traits: __TraitsComponent,
};

/**
 * A namespace for generated helper functions.
 */
export namespace ActorArchetype {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("entityId", AlgebraicType.createU64Type()),
      new ProductTypeElement("actions", __ActionsComponent.getTypeScriptAlgebraicType()),
      new ProductTypeElement("allegiance", __AllegianceComponent.getTypeScriptAlgebraicType()),
      new ProductTypeElement("appearanceFeatures", __AppearanceFeaturesComponent.getTypeScriptAlgebraicType()),
      new ProductTypeElement("attack", __AttackComponent.getTypeScriptAlgebraicType()),
      new ProductTypeElement("baseline", __BaselineComponent.getTypeScriptAlgebraicType()),
      new ProductTypeElement("ep", __EpComponent.getTypeScriptAlgebraicType()),
      new ProductTypeElement("hp", __HpComponent.getTypeScriptAlgebraicType()),
      new ProductTypeElement("location", __LocationComponent.getTypeScriptAlgebraicType()),
      new ProductTypeElement("traits", __TraitsComponent.getTypeScriptAlgebraicType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: ActorArchetype): void {
    ActorArchetype.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): ActorArchetype {
    return ActorArchetype.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


