// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";

export type AdminRecreatePlayerForIdentity = {
  identity: Identity,
  allegianceName: string,
  startingRoomName: string,
  baselineName: string,
  traitNames: string[],
};

/**
 * A namespace for generated helper functions.
 */
export namespace AdminRecreatePlayerForIdentity {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("identity", AlgebraicType.createIdentityType()),
      new ProductTypeElement("allegianceName", AlgebraicType.createStringType()),
      new ProductTypeElement("startingRoomName", AlgebraicType.createStringType()),
      new ProductTypeElement("baselineName", AlgebraicType.createStringType()),
      new ProductTypeElement("traitNames", AlgebraicType.createArrayType(AlgebraicType.createStringType())),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: AdminRecreatePlayerForIdentity): void {
    AdminRecreatePlayerForIdentity.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): AdminRecreatePlayerForIdentity {
    return AdminRecreatePlayerForIdentity.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

