// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { ActionStep as __ActionStep } from "./action_step_type";
import { Action as __Action } from "./action_type";
import { Baseline as __Baseline } from "./baseline_type";
import { Trait as __Trait } from "./trait_type";
import { SpecialEntityBlob as __SpecialEntityBlob } from "./special_entity_blob_type";

export type AdminBundle = {
  actions: __Action[],
  actionSteps: __ActionStep[],
  baselines: __Baseline[],
  traits: __Trait[],
  specialEntityBlobs: __SpecialEntityBlob[],
};

/**
 * A namespace for generated helper functions.
 */
export namespace AdminBundle {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("actions", AlgebraicType.createArrayType(__Action.getTypeScriptAlgebraicType())),
      new ProductTypeElement("actionSteps", AlgebraicType.createArrayType(__ActionStep.getTypeScriptAlgebraicType())),
      new ProductTypeElement("baselines", AlgebraicType.createArrayType(__Baseline.getTypeScriptAlgebraicType())),
      new ProductTypeElement("traits", AlgebraicType.createArrayType(__Trait.getTypeScriptAlgebraicType())),
      new ProductTypeElement("specialEntityBlobs", AlgebraicType.createArrayType(__SpecialEntityBlob.getTypeScriptAlgebraicType())),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: AdminBundle): void {
    AdminBundle.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): AdminBundle {
    return AdminBundle.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


