// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  AppearanceFeatureType,
} from "./types";


export default __t.row({
  index: __t.u32().primaryKey(),
  name: __t.string(),
  text: __t.string(),
  get appearanceFeatureType() {
    return AppearanceFeatureType.name("appearance_feature_type");
  },
  priority: __t.i32(),
});
