// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { Baseline } from "./baseline_type";
import { StatBlock as __StatBlock } from "./stat_block_type";

import { EventContext, Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `baselines`.
 *
 * Obtain a handle from the [`baselines`] property on [`RemoteTables`],
 * like `ctx.db.baselines`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.baselines.on_insert(...)`.
 */
export class BaselinesTableHandle {
  tableCache: TableCache<Baseline>;

  constructor(tableCache: TableCache<Baseline>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<Baseline> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `id` unique index on the table `baselines`,
   * which allows point queries on the field of the same name
   * via the [`BaselinesIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.baselines.id().find(...)`.
   *
   * Get a handle on the `id` unique index on the table `baselines`.
   */
  id = {
    // Find the subscribed row whose `id` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): Baseline | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.id, col_val)) {
          return row;
        }
      }
    },
  };
  /**
   * Access to the `name` unique index on the table `baselines`,
   * which allows point queries on the field of the same name
   * via the [`BaselinesNameUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.baselines.name().find(...)`.
   *
   * Get a handle on the `name` unique index on the table `baselines`.
   */
  name = {
    // Find the subscribed row whose `name` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: string): Baseline | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.name, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: Baseline) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: Baseline) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: Baseline) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: Baseline) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: Baseline, newRow: Baseline) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: Baseline, newRow: Baseline) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
