// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { AppearanceFeature } from "./appearance_feature_type";
import { AppearanceFeatureType as __AppearanceFeatureType } from "./appearance_feature_type_type";

import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `en_appearance_features`.
 *
 * Obtain a handle from the [`enAppearanceFeatures`] property on [`RemoteTables`],
 * like `ctx.db.enAppearanceFeatures`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.enAppearanceFeatures.on_insert(...)`.
 */
export class EnAppearanceFeaturesTableHandle {
  tableCache: TableCache<AppearanceFeature>;

  constructor(tableCache: TableCache<AppearanceFeature>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<AppearanceFeature> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `id` unique index on the table `en_appearance_features`,
   * which allows point queries on the field of the same name
   * via the [`EnAppearanceFeaturesIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.enAppearanceFeatures.id().find(...)`.
   *
   * Get a handle on the `id` unique index on the table `en_appearance_features`.
   */
  id = {
    // Find the subscribed row whose `id` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): AppearanceFeature | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.id, col_val)) {
          return row;
        }
      }
    },
  };
  /**
   * Access to the `text` unique index on the table `en_appearance_features`,
   * which allows point queries on the field of the same name
   * via the [`EnAppearanceFeaturesTextUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.enAppearanceFeatures.text().find(...)`.
   *
   * Get a handle on the `text` unique index on the table `en_appearance_features`.
   */
  text = {
    // Find the subscribed row whose `text` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: string): AppearanceFeature | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.text, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: AppearanceFeature) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: AppearanceFeature) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: AppearanceFeature) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: AppearanceFeature) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: AppearanceFeature, newRow: AppearanceFeature) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: AppearanceFeature, newRow: AppearanceFeature) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
