// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { ActionHotkeysComponent as __ActionHotkeysComponent } from "./action_hotkeys_component_type";
import { ActionOptionsComponent as __ActionOptionsComponent } from "./action_options_component_type";
import { ActionStateComponent as __ActionStateComponent } from "./action_state_component_type";
import { ActionsComponent as __ActionsComponent } from "./actions_component_type";
import { AllegianceComponent as __AllegianceComponent } from "./allegiance_component_type";
import { AppearanceFeaturesComponent as __AppearanceFeaturesComponent } from "./appearance_features_component_type";
import { AttackComponent as __AttackComponent } from "./attack_component_type";
import { BaselineComponent as __BaselineComponent } from "./baseline_component_type";
import { NameComponent as __NameComponent } from "./name_component_type";
import { LocationComponent as __LocationComponent } from "./location_component_type";
import { PathComponent as __PathComponent } from "./path_component_type";
import { TraitsComponent as __TraitsComponent } from "./traits_component_type";
import { StatBlockCacheComponent as __StatBlockCacheComponent } from "./stat_block_cache_component_type";
import { FlagComponent as __FlagComponent } from "./flag_component_type";
import { HpComponent as __HpComponent } from "./hp_component_type";
import { EpComponent as __EpComponent } from "./ep_component_type";
import { PlayerControllerComponent as __PlayerControllerComponent } from "./player_controller_component_type";
import { TargetComponent as __TargetComponent } from "./target_component_type";
import { EntityProminenceComponent as __EntityProminenceComponent } from "./entity_prominence_component_type";
import { TimerComponent as __TimerComponent } from "./timer_component_type";
import { RngSeedComponent as __RngSeedComponent } from "./rng_seed_component_type";
import { LocationMapComponent as __LocationMapComponent } from "./location_map_component_type";
import { MapComponent as __MapComponent } from "./map_component_type";

export type EntityBlob = {
  entityId: bigint,
  name: __NameComponent | undefined,
  location: __LocationComponent | undefined,
  path: __PathComponent | undefined,
  allegiance: __AllegianceComponent | undefined,
  baseline: __BaselineComponent | undefined,
  traits: __TraitsComponent | undefined,
  traitsStatBlockCache: __StatBlockCacheComponent | undefined,
  traitsStatBlockDirtyFlag: __FlagComponent | undefined,
  totalStatBlockDirtyFlag: __FlagComponent | undefined,
  attack: __AttackComponent | undefined,
  hp: __HpComponent | undefined,
  ep: __EpComponent | undefined,
  playerController: __PlayerControllerComponent | undefined,
  target: __TargetComponent | undefined,
  actionState: __ActionStateComponent | undefined,
  queuedActionState: __ActionStateComponent | undefined,
  actions: __ActionsComponent | undefined,
  actionHotkeys: __ActionHotkeysComponent | undefined,
  actionOptions: __ActionOptionsComponent | undefined,
  entityProminence: __EntityProminenceComponent | undefined,
  entityDeactivationTimer: __TimerComponent | undefined,
  rngSeed: __RngSeedComponent | undefined,
  locationMap: __LocationMapComponent | undefined,
  realizedMap: __MapComponent | undefined,
  unrealizedMap: __MapComponent | undefined,
  appearanceFeatures: __AppearanceFeaturesComponent | undefined,
};

/**
 * A namespace for generated helper functions.
 */
export namespace EntityBlob {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("entityId", AlgebraicType.createU64Type()),
      new ProductTypeElement("name", AlgebraicType.createOptionType(__NameComponent.getTypeScriptAlgebraicType())),
      new ProductTypeElement("location", AlgebraicType.createOptionType(__LocationComponent.getTypeScriptAlgebraicType())),
      new ProductTypeElement("path", AlgebraicType.createOptionType(__PathComponent.getTypeScriptAlgebraicType())),
      new ProductTypeElement("allegiance", AlgebraicType.createOptionType(__AllegianceComponent.getTypeScriptAlgebraicType())),
      new ProductTypeElement("baseline", AlgebraicType.createOptionType(__BaselineComponent.getTypeScriptAlgebraicType())),
      new ProductTypeElement("traits", AlgebraicType.createOptionType(__TraitsComponent.getTypeScriptAlgebraicType())),
      new ProductTypeElement("traitsStatBlockCache", AlgebraicType.createOptionType(__StatBlockCacheComponent.getTypeScriptAlgebraicType())),
      new ProductTypeElement("traitsStatBlockDirtyFlag", AlgebraicType.createOptionType(__FlagComponent.getTypeScriptAlgebraicType())),
      new ProductTypeElement("totalStatBlockDirtyFlag", AlgebraicType.createOptionType(__FlagComponent.getTypeScriptAlgebraicType())),
      new ProductTypeElement("attack", AlgebraicType.createOptionType(__AttackComponent.getTypeScriptAlgebraicType())),
      new ProductTypeElement("hp", AlgebraicType.createOptionType(__HpComponent.getTypeScriptAlgebraicType())),
      new ProductTypeElement("ep", AlgebraicType.createOptionType(__EpComponent.getTypeScriptAlgebraicType())),
      new ProductTypeElement("playerController", AlgebraicType.createOptionType(__PlayerControllerComponent.getTypeScriptAlgebraicType())),
      new ProductTypeElement("target", AlgebraicType.createOptionType(__TargetComponent.getTypeScriptAlgebraicType())),
      new ProductTypeElement("actionState", AlgebraicType.createOptionType(__ActionStateComponent.getTypeScriptAlgebraicType())),
      new ProductTypeElement("queuedActionState", AlgebraicType.createOptionType(__ActionStateComponent.getTypeScriptAlgebraicType())),
      new ProductTypeElement("actions", AlgebraicType.createOptionType(__ActionsComponent.getTypeScriptAlgebraicType())),
      new ProductTypeElement("actionHotkeys", AlgebraicType.createOptionType(__ActionHotkeysComponent.getTypeScriptAlgebraicType())),
      new ProductTypeElement("actionOptions", AlgebraicType.createOptionType(__ActionOptionsComponent.getTypeScriptAlgebraicType())),
      new ProductTypeElement("entityProminence", AlgebraicType.createOptionType(__EntityProminenceComponent.getTypeScriptAlgebraicType())),
      new ProductTypeElement("entityDeactivationTimer", AlgebraicType.createOptionType(__TimerComponent.getTypeScriptAlgebraicType())),
      new ProductTypeElement("rngSeed", AlgebraicType.createOptionType(__RngSeedComponent.getTypeScriptAlgebraicType())),
      new ProductTypeElement("locationMap", AlgebraicType.createOptionType(__LocationMapComponent.getTypeScriptAlgebraicType())),
      new ProductTypeElement("realizedMap", AlgebraicType.createOptionType(__MapComponent.getTypeScriptAlgebraicType())),
      new ProductTypeElement("unrealizedMap", AlgebraicType.createOptionType(__MapComponent.getTypeScriptAlgebraicType())),
      new ProductTypeElement("appearanceFeatures", AlgebraicType.createOptionType(__AppearanceFeaturesComponent.getTypeScriptAlgebraicType())),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: EntityBlob): void {
    EntityBlob.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): EntityBlob {
    return EntityBlob.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


