// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { EntityBlob } from "./entity_blob_type";
import { ActionHotkeysComponent as __ActionHotkeysComponent } from "./action_hotkeys_component_type";
import { ActionOptionsComponent as __ActionOptionsComponent } from "./action_options_component_type";
import { ActionStateComponent as __ActionStateComponent } from "./action_state_component_type";
import { ActionsComponent as __ActionsComponent } from "./actions_component_type";
import { AllegianceComponent as __AllegianceComponent } from "./allegiance_component_type";
import { AppearanceFeaturesComponent as __AppearanceFeaturesComponent } from "./appearance_features_component_type";
import { AttackComponent as __AttackComponent } from "./attack_component_type";
import { BaselineComponent as __BaselineComponent } from "./baseline_component_type";
import { NameComponent as __NameComponent } from "./name_component_type";
import { LocationComponent as __LocationComponent } from "./location_component_type";
import { PathComponent as __PathComponent } from "./path_component_type";
import { TraitsComponent as __TraitsComponent } from "./traits_component_type";
import { StatBlockCacheComponent as __StatBlockCacheComponent } from "./stat_block_cache_component_type";
import { FlagComponent as __FlagComponent } from "./flag_component_type";
import { HpComponent as __HpComponent } from "./hp_component_type";
import { EpComponent as __EpComponent } from "./ep_component_type";
import { PlayerControllerComponent as __PlayerControllerComponent } from "./player_controller_component_type";
import { TargetComponent as __TargetComponent } from "./target_component_type";
import { EntityProminenceComponent as __EntityProminenceComponent } from "./entity_prominence_component_type";
import { TimerComponent as __TimerComponent } from "./timer_component_type";
import { RngSeedComponent as __RngSeedComponent } from "./rng_seed_component_type";
import { LocationMapComponent as __LocationMapComponent } from "./location_map_component_type";
import { MapComponent as __MapComponent } from "./map_component_type";

import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `entity_blobs`.
 *
 * Obtain a handle from the [`entityBlobs`] property on [`RemoteTables`],
 * like `ctx.db.entityBlobs`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.entityBlobs.on_insert(...)`.
 */
export class EntityBlobsTableHandle {
  tableCache: TableCache<EntityBlob>;

  constructor(tableCache: TableCache<EntityBlob>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<EntityBlob> {
    return this.tableCache.iter();
  }

  onInsert = (cb: (ctx: EventContext, row: EntityBlob) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: EntityBlob) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: EntityBlob) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: EntityBlob) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }
}
