// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { EntityDeactivationTimerComponent } from "./entity_deactivation_timer_component_type";
import { EventContext, Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `entity_deactivation_timer_components`.
 *
 * Obtain a handle from the [`entityDeactivationTimerComponents`] property on [`RemoteTables`],
 * like `ctx.db.entityDeactivationTimerComponents`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.entityDeactivationTimerComponents.on_insert(...)`.
 */
export class EntityDeactivationTimerComponentsTableHandle {
  tableCache: TableCache<EntityDeactivationTimerComponent>;

  constructor(tableCache: TableCache<EntityDeactivationTimerComponent>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<EntityDeactivationTimerComponent> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `entityId` unique index on the table `entity_deactivation_timer_components`,
   * which allows point queries on the field of the same name
   * via the [`EntityDeactivationTimerComponentsEntityIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.entityDeactivationTimerComponents.entityId().find(...)`.
   *
   * Get a handle on the `entityId` unique index on the table `entity_deactivation_timer_components`.
   */
  entityId = {
    // Find the subscribed row whose `entityId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): EntityDeactivationTimerComponent | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.entityId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: EntityDeactivationTimerComponent) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: EntityDeactivationTimerComponent) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: EntityDeactivationTimerComponent) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: EntityDeactivationTimerComponent) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: EntityDeactivationTimerComponent, newRow: EntityDeactivationTimerComponent) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: EntityDeactivationTimerComponent, newRow: EntityDeactivationTimerComponent) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
