// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  NameComponentBlob,
  LocationComponentBlob,
  PathComponentBlob,
  PathBlockerComponentBlob,
  HpShareComponentBlob,
  HpShareAppliedComponentBlob,
  AllegianceComponentBlob,
  PartyComponentBlob,
  BaselineComponentBlob,
  TraitsComponentBlob,
  ActiveStanceComponentBlob,
  EquipmentComponentBlob,
  StartingGearComponentBlob,
  EquipmentBlobbedComponentBlob,
  RemainsComponentBlob,
  DefaultArmamentsComponentBlob,
  ArmorComponentBlob,
  RelicsComponentBlob,
  StanceCustomizationsComponentBlob,
  ItemComponentBlob,
  EquippableComponentBlob,
  EquipmentDisabledComponentBlob,
  StatsCacheComponentBlob,
  AppearanceCacheComponentBlob,
  ReadinessCacheComponentBlob,
  BodyCapacityCacheComponentBlob,
  EquipmentBodyCapacityCacheComponentBlob,
  FlagComponentBlob,
  CheckpointComponentBlob,
  DifferentiableComponentBlob,
  MapInstanceComponentBlob,
  MapCheckpointsComponentBlob,
  MapRoomsComponentBlob,
  PendingConnectionsComponentBlob,
  CheckpointBindingComponentBlob,
  DefeatDropComponentBlob,
  AttackComponentBlob,
  HpComponentBlob,
  EpComponentBlob,
  MaximaRaiseComponentBlob,
  StatsTotalComponentBlob,
  ReadinessTotalComponentBlob,
  BodyCapacityTotalComponentBlob,
  FearStatusComponentBlob,
  CourageStatusComponentBlob,
  BracedStatusComponentBlob,
  PlayerControllerComponentBlob,
  EnemyControllerComponentBlob,
  ActionStateComponentBlob,
  ActionQueueComponentBlob,
  ActionsComponentBlob,
  PinnedActionsComponentBlob,
  ActionCursorComponentBlob,
  TimerComponentBlob,
  LocationMapComponentBlob,
  AppearanceFeaturesComponentBlob,
} from "./types";


export default __t.row({
  get name() {
    return __t.option(NameComponentBlob);
  },
  get location() {
    return __t.option(LocationComponentBlob);
  },
  get path() {
    return __t.option(PathComponentBlob);
  },
  get pathBlocker() {
    return __t.option(PathBlockerComponentBlob).name("path_blocker");
  },
  get hpShare() {
    return __t.option(HpShareComponentBlob).name("hp_share");
  },
  get hpShareApplied() {
    return __t.option(HpShareAppliedComponentBlob).name("hp_share_applied");
  },
  get allegiance() {
    return __t.option(AllegianceComponentBlob);
  },
  get party() {
    return __t.option(PartyComponentBlob);
  },
  get baseline() {
    return __t.option(BaselineComponentBlob);
  },
  get traits() {
    return __t.option(TraitsComponentBlob);
  },
  get activeStance() {
    return __t.option(ActiveStanceComponentBlob).name("active_stance");
  },
  get equipment() {
    return __t.option(EquipmentComponentBlob);
  },
  get startingGear() {
    return __t.option(StartingGearComponentBlob).name("starting_gear");
  },
  get equipmentBlobbed() {
    return __t.option(EquipmentBlobbedComponentBlob).name("equipment_blobbed");
  },
  get remains() {
    return __t.option(RemainsComponentBlob);
  },
  get defaultArmaments() {
    return __t.option(DefaultArmamentsComponentBlob).name("default_armaments");
  },
  get armor() {
    return __t.option(ArmorComponentBlob);
  },
  get relics() {
    return __t.option(RelicsComponentBlob);
  },
  get stanceCustomizations() {
    return __t.option(StanceCustomizationsComponentBlob).name("stance_customizations");
  },
  get item() {
    return __t.option(ItemComponentBlob);
  },
  get equippable() {
    return __t.option(EquippableComponentBlob);
  },
  get equipmentDisabled() {
    return __t.option(EquipmentDisabledComponentBlob).name("equipment_disabled");
  },
  get traitsStatsCache() {
    return __t.option(StatsCacheComponentBlob).name("traits_stats_cache");
  },
  get statusStatsCache() {
    return __t.option(StatsCacheComponentBlob).name("status_stats_cache");
  },
  get questStatsCache() {
    return __t.option(StatsCacheComponentBlob).name("quest_stats_cache");
  },
  get equipmentStatsCache() {
    return __t.option(StatsCacheComponentBlob).name("equipment_stats_cache");
  },
  get traitsAppearanceCache() {
    return __t.option(AppearanceCacheComponentBlob).name("traits_appearance_cache");
  },
  get questAppearanceCache() {
    return __t.option(AppearanceCacheComponentBlob).name("quest_appearance_cache");
  },
  get equipmentAppearanceCache() {
    return __t.option(AppearanceCacheComponentBlob).name("equipment_appearance_cache");
  },
  get traitsReadinessCache() {
    return __t.option(ReadinessCacheComponentBlob).name("traits_readiness_cache");
  },
  get statusReadinessCache() {
    return __t.option(ReadinessCacheComponentBlob).name("status_readiness_cache");
  },
  get questReadinessCache() {
    return __t.option(ReadinessCacheComponentBlob).name("quest_readiness_cache");
  },
  get equipmentReadinessCache() {
    return __t.option(ReadinessCacheComponentBlob).name("equipment_readiness_cache");
  },
  get traitsBodyCapacityCache() {
    return __t.option(BodyCapacityCacheComponentBlob).name("traits_body_capacity_cache");
  },
  get questBodyCapacityCache() {
    return __t.option(BodyCapacityCacheComponentBlob).name("quest_body_capacity_cache");
  },
  get equipmentBodyCapacityCache() {
    return __t.option(EquipmentBodyCapacityCacheComponentBlob).name("equipment_body_capacity_cache");
  },
  get traitsDirtyFlag() {
    return __t.option(FlagComponentBlob).name("traits_dirty_flag");
  },
  get statusDirtyFlag() {
    return __t.option(FlagComponentBlob).name("status_dirty_flag");
  },
  get questDirtyFlag() {
    return __t.option(FlagComponentBlob).name("quest_dirty_flag");
  },
  get equipmentDirtyFlag() {
    return __t.option(FlagComponentBlob).name("equipment_dirty_flag");
  },
  get statsDirtyFlag() {
    return __t.option(FlagComponentBlob).name("stats_dirty_flag");
  },
  get appearanceDirtyFlag() {
    return __t.option(FlagComponentBlob).name("appearance_dirty_flag");
  },
  get bodyCapacityDirtyFlag() {
    return __t.option(FlagComponentBlob).name("body_capacity_dirty_flag");
  },
  get readinessDirtyFlag() {
    return __t.option(FlagComponentBlob).name("readiness_dirty_flag");
  },
  get checkpointObject() {
    return __t.option(FlagComponentBlob).name("checkpoint_object");
  },
  get turnPaused() {
    return __t.option(FlagComponentBlob).name("turn_paused");
  },
  get open() {
    return __t.option(FlagComponentBlob);
  },
  get stanceForced() {
    return __t.option(FlagComponentBlob).name("stance_forced");
  },
  get actionQueueDirty() {
    return __t.option(FlagComponentBlob).name("action_queue_dirty");
  },
  get perished() {
    return __t.option(FlagComponentBlob);
  },
  get destroyed() {
    return __t.option(FlagComponentBlob);
  },
  get checkpoint() {
    return __t.option(CheckpointComponentBlob);
  },
  get differentiable() {
    return __t.option(DifferentiableComponentBlob);
  },
  get mapInstance() {
    return __t.option(MapInstanceComponentBlob).name("map_instance");
  },
  get mapCheckpoints() {
    return __t.option(MapCheckpointsComponentBlob).name("map_checkpoints");
  },
  get mapRooms() {
    return __t.option(MapRoomsComponentBlob).name("map_rooms");
  },
  get pendingConnections() {
    return __t.option(PendingConnectionsComponentBlob).name("pending_connections");
  },
  get checkpointBinding() {
    return __t.option(CheckpointBindingComponentBlob).name("checkpoint_binding");
  },
  get defeatDrop() {
    return __t.option(DefeatDropComponentBlob).name("defeat_drop");
  },
  get attack() {
    return __t.option(AttackComponentBlob);
  },
  get hp() {
    return __t.option(HpComponentBlob);
  },
  get ep() {
    return __t.option(EpComponentBlob);
  },
  get maximaRaise() {
    return __t.option(MaximaRaiseComponentBlob).name("maxima_raise");
  },
  get statsTotal() {
    return __t.option(StatsTotalComponentBlob).name("stats_total");
  },
  get readinessTotal() {
    return __t.option(ReadinessTotalComponentBlob).name("readiness_total");
  },
  get bodyCapacityTotal() {
    return __t.option(BodyCapacityTotalComponentBlob).name("body_capacity_total");
  },
  get fearStatus() {
    return __t.option(FearStatusComponentBlob).name("fear_status");
  },
  get courageStatus() {
    return __t.option(CourageStatusComponentBlob).name("courage_status");
  },
  get bracedStatus() {
    return __t.option(BracedStatusComponentBlob).name("braced_status");
  },
  get playerController() {
    return __t.option(PlayerControllerComponentBlob).name("player_controller");
  },
  get enemyController() {
    return __t.option(EnemyControllerComponentBlob).name("enemy_controller");
  },
  get actionState() {
    return __t.option(ActionStateComponentBlob).name("action_state");
  },
  get actionQueue() {
    return __t.option(ActionQueueComponentBlob).name("action_queue");
  },
  get actions() {
    return __t.option(ActionsComponentBlob);
  },
  get offeredActions() {
    return __t.option(ActionsComponentBlob).name("offered_actions");
  },
  get defaultActions() {
    return __t.option(ActionsComponentBlob).name("default_actions");
  },
  get pinnedActions() {
    return __t.option(PinnedActionsComponentBlob).name("pinned_actions");
  },
  get actionCursor() {
    return __t.option(ActionCursorComponentBlob).name("action_cursor");
  },
  get entityDeletionTimer() {
    return __t.option(TimerComponentBlob).name("entity_deletion_timer");
  },
  get playerDeactivationTimer() {
    return __t.option(TimerComponentBlob).name("player_deactivation_timer");
  },
  get respawnTimer() {
    return __t.option(TimerComponentBlob).name("respawn_timer");
  },
  get mapCleanupTimer() {
    return __t.option(TimerComponentBlob).name("map_cleanup_timer");
  },
  get actionlessSince() {
    return __t.option(TimerComponentBlob).name("actionless_since");
  },
  get locationMap() {
    return __t.option(LocationMapComponentBlob).name("location_map");
  },
  get appearanceFeatures() {
    return __t.option(AppearanceFeaturesComponentBlob).name("appearance_features");
  },
});
