// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ActionHotkeysComponent,
  ActionStateComponent,
  ActionsComponent,
  AllegianceComponent,
  AppearanceFeaturesComponent,
  AttackComponent,
  BaselineComponent,
  NameComponent,
  LocationComponent,
  PathComponent,
  TraitsComponent,
  StatBlockCacheComponent,
  FlagComponent,
  HpComponent,
  EpComponent,
  PlayerControllerComponent,
  EnemyControllerComponent,
  EntityProminenceComponent,
  TimerComponent,
  LocationMapComponent,
} from "./types";


export default __t.row({
  get name() {
    return __t.option(NameComponent);
  },
  get location() {
    return __t.option(LocationComponent);
  },
  get path() {
    return __t.option(PathComponent);
  },
  get allegiance() {
    return __t.option(AllegianceComponent);
  },
  get baseline() {
    return __t.option(BaselineComponent);
  },
  get traits() {
    return __t.option(TraitsComponent);
  },
  get equipmentStatBlockCache() {
    return __t.option(StatBlockCacheComponent).name("equipment_stat_block_cache");
  },
  get statusStatBlockCache() {
    return __t.option(StatBlockCacheComponent).name("status_stat_block_cache");
  },
  get traitsStatBlockCache() {
    return __t.option(StatBlockCacheComponent).name("traits_stat_block_cache");
  },
  get traitsStatBlockDirtyFlag() {
    return __t.option(FlagComponent).name("traits_stat_block_dirty_flag");
  },
  get totalStatBlockDirtyFlag() {
    return __t.option(FlagComponent).name("total_stat_block_dirty_flag");
  },
  get attack() {
    return __t.option(AttackComponent);
  },
  get hp() {
    return __t.option(HpComponent);
  },
  get ep() {
    return __t.option(EpComponent);
  },
  get playerController() {
    return __t.option(PlayerControllerComponent).name("player_controller");
  },
  get enemyController() {
    return __t.option(EnemyControllerComponent).name("enemy_controller");
  },
  get actionState() {
    return __t.option(ActionStateComponent).name("action_state");
  },
  get queuedActionState() {
    return __t.option(ActionStateComponent).name("queued_action_state");
  },
  get actions() {
    return __t.option(ActionsComponent);
  },
  get actionHotkeys() {
    return __t.option(ActionHotkeysComponent).name("action_hotkeys");
  },
  get entityProminence() {
    return __t.option(EntityProminenceComponent).name("entity_prominence");
  },
  get entityDeletionTimer() {
    return __t.option(TimerComponent).name("entity_deletion_timer");
  },
  get playerDeactivationTimer() {
    return __t.option(TimerComponent).name("player_deactivation_timer");
  },
  get locationMap() {
    return __t.option(LocationMapComponent).name("location_map");
  },
  get appearanceFeatures() {
    return __t.option(AppearanceFeaturesComponent).name("appearance_features");
  },
});
