// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
export type HpComponent = {
  entityId: bigint,
  hp: number,
  mhp: number,
  defense: number,
  accumulatedDamage: number,
  accumulatedHealing: number,
};

/**
 * A namespace for generated helper functions.
 */
export namespace HpComponent {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("entityId", AlgebraicType.createU64Type()),
      new ProductTypeElement("hp", AlgebraicType.createI32Type()),
      new ProductTypeElement("mhp", AlgebraicType.createI32Type()),
      new ProductTypeElement("defense", AlgebraicType.createI32Type()),
      new ProductTypeElement("accumulatedDamage", AlgebraicType.createI32Type()),
      new ProductTypeElement("accumulatedHealing", AlgebraicType.createI32Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: HpComponent): void {
    HpComponent.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): HpComponent {
    return HpComponent.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


