// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { IdentityInactiveEntity } from "./identity_inactive_entity_type";
import { ComponentSet as __ComponentSet } from "./component_set_type";

import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `identity_inactive_entities`.
 *
 * Obtain a handle from the [`identityInactiveEntities`] property on [`RemoteTables`],
 * like `ctx.db.identityInactiveEntities`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.identityInactiveEntities.on_insert(...)`.
 */
export class IdentityInactiveEntitiesTableHandle {
  tableCache: TableCache<IdentityInactiveEntity>;

  constructor(tableCache: TableCache<IdentityInactiveEntity>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<IdentityInactiveEntity> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `identity` unique index on the table `identity_inactive_entities`,
   * which allows point queries on the field of the same name
   * via the [`IdentityInactiveEntitiesIdentityUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.identityInactiveEntities.identity().find(...)`.
   *
   * Get a handle on the `identity` unique index on the table `identity_inactive_entities`.
   */
  identity = {
    // Find the subscribed row whose `identity` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: Identity): IdentityInactiveEntity | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.identity, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: IdentityInactiveEntity) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: IdentityInactiveEntity) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: IdentityInactiveEntity) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: IdentityInactiveEntity) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }
}
