// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.1.0 (commit 6981f48b4bc1a71c8dd9bdfe5a2c343f6370243d).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AcceptLoginRequestReducer from "./accept_login_request_reducer";
import ActReducer from "./act_reducer";
import AssignStanceActionsReducer from "./assign_stance_actions_reducer";
import AssignStanceArmamentsReducer from "./assign_stance_armaments_reducer";
import BootstrapAdminReducer from "./bootstrap_admin_reducer";
import ClearArmorReducer from "./clear_armor_reducer";
import CreateAccountReducer from "./create_account_reducer";
import GrantRoleReducer from "./grant_role_reducer";
import LoginWithPasswordReducer from "./login_with_password_reducer";
import ProvisionAccountReducer from "./provision_account_reducer";
import PushAssetsReducer from "./push_assets_reducer";
import RefuseLoginRequestReducer from "./refuse_login_request_reducer";
import RequestLoginReducer from "./request_login_reducer";
import SetArmorReducer from "./set_armor_reducer";
import SetDefaultActionsReducer from "./set_default_actions_reducer";
import SetDefaultArmamentsReducer from "./set_default_armaments_reducer";
import SetPasswordReducer from "./set_password_reducer";
import SetRelicsReducer from "./set_relics_reducer";
import SetStanceReducer from "./set_stance_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AccountIdentitiesRow from "./account_identities_table";
import AccountRolesRow from "./account_roles_table";
import AccountsRow from "./accounts_table";
import ActionCursorComponentsRow from "./action_cursor_components_table";
import ActionQueueComponentsRow from "./action_queue_components_table";
import ActionQueueDirtyComponentsRow from "./action_queue_dirty_components_table";
import ActionRoundsRow from "./action_rounds_table";
import ActionStateComponentsRow from "./action_state_components_table";
import ActionlessSinceComponentsRow from "./actionless_since_components_table";
import ActionsRow from "./actions_table";
import ActionsComponentsRow from "./actions_components_table";
import ActiveStanceComponentsRow from "./active_stance_components_table";
import AllegianceComponentsRow from "./allegiance_components_table";
import AppearanceFeaturesRow from "./appearance_features_table";
import AppearanceFeaturesComponentsRow from "./appearance_features_components_table";
import ArmamentsRow from "./armaments_table";
import ArmorComponentsRow from "./armor_components_table";
import ArmorsRow from "./armors_table";
import AttackComponentsRow from "./attack_components_table";
import BaselineComponentsRow from "./baseline_components_table";
import BracedStatusComponentsRow from "./braced_status_components_table";
import CheckpointBindingComponentsRow from "./checkpoint_binding_components_table";
import CheckpointComponentsRow from "./checkpoint_components_table";
import CheckpointObjectComponentsRow from "./checkpoint_object_components_table";
import CourageStatusComponentsRow from "./courage_status_components_table";
import DefaultActionsComponentsRow from "./default_actions_components_table";
import DefaultArmamentsComponentsRow from "./default_armaments_components_table";
import DefeatDropComponentsRow from "./defeat_drop_components_table";
import DifferentiableComponentsRow from "./differentiable_components_table";
import EnemyControllerComponentsRow from "./enemy_controller_components_table";
import EntitiesRow from "./entities_table";
import EntitiesQuestsProgressRow from "./entities_quests_progress_table";
import EntitiesVisitedLocationsRow from "./entities_visited_locations_table";
import EntityBlobsRow from "./entity_blobs_table";
import EntityDeletionTimerComponentsRow from "./entity_deletion_timer_components_table";
import EpComponentsRow from "./ep_components_table";
import EquipmentComponentsRow from "./equipment_components_table";
import EquipmentStatBlockCacheComponentsRow from "./equipment_stat_block_cache_components_table";
import EquipmentStatBlockDirtyFlagComponentsRow from "./equipment_stat_block_dirty_flag_components_table";
import FearStatusComponentsRow from "./fear_status_components_table";
import HpComponentsRow from "./hp_components_table";
import HpShareAppliedComponentsRow from "./hp_share_applied_components_table";
import HpShareComponentsRow from "./hp_share_components_table";
import ItemComponentsRow from "./item_components_table";
import LocationComponentsRow from "./location_components_table";
import LocationMapComponentsRow from "./location_map_components_table";
import LoginRequestVotersRow from "./login_request_voters_table";
import LoginRequestsRow from "./login_requests_table";
import LoginResponsesRow from "./login_responses_table";
import MapCheckpointsComponentsRow from "./map_checkpoints_components_table";
import MapCleanupTimerComponentsRow from "./map_cleanup_timer_components_table";
import MapInstanceComponentsRow from "./map_instance_components_table";
import MapRoomsComponentsRow from "./map_rooms_components_table";
import NameComponentsRow from "./name_components_table";
import NamedEntitiesRow from "./named_entities_table";
import ObservableEventsRow from "./observable_events_table";
import OfferedActionsComponentsRow from "./offered_actions_components_table";
import OpenComponentsRow from "./open_components_table";
import PartyComponentsRow from "./party_components_table";
import PathBlockerComponentsRow from "./path_blocker_components_table";
import PathComponentsRow from "./path_components_table";
import PendingConnectionsComponentsRow from "./pending_connections_components_table";
import PerishedComponentsRow from "./perished_components_table";
import PinnedActionsComponentsRow from "./pinned_actions_components_table";
import PlayerControllerComponentsRow from "./player_controller_components_table";
import PlayerDeactivationTimerComponentsRow from "./player_deactivation_timer_components_table";
import QuestStatBlockCacheComponentsRow from "./quest_stat_block_cache_components_table";
import QuestStatBlockDirtyFlagComponentsRow from "./quest_stat_block_dirty_flag_components_table";
import QuestsRow from "./quests_table";
import QuestsRoomsRolesRow from "./quests_rooms_roles_table";
import RelicsRow from "./relics_table";
import RelicsComponentsRow from "./relics_components_table";
import RemainsComponentsRow from "./remains_components_table";
import RespawnTimerComponentsRow from "./respawn_timer_components_table";
import RolesRow from "./roles_table";
import SpecialActionsRow from "./special_actions_table";
import StanceForcedComponentsRow from "./stance_forced_components_table";
import StanceLoadoutsComponentsRow from "./stance_loadouts_components_table";
import StancesRow from "./stances_table";
import StatusStatBlockCacheComponentsRow from "./status_stat_block_cache_components_table";
import StatusStatBlockDirtyFlagComponentsRow from "./status_stat_block_dirty_flag_components_table";
import TotalStatBlockComponentsRow from "./total_stat_block_components_table";
import TotalStatBlockDirtyFlagComponentsRow from "./total_stat_block_dirty_flag_components_table";
import TraitsComponentsRow from "./traits_components_table";
import TraitsStatBlockCacheComponentsRow from "./traits_stat_block_cache_components_table";
import TraitsStatBlockDirtyFlagComponentsRow from "./traits_stat_block_dirty_flag_components_table";
import TurnPausedComponentsRow from "./turn_paused_components_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  account_identities: __table({
    name: 'account_identities',
    indexes: [
      { accessor: 'account_id', name: 'account_identities_account_id_idx_btree', algorithm: 'btree', columns: [
        'accountId',
      ] },
      { accessor: 'identity', name: 'account_identities_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'account_identities_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, AccountIdentitiesRow),
  account_roles: __table({
    name: 'account_roles',
    indexes: [
      { accessor: 'account_id', name: 'account_roles_account_id_idx_btree', algorithm: 'btree', columns: [
        'accountId',
      ] },
      { accessor: 'id', name: 'account_roles_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'account_roles_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AccountRolesRow),
  accounts: __table({
    name: 'accounts',
    indexes: [
      { accessor: 'id', name: 'accounts_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'name', name: 'accounts_name_idx_btree', algorithm: 'btree', columns: [
        'name',
      ] },
    ],
    constraints: [
      { name: 'accounts_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'accounts_name_key', constraint: 'unique', columns: ['name'] },
    ],
  }, AccountsRow),
  action_cursor_components: __table({
    name: 'action_cursor_components',
    indexes: [
      { accessor: 'entity_id', name: 'action_cursor_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'action_cursor_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, ActionCursorComponentsRow),
  action_queue_components: __table({
    name: 'action_queue_components',
    indexes: [
      { accessor: 'entity_id', name: 'action_queue_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'action_queue_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, ActionQueueComponentsRow),
  action_queue_dirty_components: __table({
    name: 'action_queue_dirty_components',
    indexes: [
      { accessor: 'entity_id', name: 'action_queue_dirty_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'action_queue_dirty_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, ActionQueueDirtyComponentsRow),
  action_rounds: __table({
    name: 'action_rounds',
    indexes: [
      { accessor: 'action_sequence', name: 'action_rounds_action_id_sequence_index_idx_btree', algorithm: 'btree', columns: [
        'actionId',
        'sequenceIndex',
      ] },
      { accessor: 'id', name: 'action_rounds_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'action_rounds_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ActionRoundsRow),
  action_state_components: __table({
    name: 'action_state_components',
    indexes: [
      { accessor: 'entity_id', name: 'action_state_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'action_state_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, ActionStateComponentsRow),
  actionless_since_components: __table({
    name: 'actionless_since_components',
    indexes: [
      { accessor: 'entity_id', name: 'actionless_since_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'actionless_since_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, ActionlessSinceComponentsRow),
  actions: __table({
    name: 'actions',
    indexes: [
      { accessor: 'id', name: 'actions_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'name', name: 'actions_name_idx_btree', algorithm: 'btree', columns: [
        'name',
      ] },
    ],
    constraints: [
      { name: 'actions_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'actions_name_key', constraint: 'unique', columns: ['name'] },
    ],
  }, ActionsRow),
  actions_components: __table({
    name: 'actions_components',
    indexes: [
      { accessor: 'entity_id', name: 'actions_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'actions_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, ActionsComponentsRow),
  active_stance_components: __table({
    name: 'active_stance_components',
    indexes: [
      { accessor: 'entity_id', name: 'active_stance_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'active_stance_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, ActiveStanceComponentsRow),
  allegiance_components: __table({
    name: 'allegiance_components',
    indexes: [
      { accessor: 'allegiance_entity_id', name: 'allegiance_components_allegiance_entity_id_idx_btree', algorithm: 'btree', columns: [
        'allegianceEntityId',
      ] },
      { accessor: 'entity_id', name: 'allegiance_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'allegiance_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, AllegianceComponentsRow),
  appearance_features: __table({
    name: 'appearance_features',
    indexes: [
      { accessor: 'index', name: 'appearance_features_index_idx_btree', algorithm: 'btree', columns: [
        'index',
      ] },
      { accessor: 'name', name: 'appearance_features_name_idx_btree', algorithm: 'btree', columns: [
        'name',
      ] },
    ],
    constraints: [
      { name: 'appearance_features_index_key', constraint: 'unique', columns: ['index'] },
      { name: 'appearance_features_name_key', constraint: 'unique', columns: ['name'] },
    ],
  }, AppearanceFeaturesRow),
  appearance_features_components: __table({
    name: 'appearance_features_components',
    indexes: [
      { accessor: 'entity_id', name: 'appearance_features_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'appearance_features_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, AppearanceFeaturesComponentsRow),
  armaments: __table({
    name: 'armaments',
    indexes: [
      { accessor: 'id', name: 'armaments_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'name', name: 'armaments_name_idx_btree', algorithm: 'btree', columns: [
        'name',
      ] },
    ],
    constraints: [
      { name: 'armaments_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'armaments_name_key', constraint: 'unique', columns: ['name'] },
    ],
  }, ArmamentsRow),
  armor_components: __table({
    name: 'armor_components',
    indexes: [
      { accessor: 'entity_id', name: 'armor_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'armor_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, ArmorComponentsRow),
  armors: __table({
    name: 'armors',
    indexes: [
      { accessor: 'id', name: 'armors_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'name', name: 'armors_name_idx_btree', algorithm: 'btree', columns: [
        'name',
      ] },
    ],
    constraints: [
      { name: 'armors_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'armors_name_key', constraint: 'unique', columns: ['name'] },
    ],
  }, ArmorsRow),
  attack_components: __table({
    name: 'attack_components',
    indexes: [
      { accessor: 'entity_id', name: 'attack_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'attack_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, AttackComponentsRow),
  baseline_components: __table({
    name: 'baseline_components',
    indexes: [
      { accessor: 'entity_id', name: 'baseline_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'baseline_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, BaselineComponentsRow),
  braced_status_components: __table({
    name: 'braced_status_components',
    indexes: [
      { accessor: 'entity_id', name: 'braced_status_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'braced_status_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, BracedStatusComponentsRow),
  checkpoint_binding_components: __table({
    name: 'checkpoint_binding_components',
    indexes: [
      { accessor: 'entity_id', name: 'checkpoint_binding_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'checkpoint_binding_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, CheckpointBindingComponentsRow),
  checkpoint_components: __table({
    name: 'checkpoint_components',
    indexes: [
      { accessor: 'entity_id', name: 'checkpoint_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'checkpoint_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, CheckpointComponentsRow),
  checkpoint_object_components: __table({
    name: 'checkpoint_object_components',
    indexes: [
      { accessor: 'entity_id', name: 'checkpoint_object_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'checkpoint_object_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, CheckpointObjectComponentsRow),
  courage_status_components: __table({
    name: 'courage_status_components',
    indexes: [
      { accessor: 'entity_id', name: 'courage_status_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'courage_status_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, CourageStatusComponentsRow),
  default_actions_components: __table({
    name: 'default_actions_components',
    indexes: [
      { accessor: 'entity_id', name: 'default_actions_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'default_actions_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, DefaultActionsComponentsRow),
  default_armaments_components: __table({
    name: 'default_armaments_components',
    indexes: [
      { accessor: 'entity_id', name: 'default_armaments_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'default_armaments_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, DefaultArmamentsComponentsRow),
  defeat_drop_components: __table({
    name: 'defeat_drop_components',
    indexes: [
      { accessor: 'entity_id', name: 'defeat_drop_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'defeat_drop_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, DefeatDropComponentsRow),
  differentiable_components: __table({
    name: 'differentiable_components',
    indexes: [
      { accessor: 'entity_id', name: 'differentiable_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'differentiable_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, DifferentiableComponentsRow),
  enemy_controller_components: __table({
    name: 'enemy_controller_components',
    indexes: [
      { accessor: 'entity_id', name: 'enemy_controller_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'enemy_controller_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, EnemyControllerComponentsRow),
  entities: __table({
    name: 'entities',
    indexes: [
      { accessor: 'id', name: 'entities_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'entities_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EntitiesRow),
  entities_quests_progress: __table({
    name: 'entities_quests_progress',
    indexes: [
      { accessor: 'entity_id', name: 'entities_quests_progress_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
      { accessor: 'id', name: 'entities_quests_progress_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'quest_id', name: 'entities_quests_progress_quest_id_idx_btree', algorithm: 'btree', columns: [
        'questId',
      ] },
    ],
    constraints: [
      { name: 'entities_quests_progress_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EntitiesQuestsProgressRow),
  entities_visited_locations: __table({
    name: 'entities_visited_locations',
    indexes: [
      { accessor: 'id', name: 'entities_visited_locations_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'location_entity_id', name: 'entities_visited_locations_location_entity_id_idx_btree', algorithm: 'btree', columns: [
        'locationEntityId',
      ] },
      { accessor: 'visitor_entity_id', name: 'entities_visited_locations_visitor_entity_id_idx_btree', algorithm: 'btree', columns: [
        'visitorEntityId',
      ] },
    ],
    constraints: [
      { name: 'entities_visited_locations_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EntitiesVisitedLocationsRow),
  entity_blobs: __table({
    name: 'entity_blobs',
    indexes: [
    ],
    constraints: [
    ],
  }, EntityBlobsRow),
  entity_deletion_timer_components: __table({
    name: 'entity_deletion_timer_components',
    indexes: [
      { accessor: 'entity_id', name: 'entity_deletion_timer_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'entity_deletion_timer_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, EntityDeletionTimerComponentsRow),
  ep_components: __table({
    name: 'ep_components',
    indexes: [
      { accessor: 'entity_id', name: 'ep_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'ep_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, EpComponentsRow),
  equipment_components: __table({
    name: 'equipment_components',
    indexes: [
      { accessor: 'entity_id', name: 'equipment_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'equipment_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, EquipmentComponentsRow),
  equipment_stat_block_cache_components: __table({
    name: 'equipment_stat_block_cache_components',
    indexes: [
      { accessor: 'entity_id', name: 'equipment_stat_block_cache_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'equipment_stat_block_cache_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, EquipmentStatBlockCacheComponentsRow),
  equipment_stat_block_dirty_flag_components: __table({
    name: 'equipment_stat_block_dirty_flag_components',
    indexes: [
      { accessor: 'entity_id', name: 'equipment_stat_block_dirty_flag_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'equipment_stat_block_dirty_flag_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, EquipmentStatBlockDirtyFlagComponentsRow),
  fear_status_components: __table({
    name: 'fear_status_components',
    indexes: [
      { accessor: 'entity_id', name: 'fear_status_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'fear_status_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, FearStatusComponentsRow),
  hp_components: __table({
    name: 'hp_components',
    indexes: [
      { accessor: 'entity_id', name: 'hp_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'hp_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, HpComponentsRow),
  hp_share_applied_components: __table({
    name: 'hp_share_applied_components',
    indexes: [
      { accessor: 'entity_id', name: 'hp_share_applied_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'hp_share_applied_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
    event: true,
  }, HpShareAppliedComponentsRow),
  hp_share_components: __table({
    name: 'hp_share_components',
    indexes: [
      { accessor: 'entity_id', name: 'hp_share_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
      { accessor: 'partner_entity_id', name: 'hp_share_components_partner_entity_id_idx_btree', algorithm: 'btree', columns: [
        'partnerEntityId',
      ] },
    ],
    constraints: [
      { name: 'hp_share_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, HpShareComponentsRow),
  item_components: __table({
    name: 'item_components',
    indexes: [
      { accessor: 'entity_id', name: 'item_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'item_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, ItemComponentsRow),
  location_components: __table({
    name: 'location_components',
    indexes: [
      { accessor: 'entity_id', name: 'location_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
      { accessor: 'location_entity_id', name: 'location_components_location_entity_id_idx_btree', algorithm: 'btree', columns: [
        'locationEntityId',
      ] },
    ],
    constraints: [
      { name: 'location_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, LocationComponentsRow),
  location_map_components: __table({
    name: 'location_map_components',
    indexes: [
      { accessor: 'entity_id', name: 'location_map_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'location_map_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, LocationMapComponentsRow),
  login_request_voters: __table({
    name: 'login_request_voters',
    indexes: [
      { accessor: 'id', name: 'login_request_voters_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'login_request_id', name: 'login_request_voters_login_request_id_idx_btree', algorithm: 'btree', columns: [
        'loginRequestId',
      ] },
    ],
    constraints: [
      { name: 'login_request_voters_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, LoginRequestVotersRow),
  login_requests: __table({
    name: 'login_requests',
    indexes: [
      { accessor: 'account_id', name: 'login_requests_account_id_idx_btree', algorithm: 'btree', columns: [
        'accountId',
      ] },
      { accessor: 'id', name: 'login_requests_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'login_requests_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, LoginRequestsRow),
  login_responses: __table({
    name: 'login_responses',
    indexes: [
      { accessor: 'id', name: 'login_responses_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'login_request_id', name: 'login_responses_login_request_id_idx_btree', algorithm: 'btree', columns: [
        'loginRequestId',
      ] },
    ],
    constraints: [
      { name: 'login_responses_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, LoginResponsesRow),
  map_checkpoints_components: __table({
    name: 'map_checkpoints_components',
    indexes: [
      { accessor: 'entity_id', name: 'map_checkpoints_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'map_checkpoints_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, MapCheckpointsComponentsRow),
  map_cleanup_timer_components: __table({
    name: 'map_cleanup_timer_components',
    indexes: [
      { accessor: 'entity_id', name: 'map_cleanup_timer_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'map_cleanup_timer_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, MapCleanupTimerComponentsRow),
  map_instance_components: __table({
    name: 'map_instance_components',
    indexes: [
      { accessor: 'entity_id', name: 'map_instance_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
      { accessor: 'party_leader', name: 'map_instance_components_party_leader_idx_btree', algorithm: 'btree', columns: [
        'partyLeader',
      ] },
    ],
    constraints: [
      { name: 'map_instance_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, MapInstanceComponentsRow),
  map_rooms_components: __table({
    name: 'map_rooms_components',
    indexes: [
      { accessor: 'entity_id', name: 'map_rooms_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'map_rooms_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, MapRoomsComponentsRow),
  name_components: __table({
    name: 'name_components',
    indexes: [
      { accessor: 'entity_id', name: 'name_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
      { accessor: 'name', name: 'name_components_name_idx_btree', algorithm: 'btree', columns: [
        'name',
      ] },
    ],
    constraints: [
      { name: 'name_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
      { name: 'name_components_name_key', constraint: 'unique', columns: ['name'] },
    ],
  }, NameComponentsRow),
  named_entities: __table({
    name: 'named_entities',
    indexes: [
      { accessor: 'name', name: 'named_entities_name_idx_btree', algorithm: 'btree', columns: [
        'name',
      ] },
    ],
    constraints: [
      { name: 'named_entities_name_key', constraint: 'unique', columns: ['name'] },
    ],
  }, NamedEntitiesRow),
  observable_events: __table({
    name: 'observable_events',
    indexes: [
      { accessor: 'id', name: 'observable_events_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'observable_events_id_key', constraint: 'unique', columns: ['id'] },
    ],
    event: true,
  }, ObservableEventsRow),
  offered_actions_components: __table({
    name: 'offered_actions_components',
    indexes: [
      { accessor: 'entity_id', name: 'offered_actions_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'offered_actions_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, OfferedActionsComponentsRow),
  open_components: __table({
    name: 'open_components',
    indexes: [
      { accessor: 'entity_id', name: 'open_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'open_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, OpenComponentsRow),
  party_components: __table({
    name: 'party_components',
    indexes: [
      { accessor: 'entity_id', name: 'party_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
      { accessor: 'party_leader', name: 'party_components_party_leader_idx_btree', algorithm: 'btree', columns: [
        'partyLeader',
      ] },
    ],
    constraints: [
      { name: 'party_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, PartyComponentsRow),
  path_blocker_components: __table({
    name: 'path_blocker_components',
    indexes: [
      { accessor: 'blocker_entity_id', name: 'path_blocker_components_blocker_entity_id_idx_btree', algorithm: 'btree', columns: [
        'blockerEntityId',
      ] },
      { accessor: 'entity_id', name: 'path_blocker_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'path_blocker_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, PathBlockerComponentsRow),
  path_components: __table({
    name: 'path_components',
    indexes: [
      { accessor: 'destination_entity_id', name: 'path_components_destination_entity_id_idx_btree', algorithm: 'btree', columns: [
        'destinationEntityId',
      ] },
      { accessor: 'entity_id', name: 'path_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'path_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, PathComponentsRow),
  pending_connections_components: __table({
    name: 'pending_connections_components',
    indexes: [
      { accessor: 'entity_id', name: 'pending_connections_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'pending_connections_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, PendingConnectionsComponentsRow),
  perished_components: __table({
    name: 'perished_components',
    indexes: [
      { accessor: 'entity_id', name: 'perished_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'perished_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, PerishedComponentsRow),
  pinned_actions_components: __table({
    name: 'pinned_actions_components',
    indexes: [
      { accessor: 'entity_id', name: 'pinned_actions_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'pinned_actions_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, PinnedActionsComponentsRow),
  player_controller_components: __table({
    name: 'player_controller_components',
    indexes: [
      { accessor: 'account_id', name: 'player_controller_components_account_id_idx_btree', algorithm: 'btree', columns: [
        'accountId',
      ] },
      { accessor: 'entity_id', name: 'player_controller_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'player_controller_components_account_id_key', constraint: 'unique', columns: ['accountId'] },
      { name: 'player_controller_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, PlayerControllerComponentsRow),
  player_deactivation_timer_components: __table({
    name: 'player_deactivation_timer_components',
    indexes: [
      { accessor: 'entity_id', name: 'player_deactivation_timer_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'player_deactivation_timer_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, PlayerDeactivationTimerComponentsRow),
  quest_stat_block_cache_components: __table({
    name: 'quest_stat_block_cache_components',
    indexes: [
      { accessor: 'entity_id', name: 'quest_stat_block_cache_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'quest_stat_block_cache_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, QuestStatBlockCacheComponentsRow),
  quest_stat_block_dirty_flag_components: __table({
    name: 'quest_stat_block_dirty_flag_components',
    indexes: [
      { accessor: 'entity_id', name: 'quest_stat_block_dirty_flag_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'quest_stat_block_dirty_flag_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, QuestStatBlockDirtyFlagComponentsRow),
  quests: __table({
    name: 'quests',
    indexes: [
      { accessor: 'id', name: 'quests_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'name', name: 'quests_name_idx_btree', algorithm: 'btree', columns: [
        'name',
      ] },
    ],
    constraints: [
      { name: 'quests_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'quests_name_key', constraint: 'unique', columns: ['name'] },
    ],
  }, QuestsRow),
  quests_rooms_roles: __table({
    name: 'quests_rooms_roles',
    indexes: [
      { accessor: 'id', name: 'quests_rooms_roles_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'quest_id', name: 'quests_rooms_roles_quest_id_idx_btree', algorithm: 'btree', columns: [
        'questId',
      ] },
      { accessor: 'room_entity_id', name: 'quests_rooms_roles_room_entity_id_idx_btree', algorithm: 'btree', columns: [
        'roomEntityId',
      ] },
    ],
    constraints: [
      { name: 'quests_rooms_roles_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, QuestsRoomsRolesRow),
  relics: __table({
    name: 'relics',
    indexes: [
      { accessor: 'id', name: 'relics_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'name', name: 'relics_name_idx_btree', algorithm: 'btree', columns: [
        'name',
      ] },
    ],
    constraints: [
      { name: 'relics_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'relics_name_key', constraint: 'unique', columns: ['name'] },
    ],
  }, RelicsRow),
  relics_components: __table({
    name: 'relics_components',
    indexes: [
      { accessor: 'entity_id', name: 'relics_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'relics_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, RelicsComponentsRow),
  remains_components: __table({
    name: 'remains_components',
    indexes: [
      { accessor: 'entity_id', name: 'remains_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'remains_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, RemainsComponentsRow),
  respawn_timer_components: __table({
    name: 'respawn_timer_components',
    indexes: [
      { accessor: 'entity_id', name: 'respawn_timer_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'respawn_timer_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, RespawnTimerComponentsRow),
  roles: __table({
    name: 'roles',
    indexes: [
      { accessor: 'id', name: 'roles_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'name', name: 'roles_name_idx_btree', algorithm: 'btree', columns: [
        'name',
      ] },
    ],
    constraints: [
      { name: 'roles_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'roles_name_key', constraint: 'unique', columns: ['name'] },
    ],
  }, RolesRow),
  special_actions: __table({
    name: 'special_actions',
    indexes: [
      { accessor: 'key', name: 'special_actions_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'special_actions_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, SpecialActionsRow),
  stance_forced_components: __table({
    name: 'stance_forced_components',
    indexes: [
      { accessor: 'entity_id', name: 'stance_forced_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'stance_forced_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, StanceForcedComponentsRow),
  stance_loadouts_components: __table({
    name: 'stance_loadouts_components',
    indexes: [
      { accessor: 'entity_id', name: 'stance_loadouts_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'stance_loadouts_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, StanceLoadoutsComponentsRow),
  stances: __table({
    name: 'stances',
    indexes: [
      { accessor: 'id', name: 'stances_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'name', name: 'stances_name_idx_btree', algorithm: 'btree', columns: [
        'name',
      ] },
    ],
    constraints: [
      { name: 'stances_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'stances_name_key', constraint: 'unique', columns: ['name'] },
    ],
  }, StancesRow),
  status_stat_block_cache_components: __table({
    name: 'status_stat_block_cache_components',
    indexes: [
      { accessor: 'entity_id', name: 'status_stat_block_cache_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'status_stat_block_cache_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, StatusStatBlockCacheComponentsRow),
  status_stat_block_dirty_flag_components: __table({
    name: 'status_stat_block_dirty_flag_components',
    indexes: [
      { accessor: 'entity_id', name: 'status_stat_block_dirty_flag_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'status_stat_block_dirty_flag_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, StatusStatBlockDirtyFlagComponentsRow),
  total_stat_block_components: __table({
    name: 'total_stat_block_components',
    indexes: [
      { accessor: 'entity_id', name: 'total_stat_block_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'total_stat_block_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, TotalStatBlockComponentsRow),
  total_stat_block_dirty_flag_components: __table({
    name: 'total_stat_block_dirty_flag_components',
    indexes: [
      { accessor: 'entity_id', name: 'total_stat_block_dirty_flag_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'total_stat_block_dirty_flag_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, TotalStatBlockDirtyFlagComponentsRow),
  traits_components: __table({
    name: 'traits_components',
    indexes: [
      { accessor: 'entity_id', name: 'traits_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'traits_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, TraitsComponentsRow),
  traits_stat_block_cache_components: __table({
    name: 'traits_stat_block_cache_components',
    indexes: [
      { accessor: 'entity_id', name: 'traits_stat_block_cache_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'traits_stat_block_cache_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, TraitsStatBlockCacheComponentsRow),
  traits_stat_block_dirty_flag_components: __table({
    name: 'traits_stat_block_dirty_flag_components',
    indexes: [
      { accessor: 'entity_id', name: 'traits_stat_block_dirty_flag_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'traits_stat_block_dirty_flag_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, TraitsStatBlockDirtyFlagComponentsRow),
  turn_paused_components: __table({
    name: 'turn_paused_components',
    indexes: [
      { accessor: 'entity_id', name: 'turn_paused_components_entity_id_idx_btree', algorithm: 'btree', columns: [
        'entityId',
      ] },
    ],
    constraints: [
      { name: 'turn_paused_components_entity_id_key', constraint: 'unique', columns: ['entityId'] },
    ],
  }, TurnPausedComponentsRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("accept_login_request", AcceptLoginRequestReducer),
  __reducerSchema("act", ActReducer),
  __reducerSchema("assign_stance_actions", AssignStanceActionsReducer),
  __reducerSchema("assign_stance_armaments", AssignStanceArmamentsReducer),
  __reducerSchema("bootstrap_admin", BootstrapAdminReducer),
  __reducerSchema("clear_armor", ClearArmorReducer),
  __reducerSchema("create_account", CreateAccountReducer),
  __reducerSchema("grant_role", GrantRoleReducer),
  __reducerSchema("login_with_password", LoginWithPasswordReducer),
  __reducerSchema("provision_account", ProvisionAccountReducer),
  __reducerSchema("push_assets", PushAssetsReducer),
  __reducerSchema("refuse_login_request", RefuseLoginRequestReducer),
  __reducerSchema("request_login", RequestLoginReducer),
  __reducerSchema("set_armor", SetArmorReducer),
  __reducerSchema("set_default_actions", SetDefaultActionsReducer),
  __reducerSchema("set_default_armaments", SetDefaultArmamentsReducer),
  __reducerSchema("set_password", SetPasswordReducer),
  __reducerSchema("set_relics", SetRelicsReducer),
  __reducerSchema("set_stance", SetStanceReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.1.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

