// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";

// Import and reexport all reducer arg types
import { Act } from "./act_reducer.ts";
export { Act };
import { AddTrait } from "./add_trait_reducer.ts";
export { AddTrait };
import { Damage } from "./damage_reducer.ts";
export { Damage };
import { DeleteTarget } from "./delete_target_reducer.ts";
export { DeleteTarget };
import { IdentityConnected } from "./identity_connected_reducer.ts";
export { IdentityConnected };
import { IdentityDisconnected } from "./identity_disconnected_reducer.ts";
export { IdentityDisconnected };
import { RunSystem } from "./run_system_reducer.ts";
export { RunSystem };
import { Target } from "./target_reducer.ts";
export { Target };

// Import and reexport all table handle types
import { ActionAppearancesTableHandle } from "./action_appearances_table.ts";
export { ActionAppearancesTableHandle };
import { ActionHotkeysComponentsTableHandle } from "./action_hotkeys_components_table.ts";
export { ActionHotkeysComponentsTableHandle };
import { ActionOptionsComponentsTableHandle } from "./action_options_components_table.ts";
export { ActionOptionsComponentsTableHandle };
import { ActionStateComponentsTableHandle } from "./action_state_components_table.ts";
export { ActionStateComponentsTableHandle };
import { ActionStepsTableHandle } from "./action_steps_table.ts";
export { ActionStepsTableHandle };
import { ActionsTableHandle } from "./actions_table.ts";
export { ActionsTableHandle };
import { ActionsComponentsTableHandle } from "./actions_components_table.ts";
export { ActionsComponentsTableHandle };
import { AllegianceComponentsTableHandle } from "./allegiance_components_table.ts";
export { AllegianceComponentsTableHandle };
import { AppearanceFeaturesTableHandle } from "./appearance_features_table.ts";
export { AppearanceFeaturesTableHandle };
import { AppearanceFeaturesComponentsTableHandle } from "./appearance_features_components_table.ts";
export { AppearanceFeaturesComponentsTableHandle };
import { AttackComponentsTableHandle } from "./attack_components_table.ts";
export { AttackComponentsTableHandle };
import { BaselineComponentsTableHandle } from "./baseline_components_table.ts";
export { BaselineComponentsTableHandle };
import { BaselinesTableHandle } from "./baselines_table.ts";
export { BaselinesTableHandle };
import { EnAppearanceFeaturesTableHandle } from "./en_appearance_features_table.ts";
export { EnAppearanceFeaturesTableHandle };
import { EntitiesTableHandle } from "./entities_table.ts";
export { EntitiesTableHandle };
import { EntityBlobsTableHandle } from "./entity_blobs_table.ts";
export { EntityBlobsTableHandle };
import { EntityDeactivationTimerComponentsTableHandle } from "./entity_deactivation_timer_components_table.ts";
export { EntityDeactivationTimerComponentsTableHandle };
import { EntityProminenceComponentsTableHandle } from "./entity_prominence_components_table.ts";
export { EntityProminenceComponentsTableHandle };
import { EpComponentsTableHandle } from "./ep_components_table.ts";
export { EpComponentsTableHandle };
import { HpComponentsTableHandle } from "./hp_components_table.ts";
export { HpComponentsTableHandle };
import { IdentityInactiveEntitiesTableHandle } from "./identity_inactive_entities_table.ts";
export { IdentityInactiveEntitiesTableHandle };
import { LocationComponentsTableHandle } from "./location_components_table.ts";
export { LocationComponentsTableHandle };
import { LocationMapComponentsTableHandle } from "./location_map_components_table.ts";
export { LocationMapComponentsTableHandle };
import { NameComponentsTableHandle } from "./name_components_table.ts";
export { NameComponentsTableHandle };
import { NamedInactiveEntitiesTableHandle } from "./named_inactive_entities_table.ts";
export { NamedInactiveEntitiesTableHandle };
import { ObservableEventsTableHandle } from "./observable_events_table.ts";
export { ObservableEventsTableHandle };
import { PathComponentsTableHandle } from "./path_components_table.ts";
export { PathComponentsTableHandle };
import { PlayerControllerComponentsTableHandle } from "./player_controller_components_table.ts";
export { PlayerControllerComponentsTableHandle };
import { QueuedActionStateComponentsTableHandle } from "./queued_action_state_components_table.ts";
export { QueuedActionStateComponentsTableHandle };
import { RealizedMapComponentsTableHandle } from "./realized_map_components_table.ts";
export { RealizedMapComponentsTableHandle };
import { RngSeedComponentsTableHandle } from "./rng_seed_components_table.ts";
export { RngSeedComponentsTableHandle };
import { SystemTimersTableHandle } from "./system_timers_table.ts";
export { SystemTimersTableHandle };
import { TargetComponentsTableHandle } from "./target_components_table.ts";
export { TargetComponentsTableHandle };
import { TotalStatBlockDirtyFlagComponentsTableHandle } from "./total_stat_block_dirty_flag_components_table.ts";
export { TotalStatBlockDirtyFlagComponentsTableHandle };
import { TraitsTableHandle } from "./traits_table.ts";
export { TraitsTableHandle };
import { TraitsComponentsTableHandle } from "./traits_components_table.ts";
export { TraitsComponentsTableHandle };
import { TraitsStatBlockCacheComponentsTableHandle } from "./traits_stat_block_cache_components_table.ts";
export { TraitsStatBlockCacheComponentsTableHandle };
import { TraitsStatBlockDirtyFlagComponentsTableHandle } from "./traits_stat_block_dirty_flag_components_table.ts";
export { TraitsStatBlockDirtyFlagComponentsTableHandle };
import { UnrealizedMapComponentsTableHandle } from "./unrealized_map_components_table.ts";
export { UnrealizedMapComponentsTableHandle };

// Import and reexport all types
import { Action } from "./action_type.ts";
export { Action };
import { ActionAppearance } from "./action_appearance_type.ts";
export { ActionAppearance };
import { ActionEffect } from "./action_effect_type.ts";
export { ActionEffect };
import { ActionHotkey } from "./action_hotkey_type.ts";
export { ActionHotkey };
import { ActionHotkeysComponent } from "./action_hotkeys_component_type.ts";
export { ActionHotkeysComponent };
import { ActionOption } from "./action_option_type.ts";
export { ActionOption };
import { ActionOptionsComponent } from "./action_options_component_type.ts";
export { ActionOptionsComponent };
import { ActionStateComponent } from "./action_state_component_type.ts";
export { ActionStateComponent };
import { ActionStep } from "./action_step_type.ts";
export { ActionStep };
import { ActionType } from "./action_type_type.ts";
export { ActionType };
import { ActionsComponent } from "./actions_component_type.ts";
export { ActionsComponent };
import { AllegianceComponent } from "./allegiance_component_type.ts";
export { AllegianceComponent };
import { AppearanceFeature } from "./appearance_feature_type.ts";
export { AppearanceFeature };
import { AppearanceFeatureType } from "./appearance_feature_type_type.ts";
export { AppearanceFeatureType };
import { AppearanceFeaturesComponent } from "./appearance_features_component_type.ts";
export { AppearanceFeaturesComponent };
import { AttackComponent } from "./attack_component_type.ts";
export { AttackComponent };
import { Baseline } from "./baseline_type.ts";
export { Baseline };
import { BaselineComponent } from "./baseline_component_type.ts";
export { BaselineComponent };
import { Buff } from "./buff_type.ts";
export { Buff };
import { ComponentSet } from "./component_set_type.ts";
export { ComponentSet };
import { Entity } from "./entity_type.ts";
export { Entity };
import { EntityBlob } from "./entity_blob_type.ts";
export { EntityBlob };
import { EntityEvent } from "./entity_event_type.ts";
export { EntityEvent };
import { EntityProminenceComponent } from "./entity_prominence_component_type.ts";
export { EntityProminenceComponent };
import { EpComponent } from "./ep_component_type.ts";
export { EpComponent };
import { EventType } from "./event_type_type.ts";
export { EventType };
import { FlagComponent } from "./flag_component_type.ts";
export { FlagComponent };
import { HpComponent } from "./hp_component_type.ts";
export { HpComponent };
import { IdentityInactiveEntity } from "./identity_inactive_entity_type.ts";
export { IdentityInactiveEntity };
import { LocationComponent } from "./location_component_type.ts";
export { LocationComponent };
import { LocationMapComponent } from "./location_map_component_type.ts";
export { LocationMapComponent };
import { MapComponent } from "./map_component_type.ts";
export { MapComponent };
import { MapLayout } from "./map_layout_type.ts";
export { MapLayout };
import { NameComponent } from "./name_component_type.ts";
export { NameComponent };
import { NamedInactiveEntity } from "./named_inactive_entity_type.ts";
export { NamedInactiveEntity };
import { PathComponent } from "./path_component_type.ts";
export { PathComponent };
import { PlayerControllerComponent } from "./player_controller_component_type.ts";
export { PlayerControllerComponent };
import { RngSeedComponent } from "./rng_seed_component_type.ts";
export { RngSeedComponent };
import { StatBlock } from "./stat_block_type.ts";
export { StatBlock };
import { StatBlockCacheComponent } from "./stat_block_cache_component_type.ts";
export { StatBlockCacheComponent };
import { SystemTimer } from "./system_timer_type.ts";
export { SystemTimer };
import { TargetComponent } from "./target_component_type.ts";
export { TargetComponent };
import { TimerComponent } from "./timer_component_type.ts";
export { TimerComponent };
import { Trait } from "./trait_type.ts";
export { Trait };
import { TraitsComponent } from "./traits_component_type.ts";
export { TraitsComponent };

const REMOTE_MODULE = {
  tables: {
    action_appearances: {
      tableName: "action_appearances",
      rowType: ActionAppearance.getTypeScriptAlgebraicType(),
      primaryKey: "actionId",
      primaryKeyInfo: {
        colName: "actionId",
        colType: ActionAppearance.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    action_hotkeys_components: {
      tableName: "action_hotkeys_components",
      rowType: ActionHotkeysComponent.getTypeScriptAlgebraicType(),
      primaryKey: "entityId",
      primaryKeyInfo: {
        colName: "entityId",
        colType: ActionHotkeysComponent.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    action_options_components: {
      tableName: "action_options_components",
      rowType: ActionOptionsComponent.getTypeScriptAlgebraicType(),
      primaryKey: "entityId",
      primaryKeyInfo: {
        colName: "entityId",
        colType: ActionOptionsComponent.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    action_state_components: {
      tableName: "action_state_components",
      rowType: ActionStateComponent.getTypeScriptAlgebraicType(),
      primaryKey: "entityId",
      primaryKeyInfo: {
        colName: "entityId",
        colType: ActionStateComponent.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    action_steps: {
      tableName: "action_steps",
      rowType: ActionStep.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: ActionStep.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    actions: {
      tableName: "actions",
      rowType: Action.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: Action.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    actions_components: {
      tableName: "actions_components",
      rowType: ActionsComponent.getTypeScriptAlgebraicType(),
      primaryKey: "entityId",
      primaryKeyInfo: {
        colName: "entityId",
        colType: ActionsComponent.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    allegiance_components: {
      tableName: "allegiance_components",
      rowType: AllegianceComponent.getTypeScriptAlgebraicType(),
      primaryKey: "entityId",
      primaryKeyInfo: {
        colName: "entityId",
        colType: AllegianceComponent.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    appearance_features: {
      tableName: "appearance_features",
      rowType: AppearanceFeature.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: AppearanceFeature.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    appearance_features_components: {
      tableName: "appearance_features_components",
      rowType: AppearanceFeaturesComponent.getTypeScriptAlgebraicType(),
      primaryKey: "entityId",
      primaryKeyInfo: {
        colName: "entityId",
        colType: AppearanceFeaturesComponent.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    attack_components: {
      tableName: "attack_components",
      rowType: AttackComponent.getTypeScriptAlgebraicType(),
      primaryKey: "entityId",
      primaryKeyInfo: {
        colName: "entityId",
        colType: AttackComponent.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    baseline_components: {
      tableName: "baseline_components",
      rowType: BaselineComponent.getTypeScriptAlgebraicType(),
      primaryKey: "entityId",
      primaryKeyInfo: {
        colName: "entityId",
        colType: BaselineComponent.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    baselines: {
      tableName: "baselines",
      rowType: Baseline.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: Baseline.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    en_appearance_features: {
      tableName: "en_appearance_features",
      rowType: AppearanceFeature.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: AppearanceFeature.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    entities: {
      tableName: "entities",
      rowType: Entity.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: Entity.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    entity_blobs: {
      tableName: "entity_blobs",
      rowType: EntityBlob.getTypeScriptAlgebraicType(),
    },
    entity_deactivation_timer_components: {
      tableName: "entity_deactivation_timer_components",
      rowType: TimerComponent.getTypeScriptAlgebraicType(),
      primaryKey: "entityId",
      primaryKeyInfo: {
        colName: "entityId",
        colType: TimerComponent.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    entity_prominence_components: {
      tableName: "entity_prominence_components",
      rowType: EntityProminenceComponent.getTypeScriptAlgebraicType(),
      primaryKey: "entityId",
      primaryKeyInfo: {
        colName: "entityId",
        colType: EntityProminenceComponent.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    ep_components: {
      tableName: "ep_components",
      rowType: EpComponent.getTypeScriptAlgebraicType(),
      primaryKey: "entityId",
      primaryKeyInfo: {
        colName: "entityId",
        colType: EpComponent.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    hp_components: {
      tableName: "hp_components",
      rowType: HpComponent.getTypeScriptAlgebraicType(),
      primaryKey: "entityId",
      primaryKeyInfo: {
        colName: "entityId",
        colType: HpComponent.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    identity_inactive_entities: {
      tableName: "identity_inactive_entities",
      rowType: IdentityInactiveEntity.getTypeScriptAlgebraicType(),
    },
    location_components: {
      tableName: "location_components",
      rowType: LocationComponent.getTypeScriptAlgebraicType(),
      primaryKey: "entityId",
      primaryKeyInfo: {
        colName: "entityId",
        colType: LocationComponent.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    location_map_components: {
      tableName: "location_map_components",
      rowType: LocationMapComponent.getTypeScriptAlgebraicType(),
      primaryKey: "entityId",
      primaryKeyInfo: {
        colName: "entityId",
        colType: LocationMapComponent.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    name_components: {
      tableName: "name_components",
      rowType: NameComponent.getTypeScriptAlgebraicType(),
      primaryKey: "entityId",
      primaryKeyInfo: {
        colName: "entityId",
        colType: NameComponent.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    named_inactive_entities: {
      tableName: "named_inactive_entities",
      rowType: NamedInactiveEntity.getTypeScriptAlgebraicType(),
      primaryKey: "prefabName",
      primaryKeyInfo: {
        colName: "prefabName",
        colType: NamedInactiveEntity.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    observable_events: {
      tableName: "observable_events",
      rowType: EntityEvent.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: EntityEvent.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    path_components: {
      tableName: "path_components",
      rowType: PathComponent.getTypeScriptAlgebraicType(),
      primaryKey: "entityId",
      primaryKeyInfo: {
        colName: "entityId",
        colType: PathComponent.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    player_controller_components: {
      tableName: "player_controller_components",
      rowType: PlayerControllerComponent.getTypeScriptAlgebraicType(),
      primaryKey: "entityId",
      primaryKeyInfo: {
        colName: "entityId",
        colType: PlayerControllerComponent.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    queued_action_state_components: {
      tableName: "queued_action_state_components",
      rowType: ActionStateComponent.getTypeScriptAlgebraicType(),
      primaryKey: "entityId",
      primaryKeyInfo: {
        colName: "entityId",
        colType: ActionStateComponent.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    realized_map_components: {
      tableName: "realized_map_components",
      rowType: MapComponent.getTypeScriptAlgebraicType(),
      primaryKey: "entityId",
      primaryKeyInfo: {
        colName: "entityId",
        colType: MapComponent.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    rng_seed_components: {
      tableName: "rng_seed_components",
      rowType: RngSeedComponent.getTypeScriptAlgebraicType(),
      primaryKey: "entityId",
      primaryKeyInfo: {
        colName: "entityId",
        colType: RngSeedComponent.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    system_timers: {
      tableName: "system_timers",
      rowType: SystemTimer.getTypeScriptAlgebraicType(),
      primaryKey: "scheduledId",
      primaryKeyInfo: {
        colName: "scheduledId",
        colType: SystemTimer.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    target_components: {
      tableName: "target_components",
      rowType: TargetComponent.getTypeScriptAlgebraicType(),
      primaryKey: "entityId",
      primaryKeyInfo: {
        colName: "entityId",
        colType: TargetComponent.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    total_stat_block_dirty_flag_components: {
      tableName: "total_stat_block_dirty_flag_components",
      rowType: FlagComponent.getTypeScriptAlgebraicType(),
      primaryKey: "entityId",
      primaryKeyInfo: {
        colName: "entityId",
        colType: FlagComponent.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    traits: {
      tableName: "traits",
      rowType: Trait.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: Trait.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    traits_components: {
      tableName: "traits_components",
      rowType: TraitsComponent.getTypeScriptAlgebraicType(),
      primaryKey: "entityId",
      primaryKeyInfo: {
        colName: "entityId",
        colType: TraitsComponent.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    traits_stat_block_cache_components: {
      tableName: "traits_stat_block_cache_components",
      rowType: StatBlockCacheComponent.getTypeScriptAlgebraicType(),
      primaryKey: "entityId",
      primaryKeyInfo: {
        colName: "entityId",
        colType: StatBlockCacheComponent.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    traits_stat_block_dirty_flag_components: {
      tableName: "traits_stat_block_dirty_flag_components",
      rowType: FlagComponent.getTypeScriptAlgebraicType(),
      primaryKey: "entityId",
      primaryKeyInfo: {
        colName: "entityId",
        colType: FlagComponent.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    unrealized_map_components: {
      tableName: "unrealized_map_components",
      rowType: MapComponent.getTypeScriptAlgebraicType(),
      primaryKey: "entityId",
      primaryKeyInfo: {
        colName: "entityId",
        colType: MapComponent.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
  },
  reducers: {
    act: {
      reducerName: "act",
      argsType: Act.getTypeScriptAlgebraicType(),
    },
    add_trait: {
      reducerName: "add_trait",
      argsType: AddTrait.getTypeScriptAlgebraicType(),
    },
    damage: {
      reducerName: "damage",
      argsType: Damage.getTypeScriptAlgebraicType(),
    },
    delete_target: {
      reducerName: "delete_target",
      argsType: DeleteTarget.getTypeScriptAlgebraicType(),
    },
    identity_connected: {
      reducerName: "identity_connected",
      argsType: IdentityConnected.getTypeScriptAlgebraicType(),
    },
    identity_disconnected: {
      reducerName: "identity_disconnected",
      argsType: IdentityDisconnected.getTypeScriptAlgebraicType(),
    },
    run_system: {
      reducerName: "run_system",
      argsType: RunSystem.getTypeScriptAlgebraicType(),
    },
    target: {
      reducerName: "target",
      argsType: Target.getTypeScriptAlgebraicType(),
    },
  },
  versionInfo: {
    cliVersion: "1.2.0",
  },
  // Constructors which are used by the DbConnectionImpl to
  // extract type information from the generated RemoteModule.
  //
  // NOTE: This is not strictly necessary for `eventContextConstructor` because
  // all we do is build a TypeScript object which we could have done inside the
  // SDK, but if in the future we wanted to create a class this would be
  // necessary because classes have methods, so we'll keep it.
  eventContextConstructor: (imp: DbConnectionImpl, event: Event<Reducer>) => {
    return {
      ...(imp as DbConnection),
      event
    }
  },
  dbViewConstructor: (imp: DbConnectionImpl) => {
    return new RemoteTables(imp);
  },
  reducersConstructor: (imp: DbConnectionImpl, setReducerFlags: SetReducerFlags) => {
    return new RemoteReducers(imp, setReducerFlags);
  },
  setReducerFlagsConstructor: () => {
    return new SetReducerFlags();
  }
}

// A type representing all the possible variants of a reducer.
export type Reducer = never
| { name: "Act", args: Act }
| { name: "AddTrait", args: AddTrait }
| { name: "Damage", args: Damage }
| { name: "DeleteTarget", args: DeleteTarget }
| { name: "IdentityConnected", args: IdentityConnected }
| { name: "IdentityDisconnected", args: IdentityDisconnected }
| { name: "RunSystem", args: RunSystem }
| { name: "Target", args: Target }
;

export class RemoteReducers {
  constructor(private connection: DbConnectionImpl, private setCallReducerFlags: SetReducerFlags) {}

  act(actionId: bigint, targetEntityId: bigint) {
    const __args = { actionId, targetEntityId };
    let __writer = new BinaryWriter(1024);
    Act.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("act", __argsBuffer, this.setCallReducerFlags.actFlags);
  }

  onAct(callback: (ctx: ReducerEventContext, actionId: bigint, targetEntityId: bigint) => void) {
    this.connection.onReducer("act", callback);
  }

  removeOnAct(callback: (ctx: ReducerEventContext, actionId: bigint, targetEntityId: bigint) => void) {
    this.connection.offReducer("act", callback);
  }

  addTrait(entityId: bigint, traitName: string) {
    const __args = { entityId, traitName };
    let __writer = new BinaryWriter(1024);
    AddTrait.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("add_trait", __argsBuffer, this.setCallReducerFlags.addTraitFlags);
  }

  onAddTrait(callback: (ctx: ReducerEventContext, entityId: bigint, traitName: string) => void) {
    this.connection.onReducer("add_trait", callback);
  }

  removeOnAddTrait(callback: (ctx: ReducerEventContext, entityId: bigint, traitName: string) => void) {
    this.connection.offReducer("add_trait", callback);
  }

  damage(entityId: bigint, damage: number) {
    const __args = { entityId, damage };
    let __writer = new BinaryWriter(1024);
    Damage.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("damage", __argsBuffer, this.setCallReducerFlags.damageFlags);
  }

  onDamage(callback: (ctx: ReducerEventContext, entityId: bigint, damage: number) => void) {
    this.connection.onReducer("damage", callback);
  }

  removeOnDamage(callback: (ctx: ReducerEventContext, entityId: bigint, damage: number) => void) {
    this.connection.offReducer("damage", callback);
  }

  deleteTarget() {
    this.connection.callReducer("delete_target", new Uint8Array(0), this.setCallReducerFlags.deleteTargetFlags);
  }

  onDeleteTarget(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("delete_target", callback);
  }

  removeOnDeleteTarget(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("delete_target", callback);
  }

  onIdentityConnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("identity_connected", callback);
  }

  removeOnIdentityConnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("identity_connected", callback);
  }

  onIdentityDisconnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("identity_disconnected", callback);
  }

  removeOnIdentityDisconnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("identity_disconnected", callback);
  }

  runSystem(timer: SystemTimer) {
    const __args = { timer };
    let __writer = new BinaryWriter(1024);
    RunSystem.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("run_system", __argsBuffer, this.setCallReducerFlags.runSystemFlags);
  }

  onRunSystem(callback: (ctx: ReducerEventContext, timer: SystemTimer) => void) {
    this.connection.onReducer("run_system", callback);
  }

  removeOnRunSystem(callback: (ctx: ReducerEventContext, timer: SystemTimer) => void) {
    this.connection.offReducer("run_system", callback);
  }

  target(targetEntityId: bigint) {
    const __args = { targetEntityId };
    let __writer = new BinaryWriter(1024);
    Target.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("target", __argsBuffer, this.setCallReducerFlags.targetFlags);
  }

  onTarget(callback: (ctx: ReducerEventContext, targetEntityId: bigint) => void) {
    this.connection.onReducer("target", callback);
  }

  removeOnTarget(callback: (ctx: ReducerEventContext, targetEntityId: bigint) => void) {
    this.connection.offReducer("target", callback);
  }

}

export class SetReducerFlags {
  actFlags: CallReducerFlags = 'FullUpdate';
  act(flags: CallReducerFlags) {
    this.actFlags = flags;
  }

  addTraitFlags: CallReducerFlags = 'FullUpdate';
  addTrait(flags: CallReducerFlags) {
    this.addTraitFlags = flags;
  }

  damageFlags: CallReducerFlags = 'FullUpdate';
  damage(flags: CallReducerFlags) {
    this.damageFlags = flags;
  }

  deleteTargetFlags: CallReducerFlags = 'FullUpdate';
  deleteTarget(flags: CallReducerFlags) {
    this.deleteTargetFlags = flags;
  }

  runSystemFlags: CallReducerFlags = 'FullUpdate';
  runSystem(flags: CallReducerFlags) {
    this.runSystemFlags = flags;
  }

  targetFlags: CallReducerFlags = 'FullUpdate';
  target(flags: CallReducerFlags) {
    this.targetFlags = flags;
  }

}

export class RemoteTables {
  constructor(private connection: DbConnectionImpl) {}

  get actionAppearances(): ActionAppearancesTableHandle {
    return new ActionAppearancesTableHandle(this.connection.clientCache.getOrCreateTable<ActionAppearance>(REMOTE_MODULE.tables.action_appearances));
  }

  get actionHotkeysComponents(): ActionHotkeysComponentsTableHandle {
    return new ActionHotkeysComponentsTableHandle(this.connection.clientCache.getOrCreateTable<ActionHotkeysComponent>(REMOTE_MODULE.tables.action_hotkeys_components));
  }

  get actionOptionsComponents(): ActionOptionsComponentsTableHandle {
    return new ActionOptionsComponentsTableHandle(this.connection.clientCache.getOrCreateTable<ActionOptionsComponent>(REMOTE_MODULE.tables.action_options_components));
  }

  get actionStateComponents(): ActionStateComponentsTableHandle {
    return new ActionStateComponentsTableHandle(this.connection.clientCache.getOrCreateTable<ActionStateComponent>(REMOTE_MODULE.tables.action_state_components));
  }

  get actionSteps(): ActionStepsTableHandle {
    return new ActionStepsTableHandle(this.connection.clientCache.getOrCreateTable<ActionStep>(REMOTE_MODULE.tables.action_steps));
  }

  get actions(): ActionsTableHandle {
    return new ActionsTableHandle(this.connection.clientCache.getOrCreateTable<Action>(REMOTE_MODULE.tables.actions));
  }

  get actionsComponents(): ActionsComponentsTableHandle {
    return new ActionsComponentsTableHandle(this.connection.clientCache.getOrCreateTable<ActionsComponent>(REMOTE_MODULE.tables.actions_components));
  }

  get allegianceComponents(): AllegianceComponentsTableHandle {
    return new AllegianceComponentsTableHandle(this.connection.clientCache.getOrCreateTable<AllegianceComponent>(REMOTE_MODULE.tables.allegiance_components));
  }

  get appearanceFeatures(): AppearanceFeaturesTableHandle {
    return new AppearanceFeaturesTableHandle(this.connection.clientCache.getOrCreateTable<AppearanceFeature>(REMOTE_MODULE.tables.appearance_features));
  }

  get appearanceFeaturesComponents(): AppearanceFeaturesComponentsTableHandle {
    return new AppearanceFeaturesComponentsTableHandle(this.connection.clientCache.getOrCreateTable<AppearanceFeaturesComponent>(REMOTE_MODULE.tables.appearance_features_components));
  }

  get attackComponents(): AttackComponentsTableHandle {
    return new AttackComponentsTableHandle(this.connection.clientCache.getOrCreateTable<AttackComponent>(REMOTE_MODULE.tables.attack_components));
  }

  get baselineComponents(): BaselineComponentsTableHandle {
    return new BaselineComponentsTableHandle(this.connection.clientCache.getOrCreateTable<BaselineComponent>(REMOTE_MODULE.tables.baseline_components));
  }

  get baselines(): BaselinesTableHandle {
    return new BaselinesTableHandle(this.connection.clientCache.getOrCreateTable<Baseline>(REMOTE_MODULE.tables.baselines));
  }

  get enAppearanceFeatures(): EnAppearanceFeaturesTableHandle {
    return new EnAppearanceFeaturesTableHandle(this.connection.clientCache.getOrCreateTable<AppearanceFeature>(REMOTE_MODULE.tables.en_appearance_features));
  }

  get entities(): EntitiesTableHandle {
    return new EntitiesTableHandle(this.connection.clientCache.getOrCreateTable<Entity>(REMOTE_MODULE.tables.entities));
  }

  get entityBlobs(): EntityBlobsTableHandle {
    return new EntityBlobsTableHandle(this.connection.clientCache.getOrCreateTable<EntityBlob>(REMOTE_MODULE.tables.entity_blobs));
  }

  get entityDeactivationTimerComponents(): EntityDeactivationTimerComponentsTableHandle {
    return new EntityDeactivationTimerComponentsTableHandle(this.connection.clientCache.getOrCreateTable<TimerComponent>(REMOTE_MODULE.tables.entity_deactivation_timer_components));
  }

  get entityProminenceComponents(): EntityProminenceComponentsTableHandle {
    return new EntityProminenceComponentsTableHandle(this.connection.clientCache.getOrCreateTable<EntityProminenceComponent>(REMOTE_MODULE.tables.entity_prominence_components));
  }

  get epComponents(): EpComponentsTableHandle {
    return new EpComponentsTableHandle(this.connection.clientCache.getOrCreateTable<EpComponent>(REMOTE_MODULE.tables.ep_components));
  }

  get hpComponents(): HpComponentsTableHandle {
    return new HpComponentsTableHandle(this.connection.clientCache.getOrCreateTable<HpComponent>(REMOTE_MODULE.tables.hp_components));
  }

  get identityInactiveEntities(): IdentityInactiveEntitiesTableHandle {
    return new IdentityInactiveEntitiesTableHandle(this.connection.clientCache.getOrCreateTable<IdentityInactiveEntity>(REMOTE_MODULE.tables.identity_inactive_entities));
  }

  get locationComponents(): LocationComponentsTableHandle {
    return new LocationComponentsTableHandle(this.connection.clientCache.getOrCreateTable<LocationComponent>(REMOTE_MODULE.tables.location_components));
  }

  get locationMapComponents(): LocationMapComponentsTableHandle {
    return new LocationMapComponentsTableHandle(this.connection.clientCache.getOrCreateTable<LocationMapComponent>(REMOTE_MODULE.tables.location_map_components));
  }

  get nameComponents(): NameComponentsTableHandle {
    return new NameComponentsTableHandle(this.connection.clientCache.getOrCreateTable<NameComponent>(REMOTE_MODULE.tables.name_components));
  }

  get namedInactiveEntities(): NamedInactiveEntitiesTableHandle {
    return new NamedInactiveEntitiesTableHandle(this.connection.clientCache.getOrCreateTable<NamedInactiveEntity>(REMOTE_MODULE.tables.named_inactive_entities));
  }

  get observableEvents(): ObservableEventsTableHandle {
    return new ObservableEventsTableHandle(this.connection.clientCache.getOrCreateTable<EntityEvent>(REMOTE_MODULE.tables.observable_events));
  }

  get pathComponents(): PathComponentsTableHandle {
    return new PathComponentsTableHandle(this.connection.clientCache.getOrCreateTable<PathComponent>(REMOTE_MODULE.tables.path_components));
  }

  get playerControllerComponents(): PlayerControllerComponentsTableHandle {
    return new PlayerControllerComponentsTableHandle(this.connection.clientCache.getOrCreateTable<PlayerControllerComponent>(REMOTE_MODULE.tables.player_controller_components));
  }

  get queuedActionStateComponents(): QueuedActionStateComponentsTableHandle {
    return new QueuedActionStateComponentsTableHandle(this.connection.clientCache.getOrCreateTable<ActionStateComponent>(REMOTE_MODULE.tables.queued_action_state_components));
  }

  get realizedMapComponents(): RealizedMapComponentsTableHandle {
    return new RealizedMapComponentsTableHandle(this.connection.clientCache.getOrCreateTable<MapComponent>(REMOTE_MODULE.tables.realized_map_components));
  }

  get rngSeedComponents(): RngSeedComponentsTableHandle {
    return new RngSeedComponentsTableHandle(this.connection.clientCache.getOrCreateTable<RngSeedComponent>(REMOTE_MODULE.tables.rng_seed_components));
  }

  get systemTimers(): SystemTimersTableHandle {
    return new SystemTimersTableHandle(this.connection.clientCache.getOrCreateTable<SystemTimer>(REMOTE_MODULE.tables.system_timers));
  }

  get targetComponents(): TargetComponentsTableHandle {
    return new TargetComponentsTableHandle(this.connection.clientCache.getOrCreateTable<TargetComponent>(REMOTE_MODULE.tables.target_components));
  }

  get totalStatBlockDirtyFlagComponents(): TotalStatBlockDirtyFlagComponentsTableHandle {
    return new TotalStatBlockDirtyFlagComponentsTableHandle(this.connection.clientCache.getOrCreateTable<FlagComponent>(REMOTE_MODULE.tables.total_stat_block_dirty_flag_components));
  }

  get traits(): TraitsTableHandle {
    return new TraitsTableHandle(this.connection.clientCache.getOrCreateTable<Trait>(REMOTE_MODULE.tables.traits));
  }

  get traitsComponents(): TraitsComponentsTableHandle {
    return new TraitsComponentsTableHandle(this.connection.clientCache.getOrCreateTable<TraitsComponent>(REMOTE_MODULE.tables.traits_components));
  }

  get traitsStatBlockCacheComponents(): TraitsStatBlockCacheComponentsTableHandle {
    return new TraitsStatBlockCacheComponentsTableHandle(this.connection.clientCache.getOrCreateTable<StatBlockCacheComponent>(REMOTE_MODULE.tables.traits_stat_block_cache_components));
  }

  get traitsStatBlockDirtyFlagComponents(): TraitsStatBlockDirtyFlagComponentsTableHandle {
    return new TraitsStatBlockDirtyFlagComponentsTableHandle(this.connection.clientCache.getOrCreateTable<FlagComponent>(REMOTE_MODULE.tables.traits_stat_block_dirty_flag_components));
  }

  get unrealizedMapComponents(): UnrealizedMapComponentsTableHandle {
    return new UnrealizedMapComponentsTableHandle(this.connection.clientCache.getOrCreateTable<MapComponent>(REMOTE_MODULE.tables.unrealized_map_components));
  }
}

export class SubscriptionBuilder extends SubscriptionBuilderImpl<RemoteTables, RemoteReducers, SetReducerFlags> { }

export class DbConnection extends DbConnectionImpl<RemoteTables, RemoteReducers, SetReducerFlags> {
  static builder = (): DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext> => {
    return new DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext>(REMOTE_MODULE, (imp: DbConnectionImpl) => imp as DbConnection);
  }
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  }
}

export type EventContext = EventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type ReducerEventContext = ReducerEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type SubscriptionEventContext = SubscriptionEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
export type ErrorContext = ErrorContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
