// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { MapLayout as __MapLayout } from "./map_layout_type";

export type MapComponent = {
  entityId: bigint,
  mapThemeId: bigint,
  mapLayout: __MapLayout,
  totalRoomCount: number,
  mainRoomCount: number,
  loopCount: number,
};

/**
 * A namespace for generated helper functions.
 */
export namespace MapComponent {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("entityId", AlgebraicType.createU64Type()),
      new ProductTypeElement("mapThemeId", AlgebraicType.createU64Type()),
      new ProductTypeElement("mapLayout", __MapLayout.getTypeScriptAlgebraicType()),
      new ProductTypeElement("totalRoomCount", AlgebraicType.createU16Type()),
      new ProductTypeElement("mainRoomCount", AlgebraicType.createU16Type()),
      new ProductTypeElement("loopCount", AlgebraicType.createU16Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: MapComponent): void {
    MapComponent.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): MapComponent {
    return MapComponent.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


