// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { NamedInactiveEntity } from "./named_inactive_entity_type";
import { ComponentSet as __ComponentSet } from "./component_set_type";

import { EventContext, Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `named_inactive_entities`.
 *
 * Obtain a handle from the [`namedInactiveEntities`] property on [`RemoteTables`],
 * like `ctx.db.namedInactiveEntities`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.namedInactiveEntities.on_insert(...)`.
 */
export class NamedInactiveEntitiesTableHandle {
  tableCache: TableCache<NamedInactiveEntity>;

  constructor(tableCache: TableCache<NamedInactiveEntity>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<NamedInactiveEntity> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `prefabName` unique index on the table `named_inactive_entities`,
   * which allows point queries on the field of the same name
   * via the [`NamedInactiveEntitiesPrefabNameUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.namedInactiveEntities.prefabName().find(...)`.
   *
   * Get a handle on the `prefabName` unique index on the table `named_inactive_entities`.
   */
  prefabName = {
    // Find the subscribed row whose `prefabName` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: string): NamedInactiveEntity | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.prefabName, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: NamedInactiveEntity) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: NamedInactiveEntity) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: NamedInactiveEntity) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: NamedInactiveEntity) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: NamedInactiveEntity, newRow: NamedInactiveEntity) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: NamedInactiveEntity, newRow: NamedInactiveEntity) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
