// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  StatsBlock,
  AppearanceBlock,
  BodyCapacityBlock,
  ReadinessBlock,
} from "./types";


export default __t.row({
  id: __t.u32().primaryKey(),
  name: __t.string(),
  get perBitStats() {
    return StatsBlock.name("per_bit_stats");
  },
  get perBitAppearance() {
    return AppearanceBlock.name("per_bit_appearance");
  },
  get perBitBodyCapacity() {
    return BodyCapacityBlock.name("per_bit_body_capacity");
  },
  get perBitReadiness() {
    return ReadinessBlock.name("per_bit_readiness");
  },
  bitCount: __t.u32().name("bit_count"),
});
