// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  StatBlock,
} from "./types";


export default __t.row({
  id: __t.u32().primaryKey(),
  name: __t.string(),
  get perBitStatBlock() {
    return StatBlock.name("per_bit_stat_block");
  },
  bitCount: __t.u32().name("bit_count"),
});
