// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  MapLayout,
} from "./types";


export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  mapThemeId: __t.u64().name("map_theme_id"),
  get mapLayout() {
    return MapLayout.name("map_layout");
  },
  extraRoomCount: __t.u8().name("extra_room_count"),
  mainRoomCount: __t.u8().name("main_room_count"),
  loopCount: __t.u8().name("loop_count"),
});
