// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  StatsBlock,
  AppearanceBlock,
  BodyCapacityBlock,
  ReadinessBlock,
} from "./types";


export default __t.row({
  id: __t.u32().primaryKey(),
  name: __t.string(),
  get stats() {
    return StatsBlock;
  },
  get appearance() {
    return AppearanceBlock;
  },
  get bodyCapacity() {
    return BodyCapacityBlock.name("body_capacity");
  },
  get readiness() {
    return ReadinessBlock;
  },
  appearanceFeatureIds: __t.array(__t.u32()).name("appearance_feature_ids"),
});
