// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { SpecialEntityBlobType as __SpecialEntityBlobType } from "./special_entity_blob_type_type";
import { EntityBlob as __EntityBlob } from "./entity_blob_type";

export type SpecialEntityBlob = {
  specialEntityBlobType: __SpecialEntityBlobType,
  blob: __EntityBlob,
};

/**
 * A namespace for generated helper functions.
 */
export namespace SpecialEntityBlob {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("specialEntityBlobType", __SpecialEntityBlobType.getTypeScriptAlgebraicType()),
      new ProductTypeElement("blob", __EntityBlob.getTypeScriptAlgebraicType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: SpecialEntityBlob): void {
    SpecialEntityBlob.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): SpecialEntityBlob {
    return SpecialEntityBlob.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


