// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { SpecialEntityBlob } from "./special_entity_blob_type";
import { SpecialEntityBlobType as __SpecialEntityBlobType } from "./special_entity_blob_type_type";
import { EntityBlob as __EntityBlob } from "./entity_blob_type";

import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `special_entity_blobs`.
 *
 * Obtain a handle from the [`specialEntityBlobs`] property on [`RemoteTables`],
 * like `ctx.db.specialEntityBlobs`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.specialEntityBlobs.on_insert(...)`.
 */
export class SpecialEntityBlobsTableHandle {
  tableCache: TableCache<SpecialEntityBlob>;

  constructor(tableCache: TableCache<SpecialEntityBlob>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<SpecialEntityBlob> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `specialEntityBlobType` unique index on the table `special_entity_blobs`,
   * which allows point queries on the field of the same name
   * via the [`SpecialEntityBlobsSpecialEntityBlobTypeUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.specialEntityBlobs.specialEntityBlobType().find(...)`.
   *
   * Get a handle on the `specialEntityBlobType` unique index on the table `special_entity_blobs`.
   */
  specialEntityBlobType = {
    // Find the subscribed row whose `specialEntityBlobType` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: SpecialEntityBlobType): SpecialEntityBlob | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.specialEntityBlobType, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: SpecialEntityBlob) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: SpecialEntityBlob) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: SpecialEntityBlob) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: SpecialEntityBlob) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: SpecialEntityBlob, newRow: SpecialEntityBlob) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: SpecialEntityBlob, newRow: SpecialEntityBlob) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
