// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Account = __t.object("Account", {
  id: __t.u64(),
  name: __t.string(),
  createdAt: __t.timestamp(),
  requiresPasswordRotation: __t.bool(),
});
export type Account = __Infer<typeof Account>;

export const AccountIdentity = __t.object("AccountIdentity", {
  identity: __t.identity(),
  accountId: __t.u64(),
  attachedAt: __t.timestamp(),
});
export type AccountIdentity = __Infer<typeof AccountIdentity>;

export const AccountPassword = __t.object("AccountPassword", {
  accountId: __t.u64(),
  salt: __t.string(),
  passwordHash: __t.string(),
  updatedAt: __t.timestamp(),
});
export type AccountPassword = __Infer<typeof AccountPassword>;

export const AccountRole = __t.object("AccountRole", {
  id: __t.u64(),
  accountId: __t.u64(),
  roleId: __t.u32(),
});
export type AccountRole = __Infer<typeof AccountRole>;

export const Action = __t.object("Action", {
  id: __t.u32(),
  name: __t.string(),
  get actionType() {
    return ActionType;
  },
});
export type Action = __Infer<typeof Action>;

export const ActionAuthor = __t.object("ActionAuthor", {
  get actionType() {
    return ActionType;
  },
  get rounds() {
    return __t.array(ActionRoundAuthor);
  },
});
export type ActionAuthor = __Infer<typeof ActionAuthor>;

// The tagged union or sum type for the algebraic type `ActionEffect`.
export const ActionEffect = __t.enum("ActionEffect", {
  get Buff() {
    return Buff;
  },
  Attack: __t.i32(),
  Heal: __t.i32(),
  Move: __t.unit(),
  Take: __t.unit(),
  Drop: __t.unit(),
  Equip: __t.unit(),
  Unequip: __t.unit(),
});
export type ActionEffect = __Infer<typeof ActionEffect>;

export const ActionRound = __t.object("ActionRound", {
  id: __t.u64(),
  actionId: __t.u32(),
  sequenceIndex: __t.i32(),
  get effects() {
    return __t.array(ActionEffect);
  },
  interruptible: __t.bool(),
});
export type ActionRound = __Infer<typeof ActionRound>;

export const ActionRoundAuthor = __t.object("ActionRoundAuthor", {
  get effects() {
    return __t.array(ActionEffect);
  },
  interruptible: __t.bool(),
});
export type ActionRoundAuthor = __Infer<typeof ActionRoundAuthor>;

export const ActionStateComponent = __t.object("ActionStateComponent", {
  entityId: __t.u64(),
  targetEntityId: __t.u64(),
  actionId: __t.u32(),
  sequenceIndex: __t.i32(),
});
export type ActionStateComponent = __Infer<typeof ActionStateComponent>;

export const ActionStateComponentBlob = __t.object("ActionStateComponentBlob", {
  get targetEntityId() {
    return EntityIdSelector;
  },
  actionId: __t.u32(),
  sequenceIndex: __t.i32(),
});
export type ActionStateComponentBlob = __Infer<typeof ActionStateComponentBlob>;

// The tagged union or sum type for the algebraic type `ActionType`.
export const ActionType = __t.enum("ActionType", {
  Buff: __t.unit(),
  Attack: __t.unit(),
  Move: __t.unit(),
  Inventory: __t.unit(),
  Equip: __t.unit(),
});
export type ActionType = __Infer<typeof ActionType>;

export const ActionsComponent = __t.object("ActionsComponent", {
  entityId: __t.u64(),
  actionIds: __t.array(__t.u32()),
});
export type ActionsComponent = __Infer<typeof ActionsComponent>;

export const ActionsComponentBlob = __t.object("ActionsComponentBlob", {
  actionIds: __t.array(__t.u32()),
});
export type ActionsComponentBlob = __Infer<typeof ActionsComponentBlob>;

export const AllegianceComponent = __t.object("AllegianceComponent", {
  entityId: __t.u64(),
  allegianceEntityId: __t.u64(),
});
export type AllegianceComponent = __Infer<typeof AllegianceComponent>;

export const AllegianceComponentBlob = __t.object("AllegianceComponentBlob", {
  get allegianceEntityId() {
    return EntityIdSelector;
  },
});
export type AllegianceComponentBlob = __Infer<typeof AllegianceComponentBlob>;

export const AppearanceFeature = __t.object("AppearanceFeature", {
  index: __t.u32(),
  name: __t.string(),
  text: __t.string(),
  get appearanceFeatureType() {
    return AppearanceFeatureType;
  },
  priority: __t.i32(),
});
export type AppearanceFeature = __Infer<typeof AppearanceFeature>;

export const AppearanceFeatureAuthor = __t.object("AppearanceFeatureAuthor", {
  text: __t.string(),
  get appearanceFeatureType() {
    return AppearanceFeatureType;
  },
  priority: __t.i32(),
});
export type AppearanceFeatureAuthor = __Infer<typeof AppearanceFeatureAuthor>;

// The tagged union or sum type for the algebraic type `AppearanceFeatureType`.
export const AppearanceFeatureType = __t.enum("AppearanceFeatureType", {
  Noun: __t.unit(),
  Adjective: __t.unit(),
});
export type AppearanceFeatureType = __Infer<typeof AppearanceFeatureType>;

export const AppearanceFeaturesComponent = __t.object("AppearanceFeaturesComponent", {
  entityId: __t.u64(),
  appearanceFeatureIndexes: __t.array(__t.u32()),
});
export type AppearanceFeaturesComponent = __Infer<typeof AppearanceFeaturesComponent>;

export const AppearanceFeaturesComponentBlob = __t.object("AppearanceFeaturesComponentBlob", {
  appearanceFeatureIndexes: __t.array(__t.u32()),
});
export type AppearanceFeaturesComponentBlob = __Infer<typeof AppearanceFeaturesComponentBlob>;

export const AssetPack = __t.object("AssetPack", {
  get actions() {
    return __t.array(NamedActionAuthor);
  },
  get appearanceFeatures() {
    return __t.array(NamedAppearanceFeatureAuthor);
  },
  get baselines() {
    return __t.array(NamedStatBlockAuthor);
  },
  get traits() {
    return __t.array(NamedStatBlockAuthor);
  },
  get encounterBlobs() {
    return __t.array(NamedEntityBlobAuthor);
  },
  get encounters() {
    return __t.array(NamedEncounterAuthor);
  },
  get locationMapThemes() {
    return __t.array(NamedLocationMapThemeAuthor);
  },
  get locationMaps() {
    return __t.array(NamedLocationMapAuthor);
  },
  get namedInstantiateEntityBlobs() {
    return __t.array(NamedEntityBlobAuthor);
  },
  get instantiateEntityBlobs() {
    return __t.array(EntityBlobAuthor);
  },
  get newPlayerBlob() {
    return EntityBlobAuthor;
  },
});
export type AssetPack = __Infer<typeof AssetPack>;

export const AttackComponent = __t.object("AttackComponent", {
  entityId: __t.u64(),
  attack: __t.i32(),
});
export type AttackComponent = __Infer<typeof AttackComponent>;

export const AttackComponentBlob = __t.object("AttackComponentBlob", {
  attack: __t.i32(),
});
export type AttackComponentBlob = __Infer<typeof AttackComponentBlob>;

export const Baseline = __t.object("Baseline", {
  id: __t.u32(),
  name: __t.string(),
  get statBlock() {
    return StatBlock;
  },
});
export type Baseline = __Infer<typeof Baseline>;

export const BaselineComponent = __t.object("BaselineComponent", {
  entityId: __t.u64(),
  baselineId: __t.u32(),
});
export type BaselineComponent = __Infer<typeof BaselineComponent>;

export const BaselineComponentBlob = __t.object("BaselineComponentBlob", {
  baselineId: __t.u32(),
});
export type BaselineComponentBlob = __Infer<typeof BaselineComponentBlob>;

// The tagged union or sum type for the algebraic type `Buff`.
export const Buff = __t.enum("Buff", {
  Guard: __t.i32(),
});
export type Buff = __Infer<typeof Buff>;

export const Encounter = __t.object("Encounter", {
  id: __t.u32(),
  name: __t.string(),
  categoricBlobId: __t.u32(),
  blobIds: __t.array(__t.u32()),
});
export type Encounter = __Infer<typeof Encounter>;

export const EncounterAuthor = __t.object("EncounterAuthor", {
  categoricBlobName: __t.string(),
  blobNames: __t.array(__t.string()),
});
export type EncounterAuthor = __Infer<typeof EncounterAuthor>;

export const EncounterBlob = __t.object("EncounterBlob", {
  id: __t.u32(),
  name: __t.string(),
  get blob() {
    return EntityBlob;
  },
});
export type EncounterBlob = __Infer<typeof EncounterBlob>;

export const EncounterIdSample = __t.object("EncounterIdSample", {
  weight: __t.u8(),
  id: __t.u32(),
});
export type EncounterIdSample = __Infer<typeof EncounterIdSample>;

export const EncounterIdsSampler = __t.object("EncounterIdsSampler", {
  get selections() {
    return __t.array(EncounterIdSample);
  },
});
export type EncounterIdsSampler = __Infer<typeof EncounterIdsSampler>;

export const EnemyControllerComponent = __t.object("EnemyControllerComponent", {
  entityId: __t.u64(),
});
export type EnemyControllerComponent = __Infer<typeof EnemyControllerComponent>;

export const EnemyControllerComponentBlob = __t.object("EnemyControllerComponentBlob", {});
export type EnemyControllerComponentBlob = __Infer<typeof EnemyControllerComponentBlob>;

export const Entity = __t.object("Entity", {
  id: __t.u64(),
});
export type Entity = __Infer<typeof Entity>;

export const EntityBlob = __t.object("EntityBlob", {
  get name() {
    return __t.option(NameComponentBlob);
  },
  get location() {
    return __t.option(LocationComponentBlob);
  },
  get path() {
    return __t.option(PathComponentBlob);
  },
  get allegiance() {
    return __t.option(AllegianceComponentBlob);
  },
  get baseline() {
    return __t.option(BaselineComponentBlob);
  },
  get traits() {
    return __t.option(TraitsComponentBlob);
  },
  get equipmentStatBlockCache() {
    return __t.option(StatBlockCacheComponentBlob);
  },
  get statusStatBlockCache() {
    return __t.option(StatBlockCacheComponentBlob);
  },
  get traitsStatBlockCache() {
    return __t.option(StatBlockCacheComponentBlob);
  },
  get traitsStatBlockDirtyFlag() {
    return __t.option(FlagComponentBlob);
  },
  get totalStatBlockDirtyFlag() {
    return __t.option(FlagComponentBlob);
  },
  get attack() {
    return __t.option(AttackComponentBlob);
  },
  get hp() {
    return __t.option(HpComponentBlob);
  },
  get ep() {
    return __t.option(EpComponentBlob);
  },
  get playerController() {
    return __t.option(PlayerControllerComponentBlob);
  },
  get enemyController() {
    return __t.option(EnemyControllerComponentBlob);
  },
  get actionState() {
    return __t.option(ActionStateComponentBlob);
  },
  get queuedActionState() {
    return __t.option(ActionStateComponentBlob);
  },
  get actions() {
    return __t.option(ActionsComponentBlob);
  },
  get pinnedActions() {
    return __t.option(PinnedActionsComponentBlob);
  },
  get entityDeletionTimer() {
    return __t.option(TimerComponentBlob);
  },
  get playerDeactivationTimer() {
    return __t.option(TimerComponentBlob);
  },
  get locationMap() {
    return __t.option(LocationMapComponentBlob);
  },
  get appearanceFeatures() {
    return __t.option(AppearanceFeaturesComponentBlob);
  },
});
export type EntityBlob = __Infer<typeof EntityBlob>;

export const EntityBlobAuthor = __t.object("EntityBlobAuthor", {
  get name() {
    return __t.option(NameComponentBlob);
  },
  get location() {
    return __t.option(LocationComponentBlob);
  },
  get path() {
    return __t.option(PathComponentBlob);
  },
  get allegiance() {
    return __t.option(AllegianceComponentBlob);
  },
  baselineName: __t.option(__t.string()),
  traitNames: __t.option(__t.array(__t.string())),
  actionNames: __t.option(__t.array(__t.string())),
  pinnedActionNames: __t.option(__t.array(__t.string())),
  appearanceFeatureNames: __t.option(__t.array(__t.string())),
  get hp() {
    return __t.option(HpComponentBlob);
  },
  get ep() {
    return __t.option(EpComponentBlob);
  },
  get attack() {
    return __t.option(AttackComponentBlob);
  },
  get playerController() {
    return __t.option(PlayerControllerComponentBlob);
  },
  get enemyController() {
    return __t.option(EnemyControllerComponentBlob);
  },
});
export type EntityBlobAuthor = __Infer<typeof EntityBlobAuthor>;

export const EntityBlobSample = __t.object("EntityBlobSample", {
  weight: __t.u8(),
  get blob() {
    return EntityBlob;
  },
});
export type EntityBlobSample = __Infer<typeof EntityBlobSample>;

export const EntityBlobSampleAuthor = __t.object("EntityBlobSampleAuthor", {
  weight: __t.u8(),
  get blob() {
    return EntityBlobAuthor;
  },
});
export type EntityBlobSampleAuthor = __Infer<typeof EntityBlobSampleAuthor>;

export const EntityBlobsSampler = __t.object("EntityBlobsSampler", {
  get selections() {
    return __t.array(EntityBlobSample);
  },
});
export type EntityBlobsSampler = __Infer<typeof EntityBlobsSampler>;

export const EntityBlobsSamplerAuthor = __t.object("EntityBlobsSamplerAuthor", {
  get selections() {
    return __t.array(EntityBlobSampleAuthor);
  },
});
export type EntityBlobsSamplerAuthor = __Infer<typeof EntityBlobsSamplerAuthor>;

export const EntityEvent = __t.object("EntityEvent", {
  id: __t.u64(),
  time: __t.timestamp(),
  ownerEntityId: __t.u64(),
  get eventType() {
    return EventType;
  },
  targetEntityId: __t.u64(),
});
export type EntityEvent = __Infer<typeof EntityEvent>;

// The tagged union or sum type for the algebraic type `EntityIdSelector`.
export const EntityIdSelector = __t.enum("EntityIdSelector", {
  Literal: __t.u64(),
  Local: __t.u32(),
  Named: __t.string(),
});
export type EntityIdSelector = __Infer<typeof EntityIdSelector>;

export const EpComponent = __t.object("EpComponent", {
  entityId: __t.u64(),
  ep: __t.i32(),
  mep: __t.i32(),
});
export type EpComponent = __Infer<typeof EpComponent>;

export const EpComponentBlob = __t.object("EpComponentBlob", {
  ep: __t.i32(),
  mep: __t.i32(),
});
export type EpComponentBlob = __Infer<typeof EpComponentBlob>;

// The tagged union or sum type for the algebraic type `EventType`.
export const EventType = __t.enum("EventType", {
  StartAction: __t.u32(),
  get ActionEffect() {
    return ActionEffect;
  },
});
export type EventType = __Infer<typeof EventType>;

export const FlagComponent = __t.object("FlagComponent", {
  entityId: __t.u64(),
});
export type FlagComponent = __Infer<typeof FlagComponent>;

export const FlagComponentBlob = __t.object("FlagComponentBlob", {});
export type FlagComponentBlob = __Infer<typeof FlagComponentBlob>;

export const HpComponent = __t.object("HpComponent", {
  entityId: __t.u64(),
  hp: __t.i32(),
  mhp: __t.i32(),
  defense: __t.i32(),
  accumulatedDamage: __t.i32(),
  accumulatedHealing: __t.i32(),
});
export type HpComponent = __Infer<typeof HpComponent>;

export const HpComponentBlob = __t.object("HpComponentBlob", {
  hp: __t.i32(),
  mhp: __t.i32(),
  defense: __t.i32(),
  accumulatedDamage: __t.i32(),
  accumulatedHealing: __t.i32(),
});
export type HpComponentBlob = __Infer<typeof HpComponentBlob>;

// The tagged union or sum type for the algebraic type `Layout`.
export const Layout = __t.enum("Layout", {
  Path: __t.unit(),
  Hub: __t.unit(),
});
export type Layout = __Infer<typeof Layout>;

export const LocationComponent = __t.object("LocationComponent", {
  entityId: __t.u64(),
  locationEntityId: __t.u64(),
});
export type LocationComponent = __Infer<typeof LocationComponent>;

export const LocationComponentBlob = __t.object("LocationComponentBlob", {
  get locationEntityId() {
    return EntityIdSelector;
  },
});
export type LocationComponentBlob = __Infer<typeof LocationComponentBlob>;

export const LocationMap = __t.object("LocationMap", {
  id: __t.u32(),
  name: __t.string(),
  themeId: __t.u32(),
  get layout() {
    return Layout;
  },
  rngSeed: __t.option(__t.u64()),
  extraRoomCount: __t.u8(),
  mainRoomCount: __t.u8(),
  loopCount: __t.u8(),
  get encounterIdsSampler() {
    return EncounterIdsSampler;
  },
  minEncounterCount: __t.u8(),
  maxEncounterCount: __t.u8(),
});
export type LocationMap = __Infer<typeof LocationMap>;

export const LocationMapAuthor = __t.object("LocationMapAuthor", {
  themeName: __t.string(),
  get layout() {
    return Layout;
  },
  rngSeed: __t.option(__t.u64()),
  extraRoomCount: __t.u8(),
  mainRoomCount: __t.u8(),
  loopCount: __t.u8(),
  get encounterNamesSampler() {
    return __t.array(WeightedNameAuthor);
  },
  minEncounterCount: __t.u8(),
  maxEncounterCount: __t.u8(),
  connectionNames: __t.array(__t.string()),
});
export type LocationMapAuthor = __Infer<typeof LocationMapAuthor>;

export const LocationMapComponent = __t.object("LocationMapComponent", {
  entityId: __t.u64(),
  locationMapEntityId: __t.u64(),
});
export type LocationMapComponent = __Infer<typeof LocationMapComponent>;

export const LocationMapComponentBlob = __t.object("LocationMapComponentBlob", {
  get locationMapEntityId() {
    return EntityIdSelector;
  },
});
export type LocationMapComponentBlob = __Infer<typeof LocationMapComponentBlob>;

export const LocationMapConnection = __t.object("LocationMapConnection", {
  id: __t.u32(),
  exitLocationMapId: __t.u32(),
  destinationLocationMapId: __t.u32(),
});
export type LocationMapConnection = __Infer<typeof LocationMapConnection>;

export const LocationMapTheme = __t.object("LocationMapTheme", {
  id: __t.u32(),
  name: __t.string(),
  get decorationsSelector() {
    return EntityBlobsSampler;
  },
  minDecorationCount: __t.u8(),
  maxDecorationCount: __t.u8(),
  get pathsSelector() {
    return EntityBlobsSampler;
  },
  get roomsSelector() {
    return EntityBlobsSampler;
  },
});
export type LocationMapTheme = __Infer<typeof LocationMapTheme>;

export const LocationMapThemeAuthor = __t.object("LocationMapThemeAuthor", {
  get decorationsSelector() {
    return EntityBlobsSamplerAuthor;
  },
  minDecorationCount: __t.u8(),
  maxDecorationCount: __t.u8(),
  get pathsSelector() {
    return EntityBlobsSamplerAuthor;
  },
  get roomsSelector() {
    return EntityBlobsSamplerAuthor;
  },
});
export type LocationMapThemeAuthor = __Infer<typeof LocationMapThemeAuthor>;

export const LoginFinalizeTimer = __t.object("LoginFinalizeTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  loginRequestId: __t.u64(),
});
export type LoginFinalizeTimer = __Infer<typeof LoginFinalizeTimer>;

export const LoginRequest = __t.object("LoginRequest", {
  id: __t.u64(),
  accountId: __t.u64(),
  identity: __t.identity(),
  requestedAt: __t.timestamp(),
  get status() {
    return LoginRequestStatus;
  },
  quorumReachedAt: __t.option(__t.timestamp()),
  resolvedAt: __t.option(__t.timestamp()),
});
export type LoginRequest = __Infer<typeof LoginRequest>;

export const LoginRequestCode = __t.object("LoginRequestCode", {
  loginRequestId: __t.u64(),
  verificationCode: __t.string(),
});
export type LoginRequestCode = __Infer<typeof LoginRequestCode>;

// The tagged union or sum type for the algebraic type `LoginRequestStatus`.
export const LoginRequestStatus = __t.enum("LoginRequestStatus", {
  Pending: __t.unit(),
  Accepted: __t.unit(),
  Refused: __t.unit(),
});
export type LoginRequestStatus = __Infer<typeof LoginRequestStatus>;

export const LoginRequestVoter = __t.object("LoginRequestVoter", {
  id: __t.u64(),
  loginRequestId: __t.u64(),
  identity: __t.identity(),
});
export type LoginRequestVoter = __Infer<typeof LoginRequestVoter>;

export const LoginResponse = __t.object("LoginResponse", {
  id: __t.u64(),
  loginRequestId: __t.u64(),
  identity: __t.identity(),
  accepted: __t.bool(),
  respondedAt: __t.timestamp(),
});
export type LoginResponse = __Infer<typeof LoginResponse>;

export const NameComponent = __t.object("NameComponent", {
  entityId: __t.u64(),
  name: __t.string(),
});
export type NameComponent = __Infer<typeof NameComponent>;

export const NameComponentBlob = __t.object("NameComponentBlob", {
  name: __t.string(),
});
export type NameComponentBlob = __Infer<typeof NameComponentBlob>;

export const NamedActionAuthor = __t.object("NamedActionAuthor", {
  name: __t.string(),
  get value() {
    return ActionAuthor;
  },
});
export type NamedActionAuthor = __Infer<typeof NamedActionAuthor>;

export const NamedAppearanceFeatureAuthor = __t.object("NamedAppearanceFeatureAuthor", {
  name: __t.string(),
  get value() {
    return AppearanceFeatureAuthor;
  },
});
export type NamedAppearanceFeatureAuthor = __Infer<typeof NamedAppearanceFeatureAuthor>;

export const NamedEncounterAuthor = __t.object("NamedEncounterAuthor", {
  name: __t.string(),
  get value() {
    return EncounterAuthor;
  },
});
export type NamedEncounterAuthor = __Infer<typeof NamedEncounterAuthor>;

export const NamedEntity = __t.object("NamedEntity", {
  name: __t.string(),
  entityId: __t.u64(),
});
export type NamedEntity = __Infer<typeof NamedEntity>;

export const NamedEntityBlobAuthor = __t.object("NamedEntityBlobAuthor", {
  name: __t.string(),
  get value() {
    return EntityBlobAuthor;
  },
});
export type NamedEntityBlobAuthor = __Infer<typeof NamedEntityBlobAuthor>;

export const NamedLocationMapAuthor = __t.object("NamedLocationMapAuthor", {
  name: __t.string(),
  get value() {
    return LocationMapAuthor;
  },
});
export type NamedLocationMapAuthor = __Infer<typeof NamedLocationMapAuthor>;

export const NamedLocationMapThemeAuthor = __t.object("NamedLocationMapThemeAuthor", {
  name: __t.string(),
  get value() {
    return LocationMapThemeAuthor;
  },
});
export type NamedLocationMapThemeAuthor = __Infer<typeof NamedLocationMapThemeAuthor>;

export const NamedStatBlockAuthor = __t.object("NamedStatBlockAuthor", {
  name: __t.string(),
  get value() {
    return StatBlockAuthor;
  },
});
export type NamedStatBlockAuthor = __Infer<typeof NamedStatBlockAuthor>;

export const PathComponent = __t.object("PathComponent", {
  entityId: __t.u64(),
  destinationEntityId: __t.u64(),
});
export type PathComponent = __Infer<typeof PathComponent>;

export const PathComponentBlob = __t.object("PathComponentBlob", {
  get destinationEntityId() {
    return EntityIdSelector;
  },
});
export type PathComponentBlob = __Infer<typeof PathComponentBlob>;

export const PinnedActionsComponent = __t.object("PinnedActionsComponent", {
  entityId: __t.u64(),
  actionIds: __t.array(__t.u32()),
});
export type PinnedActionsComponent = __Infer<typeof PinnedActionsComponent>;

export const PinnedActionsComponentBlob = __t.object("PinnedActionsComponentBlob", {
  actionIds: __t.array(__t.u32()),
});
export type PinnedActionsComponentBlob = __Infer<typeof PinnedActionsComponentBlob>;

export const PlayerControllerComponent = __t.object("PlayerControllerComponent", {
  entityId: __t.u64(),
  accountId: __t.u64(),
});
export type PlayerControllerComponent = __Infer<typeof PlayerControllerComponent>;

export const PlayerControllerComponentBlob = __t.object("PlayerControllerComponentBlob", {
  accountId: __t.u64(),
});
export type PlayerControllerComponentBlob = __Infer<typeof PlayerControllerComponentBlob>;

export const Role = __t.object("Role", {
  id: __t.u32(),
  name: __t.string(),
});
export type Role = __Infer<typeof Role>;

export const SpecialEntityBlob = __t.object("SpecialEntityBlob", {
  get key() {
    return SpecialEntityBlobKey;
  },
  get blob() {
    return EntityBlob;
  },
});
export type SpecialEntityBlob = __Infer<typeof SpecialEntityBlob>;

// The tagged union or sum type for the algebraic type `SpecialEntityBlobKey`.
export const SpecialEntityBlobKey = __t.enum("SpecialEntityBlobKey", {
  NewPlayer: __t.unit(),
});
export type SpecialEntityBlobKey = __Infer<typeof SpecialEntityBlobKey>;

export const StatBlock = __t.object("StatBlock", {
  attack: __t.i32(),
  mhp: __t.i32(),
  defense: __t.i32(),
  mep: __t.i32(),
  actionIds: __t.array(__t.u32()),
  appearanceFeatureIds: __t.array(__t.u32()),
});
export type StatBlock = __Infer<typeof StatBlock>;

export const StatBlockAuthor = __t.object("StatBlockAuthor", {
  attack: __t.i32(),
  mhp: __t.i32(),
  defense: __t.i32(),
  mep: __t.i32(),
  actionNames: __t.array(__t.string()),
  appearanceFeatureNames: __t.array(__t.string()),
});
export type StatBlockAuthor = __Infer<typeof StatBlockAuthor>;

export const StatBlockCacheComponent = __t.object("StatBlockCacheComponent", {
  entityId: __t.u64(),
  get statBlock() {
    return StatBlock;
  },
});
export type StatBlockCacheComponent = __Infer<typeof StatBlockCacheComponent>;

export const StatBlockCacheComponentBlob = __t.object("StatBlockCacheComponentBlob", {
  get statBlock() {
    return StatBlock;
  },
});
export type StatBlockCacheComponentBlob = __Infer<typeof StatBlockCacheComponentBlob>;

export const SystemTimer = __t.object("SystemTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type SystemTimer = __Infer<typeof SystemTimer>;

export const TimerComponent = __t.object("TimerComponent", {
  entityId: __t.u64(),
  timestamp: __t.timestamp(),
});
export type TimerComponent = __Infer<typeof TimerComponent>;

export const TimerComponentBlob = __t.object("TimerComponentBlob", {
  timestamp: __t.timestamp(),
});
export type TimerComponentBlob = __Infer<typeof TimerComponentBlob>;

export const Trait = __t.object("Trait", {
  id: __t.u32(),
  name: __t.string(),
  get statBlock() {
    return StatBlock;
  },
});
export type Trait = __Infer<typeof Trait>;

export const TraitsComponent = __t.object("TraitsComponent", {
  entityId: __t.u64(),
  traitIds: __t.array(__t.u32()),
});
export type TraitsComponent = __Infer<typeof TraitsComponent>;

export const TraitsComponentBlob = __t.object("TraitsComponentBlob", {
  traitIds: __t.array(__t.u32()),
});
export type TraitsComponentBlob = __Infer<typeof TraitsComponentBlob>;

export const WeightedNameAuthor = __t.object("WeightedNameAuthor", {
  weight: __t.u8(),
  name: __t.string(),
});
export type WeightedNameAuthor = __Infer<typeof WeightedNameAuthor>;

