// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Account = __t.object("Account", {
  id: __t.u64(),
  name: __t.string(),
  createdAt: __t.timestamp(),
  requiresPasswordRotation: __t.bool(),
});
export type Account = __Infer<typeof Account>;

export const AccountIdentity = __t.object("AccountIdentity", {
  identity: __t.identity(),
  accountId: __t.u64(),
  attachedAt: __t.timestamp(),
});
export type AccountIdentity = __Infer<typeof AccountIdentity>;

export const AccountPassword = __t.object("AccountPassword", {
  accountId: __t.u64(),
  salt: __t.string(),
  passwordHash: __t.string(),
  updatedAt: __t.timestamp(),
});
export type AccountPassword = __Infer<typeof AccountPassword>;

export const AccountRole = __t.object("AccountRole", {
  id: __t.u64(),
  accountId: __t.u64(),
  roleId: __t.u32(),
});
export type AccountRole = __Infer<typeof AccountRole>;

export const Action = __t.object("Action", {
  id: __t.u32(),
  name: __t.string(),
  get actionType() {
    return ActionType;
  },
  get requirements() {
    return StatRequirements;
  },
});
export type Action = __Infer<typeof Action>;

export const ActionAsset = __t.object("ActionAsset", {
  get actionType() {
    return ActionType;
  },
  get requirements() {
    return StatRequirements;
  },
  get rounds() {
    return __t.array(ActionRoundAsset);
  },
});
export type ActionAsset = __Infer<typeof ActionAsset>;

// The tagged union or sum type for the algebraic type `ActionEffect`.
export const ActionEffect = __t.enum("ActionEffect", {
  get Buff() {
    return Buff;
  },
  Attack: __t.i16(),
  Heal: __t.i16(),
  Move: __t.unit(),
  Take: __t.unit(),
  Drop: __t.unit(),
  Equip: __t.unit(),
  Unequip: __t.unit(),
  Eat: __t.unit(),
  Intimidate: __t.i16(),
  Rally: __t.unit(),
  Dive: __t.i16(),
  Attune: __t.unit(),
  SetStance: __t.u32(),
  Open: __t.unit(),
  Dump: __t.unit(),
  Rearm: __t.unit(),
});
export type ActionEffect = __Infer<typeof ActionEffect>;

// The tagged union or sum type for the algebraic type `ActionEffectAsset`.
export const ActionEffectAsset = __t.enum("ActionEffectAsset", {
  get Buff() {
    return Buff;
  },
  Attack: __t.i16(),
  Heal: __t.i16(),
  Move: __t.unit(),
  Take: __t.unit(),
  Drop: __t.unit(),
  Equip: __t.unit(),
  Unequip: __t.unit(),
  Eat: __t.unit(),
  Intimidate: __t.i16(),
  Rally: __t.unit(),
  Dive: __t.i16(),
  Attune: __t.unit(),
  SetStance: __t.string(),
  Open: __t.unit(),
  Dump: __t.unit(),
  Rearm: __t.unit(),
});
export type ActionEffectAsset = __Infer<typeof ActionEffectAsset>;

export const ActionQueueComponent = __t.object("ActionQueueComponent", {
  entityId: __t.u64(),
  get entries() {
    return __t.array(QueuedAction);
  },
});
export type ActionQueueComponent = __Infer<typeof ActionQueueComponent>;

export const ActionQueueComponentBlob = __t.object("ActionQueueComponentBlob", {
  get entries() {
    return __t.array(QueuedAction);
  },
});
export type ActionQueueComponentBlob = __Infer<typeof ActionQueueComponentBlob>;

export const ActionRound = __t.object("ActionRound", {
  id: __t.u64(),
  actionId: __t.u32(),
  sequenceIndex: __t.i32(),
  get effects() {
    return __t.array(ActionEffect);
  },
  interruptible: __t.bool(),
});
export type ActionRound = __Infer<typeof ActionRound>;

export const ActionRoundAsset = __t.object("ActionRoundAsset", {
  get effects() {
    return __t.array(ActionEffectAsset);
  },
  interruptible: __t.bool(),
});
export type ActionRoundAsset = __Infer<typeof ActionRoundAsset>;

export const ActionStateComponent = __t.object("ActionStateComponent", {
  entityId: __t.u64(),
  targetEntityId: __t.u64(),
  actionId: __t.u32(),
  sequenceIndex: __t.i32(),
});
export type ActionStateComponent = __Infer<typeof ActionStateComponent>;

export const ActionStateComponentBlob = __t.object("ActionStateComponentBlob", {
  get targetEntityId() {
    return EntityIdSelector;
  },
  actionId: __t.u32(),
  sequenceIndex: __t.i32(),
});
export type ActionStateComponentBlob = __Infer<typeof ActionStateComponentBlob>;

// The tagged union or sum type for the algebraic type `ActionType`.
export const ActionType = __t.enum("ActionType", {
  Buff: __t.unit(),
  Attack: __t.unit(),
  Move: __t.unit(),
  Inventory: __t.unit(),
  Equip: __t.unit(),
  Eat: __t.unit(),
  Dive: __t.unit(),
  Attune: __t.unit(),
  Posture: __t.unit(),
  Interact: __t.unit(),
  Rearm: __t.unit(),
});
export type ActionType = __Infer<typeof ActionType>;

export const ActionsComponent = __t.object("ActionsComponent", {
  entityId: __t.u64(),
  actionIds: __t.array(__t.u32()),
});
export type ActionsComponent = __Infer<typeof ActionsComponent>;

export const ActionsComponentBlob = __t.object("ActionsComponentBlob", {
  actionIds: __t.array(__t.u32()),
});
export type ActionsComponentBlob = __Infer<typeof ActionsComponentBlob>;

export const ActiveStanceComponent = __t.object("ActiveStanceComponent", {
  entityId: __t.u64(),
  stanceId: __t.u32(),
});
export type ActiveStanceComponent = __Infer<typeof ActiveStanceComponent>;

export const ActiveStanceComponentBlob = __t.object("ActiveStanceComponentBlob", {
  stanceId: __t.u32(),
});
export type ActiveStanceComponentBlob = __Infer<typeof ActiveStanceComponentBlob>;

export const AllegianceComponent = __t.object("AllegianceComponent", {
  entityId: __t.u64(),
  allegianceEntityId: __t.u64(),
});
export type AllegianceComponent = __Infer<typeof AllegianceComponent>;

export const AllegianceComponentBlob = __t.object("AllegianceComponentBlob", {
  get allegianceEntityId() {
    return EntityIdSelector;
  },
});
export type AllegianceComponentBlob = __Infer<typeof AllegianceComponentBlob>;

export const AppearanceFeature = __t.object("AppearanceFeature", {
  index: __t.u32(),
  name: __t.string(),
  text: __t.string(),
  get appearanceFeatureType() {
    return AppearanceFeatureType;
  },
  priority: __t.i32(),
  exclusionGroup: __t.option(__t.string()),
});
export type AppearanceFeature = __Infer<typeof AppearanceFeature>;

export const AppearanceFeatureAsset = __t.object("AppearanceFeatureAsset", {
  text: __t.string(),
  get appearanceFeatureType() {
    return AppearanceFeatureType;
  },
  priority: __t.i32(),
  exclusionGroup: __t.option(__t.string()),
});
export type AppearanceFeatureAsset = __Infer<typeof AppearanceFeatureAsset>;

// The tagged union or sum type for the algebraic type `AppearanceFeatureType`.
export const AppearanceFeatureType = __t.enum("AppearanceFeatureType", {
  Noun: __t.unit(),
  Adjective: __t.unit(),
});
export type AppearanceFeatureType = __Infer<typeof AppearanceFeatureType>;

export const AppearanceFeaturesComponent = __t.object("AppearanceFeaturesComponent", {
  entityId: __t.u64(),
  appearanceFeatureIndexes: __t.array(__t.u32()),
});
export type AppearanceFeaturesComponent = __Infer<typeof AppearanceFeaturesComponent>;

export const AppearanceFeaturesComponentBlob = __t.object("AppearanceFeaturesComponentBlob", {
  appearanceFeatureIndexes: __t.array(__t.u32()),
});
export type AppearanceFeaturesComponentBlob = __Infer<typeof AppearanceFeaturesComponentBlob>;

export const Armament = __t.object("Armament", {
  id: __t.u32(),
  name: __t.string(),
  get statBlock() {
    return StatBlock;
  },
});
export type Armament = __Infer<typeof Armament>;

export const Armor = __t.object("Armor", {
  id: __t.u32(),
  name: __t.string(),
  get statBlock() {
    return StatBlock;
  },
});
export type Armor = __Infer<typeof Armor>;

export const ArmorComponent = __t.object("ArmorComponent", {
  entityId: __t.u64(),
  armorId: __t.u32(),
});
export type ArmorComponent = __Infer<typeof ArmorComponent>;

export const ArmorComponentBlob = __t.object("ArmorComponentBlob", {
  armorId: __t.u32(),
});
export type ArmorComponentBlob = __Infer<typeof ArmorComponentBlob>;

export const AssetPack = __t.object("AssetPack", {
  get actions() {
    return __t.array(NamedActionAsset);
  },
  get appearanceFeatures() {
    return __t.array(NamedAppearanceFeatureAsset);
  },
  get baselines() {
    return __t.array(NamedStatBlockAsset);
  },
  get traits() {
    return __t.array(NamedStatBlockAsset);
  },
  get traitPalettes() {
    return __t.array(NamedTraitPaletteAsset);
  },
  get armaments() {
    return __t.array(NamedStatBlockAsset);
  },
  get armors() {
    return __t.array(NamedStatBlockAsset);
  },
  get relics() {
    return __t.array(NamedStatBlockAsset);
  },
  get stances() {
    return __t.array(NamedStanceAsset);
  },
  get quests() {
    return __t.array(NamedQuestAsset);
  },
  coweringStanceName: __t.option(__t.string()),
  proneStanceName: __t.option(__t.string()),
  takeActionName: __t.option(__t.string()),
  dropActionName: __t.option(__t.string()),
  equipActionName: __t.option(__t.string()),
  unequipActionName: __t.option(__t.string()),
  eatActionName: __t.option(__t.string()),
  rearmActionName: __t.option(__t.string()),
  moveActionName: __t.option(__t.string()),
  get encounterBlobs() {
    return __t.array(NamedEntityBlobAsset);
  },
  get encounters() {
    return __t.array(NamedEncounterAsset);
  },
  get locationMapThemes() {
    return __t.array(NamedLocationMapThemeAsset);
  },
  get locationMaps() {
    return __t.array(NamedLocationMapAsset);
  },
  get connections() {
    return __t.array(LocationMapConnectionAsset);
  },
  get namedInstantiateEntityBlobs() {
    return __t.array(NamedEntityBlobAsset);
  },
  get instantiateEntityBlobs() {
    return __t.array(EntityBlobAsset);
  },
  get newPlayerBlob() {
    return EntityBlobAsset;
  },
});
export type AssetPack = __Infer<typeof AssetPack>;

export const AttackComponent = __t.object("AttackComponent", {
  entityId: __t.u64(),
  attack: __t.i8(),
});
export type AttackComponent = __Infer<typeof AttackComponent>;

export const AttackComponentBlob = __t.object("AttackComponentBlob", {
  attack: __t.i8(),
});
export type AttackComponentBlob = __Infer<typeof AttackComponentBlob>;

export const Baseline = __t.object("Baseline", {
  id: __t.u32(),
  name: __t.string(),
  get statBlock() {
    return StatBlock;
  },
});
export type Baseline = __Infer<typeof Baseline>;

export const BaselineComponent = __t.object("BaselineComponent", {
  entityId: __t.u64(),
  baselineId: __t.u32(),
});
export type BaselineComponent = __Infer<typeof BaselineComponent>;

export const BaselineComponentBlob = __t.object("BaselineComponentBlob", {
  baselineId: __t.u32(),
});
export type BaselineComponentBlob = __Infer<typeof BaselineComponentBlob>;

export const Bitset = __t.object("Bitset", {
  bytes: __t.byteArray(),
});
export type Bitset = __Infer<typeof Bitset>;

export const BracedStatusComponent = __t.object("BracedStatusComponent", {
  entityId: __t.u64(),
  defense: __t.i16(),
});
export type BracedStatusComponent = __Infer<typeof BracedStatusComponent>;

export const BracedStatusComponentBlob = __t.object("BracedStatusComponentBlob", {
  defense: __t.i16(),
});
export type BracedStatusComponentBlob = __Infer<typeof BracedStatusComponentBlob>;

// The tagged union or sum type for the algebraic type `Buff`.
export const Buff = __t.enum("Buff", {
  Guard: __t.i32(),
});
export type Buff = __Infer<typeof Buff>;

export const CheckpointBindingAsset = __t.object("CheckpointBindingAsset", {
  locationMapName: __t.string(),
  checkpointIndex: __t.u32(),
});
export type CheckpointBindingAsset = __Infer<typeof CheckpointBindingAsset>;

export const CheckpointBindingComponent = __t.object("CheckpointBindingComponent", {
  entityId: __t.u64(),
  locationMapId: __t.u32(),
  checkpointIndex: __t.u32(),
});
export type CheckpointBindingComponent = __Infer<typeof CheckpointBindingComponent>;

export const CheckpointBindingComponentBlob = __t.object("CheckpointBindingComponentBlob", {
  locationMapId: __t.u32(),
  checkpointIndex: __t.u32(),
});
export type CheckpointBindingComponentBlob = __Infer<typeof CheckpointBindingComponentBlob>;

export const CheckpointComponent = __t.object("CheckpointComponent", {
  entityId: __t.u64(),
  locationMapId: __t.u32(),
  checkpointIndex: __t.u32(),
});
export type CheckpointComponent = __Infer<typeof CheckpointComponent>;

export const CheckpointComponentBlob = __t.object("CheckpointComponentBlob", {
  locationMapId: __t.u32(),
  checkpointIndex: __t.u32(),
});
export type CheckpointComponentBlob = __Infer<typeof CheckpointComponentBlob>;

// The tagged union or sum type for the algebraic type `ConnectionAnchor`.
export const ConnectionAnchor = __t.enum("ConnectionAnchor", {
  Entrance: __t.unit(),
  Ending: __t.unit(),
  Edge: __t.unit(),
  Branch: __t.unit(),
});
export type ConnectionAnchor = __Infer<typeof ConnectionAnchor>;

export const CourageStatusComponent = __t.object("CourageStatusComponent", {
  entityId: __t.u64(),
  morale: __t.i16(),
});
export type CourageStatusComponent = __Infer<typeof CourageStatusComponent>;

export const CourageStatusComponentBlob = __t.object("CourageStatusComponentBlob", {
  morale: __t.i16(),
});
export type CourageStatusComponentBlob = __Infer<typeof CourageStatusComponentBlob>;

export const DefaultArmamentsComponent = __t.object("DefaultArmamentsComponent", {
  entityId: __t.u64(),
  armamentIds: __t.array(__t.u32()),
});
export type DefaultArmamentsComponent = __Infer<typeof DefaultArmamentsComponent>;

export const DefaultArmamentsComponentBlob = __t.object("DefaultArmamentsComponentBlob", {
  armamentIds: __t.array(__t.u32()),
});
export type DefaultArmamentsComponentBlob = __Infer<typeof DefaultArmamentsComponentBlob>;

export const DefeatDropComponent = __t.object("DefeatDropComponent", {
  entityId: __t.u64(),
  questId: __t.u32(),
  index: __t.u32(),
});
export type DefeatDropComponent = __Infer<typeof DefeatDropComponent>;

export const DefeatDropComponentBlob = __t.object("DefeatDropComponentBlob", {
  questId: __t.u32(),
  index: __t.u32(),
});
export type DefeatDropComponentBlob = __Infer<typeof DefeatDropComponentBlob>;

export const DifferentiableAsset = __t.object("DifferentiableAsset", {
  traitPaletteName: __t.string(),
});
export type DifferentiableAsset = __Infer<typeof DifferentiableAsset>;

export const DifferentiableComponent = __t.object("DifferentiableComponent", {
  entityId: __t.u64(),
  traitPaletteId: __t.u32(),
});
export type DifferentiableComponent = __Infer<typeof DifferentiableComponent>;

export const DifferentiableComponentBlob = __t.object("DifferentiableComponentBlob", {
  traitPaletteId: __t.u32(),
});
export type DifferentiableComponentBlob = __Infer<typeof DifferentiableComponentBlob>;

export const Encounter = __t.object("Encounter", {
  id: __t.u32(),
  name: __t.string(),
  categoricBlobId: __t.u32(),
  blobIds: __t.array(__t.u32()),
});
export type Encounter = __Infer<typeof Encounter>;

export const EncounterAsset = __t.object("EncounterAsset", {
  categoricBlobName: __t.string(),
  blobNames: __t.array(__t.string()),
});
export type EncounterAsset = __Infer<typeof EncounterAsset>;

export const EncounterBlob = __t.object("EncounterBlob", {
  id: __t.u32(),
  name: __t.string(),
  get blob() {
    return EntityBlob;
  },
});
export type EncounterBlob = __Infer<typeof EncounterBlob>;

export const EncounterIdSample = __t.object("EncounterIdSample", {
  weight: __t.u8(),
  id: __t.u32(),
});
export type EncounterIdSample = __Infer<typeof EncounterIdSample>;

export const EncounterIdsSampler = __t.object("EncounterIdsSampler", {
  get selections() {
    return __t.array(EncounterIdSample);
  },
});
export type EncounterIdsSampler = __Infer<typeof EncounterIdsSampler>;

export const EnemyControllerComponent = __t.object("EnemyControllerComponent", {
  entityId: __t.u64(),
});
export type EnemyControllerComponent = __Infer<typeof EnemyControllerComponent>;

export const EnemyControllerComponentBlob = __t.object("EnemyControllerComponentBlob", {});
export type EnemyControllerComponentBlob = __Infer<typeof EnemyControllerComponentBlob>;

export const EntitiesQuestsProgress = __t.object("EntitiesQuestsProgress", {
  id: __t.u64(),
  entityId: __t.u64(),
  questId: __t.u32(),
  get bits() {
    return Bitset;
  },
});
export type EntitiesQuestsProgress = __Infer<typeof EntitiesQuestsProgress>;

export const EntitiesVisitedLocation = __t.object("EntitiesVisitedLocation", {
  id: __t.u64(),
  visitorEntityId: __t.u64(),
  locationEntityId: __t.u64(),
});
export type EntitiesVisitedLocation = __Infer<typeof EntitiesVisitedLocation>;

export const Entity = __t.object("Entity", {
  id: __t.u64(),
});
export type Entity = __Infer<typeof Entity>;

export const EntityBlob = __t.object("EntityBlob", {
  get name() {
    return __t.option(NameComponentBlob);
  },
  get location() {
    return __t.option(LocationComponentBlob);
  },
  get path() {
    return __t.option(PathComponentBlob);
  },
  get pathBlocker() {
    return __t.option(PathBlockerComponentBlob);
  },
  get hpShare() {
    return __t.option(HpShareComponentBlob);
  },
  get hpShareApplied() {
    return __t.option(HpShareAppliedComponentBlob);
  },
  get allegiance() {
    return __t.option(AllegianceComponentBlob);
  },
  get party() {
    return __t.option(PartyComponentBlob);
  },
  get baseline() {
    return __t.option(BaselineComponentBlob);
  },
  get traits() {
    return __t.option(TraitsComponentBlob);
  },
  get activeStance() {
    return __t.option(ActiveStanceComponentBlob);
  },
  get equipment() {
    return __t.option(EquipmentComponentBlob);
  },
  get remains() {
    return __t.option(RemainsComponentBlob);
  },
  get defaultArmaments() {
    return __t.option(DefaultArmamentsComponentBlob);
  },
  get armor() {
    return __t.option(ArmorComponentBlob);
  },
  get relics() {
    return __t.option(RelicsComponentBlob);
  },
  get stanceLoadouts() {
    return __t.option(StanceLoadoutsComponentBlob);
  },
  get item() {
    return __t.option(ItemComponentBlob);
  },
  get equipmentStatBlockCache() {
    return __t.option(StatBlockCacheComponentBlob);
  },
  get statusStatBlockCache() {
    return __t.option(StatBlockCacheComponentBlob);
  },
  get traitsStatBlockCache() {
    return __t.option(StatBlockCacheComponentBlob);
  },
  get questStatBlockCache() {
    return __t.option(StatBlockCacheComponentBlob);
  },
  get traitsStatBlockDirtyFlag() {
    return __t.option(FlagComponentBlob);
  },
  get equipmentStatBlockDirtyFlag() {
    return __t.option(FlagComponentBlob);
  },
  get statusStatBlockDirtyFlag() {
    return __t.option(FlagComponentBlob);
  },
  get questStatBlockDirtyFlag() {
    return __t.option(FlagComponentBlob);
  },
  get totalStatBlockDirtyFlag() {
    return __t.option(FlagComponentBlob);
  },
  get checkpointObject() {
    return __t.option(FlagComponentBlob);
  },
  get turnPaused() {
    return __t.option(FlagComponentBlob);
  },
  get open() {
    return __t.option(FlagComponentBlob);
  },
  get stanceForced() {
    return __t.option(FlagComponentBlob);
  },
  get actionQueueDirty() {
    return __t.option(FlagComponentBlob);
  },
  get perished() {
    return __t.option(FlagComponentBlob);
  },
  get checkpoint() {
    return __t.option(CheckpointComponentBlob);
  },
  get differentiable() {
    return __t.option(DifferentiableComponentBlob);
  },
  get mapInstance() {
    return __t.option(MapInstanceComponentBlob);
  },
  get mapCheckpoints() {
    return __t.option(MapCheckpointsComponentBlob);
  },
  get mapRooms() {
    return __t.option(MapRoomsComponentBlob);
  },
  get pendingConnections() {
    return __t.option(PendingConnectionsComponentBlob);
  },
  get checkpointBinding() {
    return __t.option(CheckpointBindingComponentBlob);
  },
  get defeatDrop() {
    return __t.option(DefeatDropComponentBlob);
  },
  get attack() {
    return __t.option(AttackComponentBlob);
  },
  get hp() {
    return __t.option(HpComponentBlob);
  },
  get ep() {
    return __t.option(EpComponentBlob);
  },
  get totalStatBlock() {
    return __t.option(TotalStatBlockComponentBlob);
  },
  get fearStatus() {
    return __t.option(FearStatusComponentBlob);
  },
  get courageStatus() {
    return __t.option(CourageStatusComponentBlob);
  },
  get bracedStatus() {
    return __t.option(BracedStatusComponentBlob);
  },
  get playerController() {
    return __t.option(PlayerControllerComponentBlob);
  },
  get enemyController() {
    return __t.option(EnemyControllerComponentBlob);
  },
  get actionState() {
    return __t.option(ActionStateComponentBlob);
  },
  get actionQueue() {
    return __t.option(ActionQueueComponentBlob);
  },
  get actions() {
    return __t.option(ActionsComponentBlob);
  },
  get offeredActions() {
    return __t.option(ActionsComponentBlob);
  },
  get defaultActions() {
    return __t.option(ActionsComponentBlob);
  },
  get pinnedActions() {
    return __t.option(PinnedActionsComponentBlob);
  },
  get entityDeletionTimer() {
    return __t.option(TimerComponentBlob);
  },
  get playerDeactivationTimer() {
    return __t.option(TimerComponentBlob);
  },
  get respawnTimer() {
    return __t.option(TimerComponentBlob);
  },
  get mapCleanupTimer() {
    return __t.option(TimerComponentBlob);
  },
  get actionlessSince() {
    return __t.option(TimerComponentBlob);
  },
  get locationMap() {
    return __t.option(LocationMapComponentBlob);
  },
  get appearanceFeatures() {
    return __t.option(AppearanceFeaturesComponentBlob);
  },
});
export type EntityBlob = __Infer<typeof EntityBlob>;

export const EntityBlobAsset = __t.object("EntityBlobAsset", {
  get name() {
    return __t.option(NameComponentBlob);
  },
  get location() {
    return __t.option(LocationComponentBlob);
  },
  get path() {
    return __t.option(PathComponentBlob);
  },
  get allegiance() {
    return __t.option(AllegianceComponentBlob);
  },
  baselineName: __t.option(__t.string()),
  stanceName: __t.option(__t.string()),
  traitNames: __t.option(__t.array(__t.string())),
  armamentNames: __t.option(__t.array(__t.string())),
  armorName: __t.option(__t.string()),
  relicNames: __t.option(__t.array(__t.string())),
  get item() {
    return __t.option(ItemRefAsset);
  },
  actionNames: __t.option(__t.array(__t.string())),
  offeredActionNames: __t.option(__t.array(__t.string())),
  pinnedActionNames: __t.option(__t.array(__t.string())),
  appearanceFeatureNames: __t.option(__t.array(__t.string())),
  remainsAppearanceFeatureNames: __t.option(__t.array(__t.string())),
  get hp() {
    return __t.option(HpComponentBlob);
  },
  get ep() {
    return __t.option(EpComponentBlob);
  },
  get attack() {
    return __t.option(AttackComponentBlob);
  },
  get playerController() {
    return __t.option(PlayerControllerComponentBlob);
  },
  get enemyController() {
    return __t.option(EnemyControllerComponentBlob);
  },
  get differentiable() {
    return __t.option(DifferentiableAsset);
  },
  get checkpointObject() {
    return __t.option(FlagComponentBlob);
  },
  get checkpointBinding() {
    return __t.option(CheckpointBindingAsset);
  },
});
export type EntityBlobAsset = __Infer<typeof EntityBlobAsset>;

export const EntityBlobSample = __t.object("EntityBlobSample", {
  weight: __t.u8(),
  get blob() {
    return EntityBlob;
  },
});
export type EntityBlobSample = __Infer<typeof EntityBlobSample>;

export const EntityBlobSampleAsset = __t.object("EntityBlobSampleAsset", {
  weight: __t.u8(),
  get blob() {
    return EntityBlobAsset;
  },
});
export type EntityBlobSampleAsset = __Infer<typeof EntityBlobSampleAsset>;

export const EntityBlobsSampler = __t.object("EntityBlobsSampler", {
  get selections() {
    return __t.array(EntityBlobSample);
  },
});
export type EntityBlobsSampler = __Infer<typeof EntityBlobsSampler>;

export const EntityBlobsSamplerAsset = __t.object("EntityBlobsSamplerAsset", {
  get selections() {
    return __t.array(EntityBlobSampleAsset);
  },
});
export type EntityBlobsSamplerAsset = __Infer<typeof EntityBlobsSamplerAsset>;

export const EntityEvent = __t.object("EntityEvent", {
  id: __t.u64(),
  time: __t.timestamp(),
  ownerEntityId: __t.u64(),
  get eventType() {
    return EventType;
  },
  targetEntityId: __t.u64(),
  get statBlock() {
    return __t.option(StatBlock);
  },
});
export type EntityEvent = __Infer<typeof EntityEvent>;

// The tagged union or sum type for the algebraic type `EntityIdSelector`.
export const EntityIdSelector = __t.enum("EntityIdSelector", {
  Literal: __t.u64(),
  Local: __t.u32(),
  Named: __t.string(),
});
export type EntityIdSelector = __Infer<typeof EntityIdSelector>;

export const EpComponent = __t.object("EpComponent", {
  entityId: __t.u64(),
  ep: __t.i16(),
  mep: __t.i16(),
});
export type EpComponent = __Infer<typeof EpComponent>;

export const EpComponentBlob = __t.object("EpComponentBlob", {
  ep: __t.i16(),
  mep: __t.i16(),
});
export type EpComponentBlob = __Infer<typeof EpComponentBlob>;

export const EquipmentComponent = __t.object("EquipmentComponent", {
  entityId: __t.u64(),
  armamentIds: __t.array(__t.u32()),
  wornArmorId: __t.option(__t.u32()),
  wornRelicIds: __t.array(__t.u32()),
});
export type EquipmentComponent = __Infer<typeof EquipmentComponent>;

export const EquipmentComponentBlob = __t.object("EquipmentComponentBlob", {
  armamentIds: __t.array(__t.u32()),
  wornArmorId: __t.option(__t.u32()),
  wornRelicIds: __t.array(__t.u32()),
});
export type EquipmentComponentBlob = __Infer<typeof EquipmentComponentBlob>;

// The tagged union or sum type for the algebraic type `EventType`.
export const EventType = __t.enum("EventType", {
  StartAction: __t.u32(),
  get ActionEffect() {
    return ActionEffect;
  },
  get ActionFailed() {
    return ActionEffect;
  },
  TargetLost: __t.u32(),
  Died: __t.unit(),
  Shattered: __t.unit(),
  Spilled: __t.unit(),
});
export type EventType = __Infer<typeof EventType>;

export const FearStatusComponent = __t.object("FearStatusComponent", {
  entityId: __t.u64(),
  intimidation: __t.i16(),
});
export type FearStatusComponent = __Infer<typeof FearStatusComponent>;

export const FearStatusComponentBlob = __t.object("FearStatusComponentBlob", {
  intimidation: __t.i16(),
});
export type FearStatusComponentBlob = __Infer<typeof FearStatusComponentBlob>;

export const FlagComponent = __t.object("FlagComponent", {
  entityId: __t.u64(),
});
export type FlagComponent = __Infer<typeof FlagComponent>;

export const FlagComponentBlob = __t.object("FlagComponentBlob", {});
export type FlagComponentBlob = __Infer<typeof FlagComponentBlob>;

export const HpComponent = __t.object("HpComponent", {
  entityId: __t.u64(),
  hp: __t.i16(),
  mhp: __t.i16(),
  defense: __t.i8(),
  accumulatedDamage: __t.i16(),
  accumulatedHealing: __t.i16(),
});
export type HpComponent = __Infer<typeof HpComponent>;

export const HpComponentBlob = __t.object("HpComponentBlob", {
  hp: __t.i16(),
  mhp: __t.i16(),
  defense: __t.i8(),
  accumulatedDamage: __t.i16(),
  accumulatedHealing: __t.i16(),
});
export type HpComponentBlob = __Infer<typeof HpComponentBlob>;

export const HpShareAppliedComponent = __t.object("HpShareAppliedComponent", {
  entityId: __t.u64(),
  damage: __t.i16(),
  healing: __t.i16(),
});
export type HpShareAppliedComponent = __Infer<typeof HpShareAppliedComponent>;

export const HpShareAppliedComponentBlob = __t.object("HpShareAppliedComponentBlob", {
  damage: __t.i16(),
  healing: __t.i16(),
});
export type HpShareAppliedComponentBlob = __Infer<typeof HpShareAppliedComponentBlob>;

export const HpShareComponent = __t.object("HpShareComponent", {
  entityId: __t.u64(),
  partnerEntityId: __t.u64(),
});
export type HpShareComponent = __Infer<typeof HpShareComponent>;

export const HpShareComponentBlob = __t.object("HpShareComponentBlob", {
  get partnerEntityId() {
    return EntityIdSelector;
  },
});
export type HpShareComponentBlob = __Infer<typeof HpShareComponentBlob>;

export const ItemComponent = __t.object("ItemComponent", {
  entityId: __t.u64(),
  get itemRef() {
    return ItemRef;
  },
});
export type ItemComponent = __Infer<typeof ItemComponent>;

export const ItemComponentBlob = __t.object("ItemComponentBlob", {
  get itemRef() {
    return ItemRef;
  },
});
export type ItemComponentBlob = __Infer<typeof ItemComponentBlob>;

// The tagged union or sum type for the algebraic type `ItemRef`.
export const ItemRef = __t.enum("ItemRef", {
  Armament: __t.u32(),
  Armor: __t.u32(),
  Relic: __t.u32(),
  get QuestItem() {
    return QuestItemRef;
  },
});
export type ItemRef = __Infer<typeof ItemRef>;

// The tagged union or sum type for the algebraic type `ItemRefAsset`.
export const ItemRefAsset = __t.enum("ItemRefAsset", {
  Armament: __t.string(),
  Armor: __t.string(),
  Relic: __t.string(),
  get QuestItem() {
    return QuestItemRefAsset;
  },
});
export type ItemRefAsset = __Infer<typeof ItemRefAsset>;

// The tagged union or sum type for the algebraic type `Layout`.
export const Layout = __t.enum("Layout", {
  Path: __t.unit(),
  Hub: __t.unit(),
});
export type Layout = __Infer<typeof Layout>;

export const LocationComponent = __t.object("LocationComponent", {
  entityId: __t.u64(),
  locationEntityId: __t.u64(),
  get kind() {
    return LocationKind;
  },
});
export type LocationComponent = __Infer<typeof LocationComponent>;

export const LocationComponentBlob = __t.object("LocationComponentBlob", {
  get locationEntityId() {
    return EntityIdSelector;
  },
  get kind() {
    return LocationKind;
  },
});
export type LocationComponentBlob = __Infer<typeof LocationComponentBlob>;

// The tagged union or sum type for the algebraic type `LocationKind`.
export const LocationKind = __t.enum("LocationKind", {
  Exterior: __t.unit(),
  Interior: __t.unit(),
});
export type LocationKind = __Infer<typeof LocationKind>;

export const LocationMap = __t.object("LocationMap", {
  id: __t.u32(),
  name: __t.string(),
  themeId: __t.u32(),
  get layout() {
    return Layout;
  },
  get zoneKind() {
    return ZoneKind;
  },
  rngSeed: __t.option(__t.u64()),
  extraRoomCount: __t.u8(),
  mainRoomCount: __t.u8(),
  loopCount: __t.u8(),
  get encounterIdsSampler() {
    return EncounterIdsSampler;
  },
  minEncounterCount: __t.u8(),
  maxEncounterCount: __t.u8(),
  minHiddenRoomCount: __t.u8(),
  maxHiddenRoomCount: __t.u8(),
  get questSpawns() {
    return __t.array(QuestSpawn);
  },
  get questRoomClaims() {
    return __t.array(QuestRoomClaim);
  },
  get roomLocation() {
    return __t.option(RoomLocationAsset);
  },
});
export type LocationMap = __Infer<typeof LocationMap>;

export const LocationMapAsset = __t.object("LocationMapAsset", {
  themeName: __t.string(),
  get layout() {
    return Layout;
  },
  get zoneKind() {
    return ZoneKind;
  },
  rngSeed: __t.option(__t.u64()),
  extraRoomCount: __t.u8(),
  mainRoomCount: __t.u8(),
  loopCount: __t.u8(),
  get encounterNamesSampler() {
    return __t.array(WeightedNameAsset);
  },
  minEncounterCount: __t.u8(),
  maxEncounterCount: __t.u8(),
  minHiddenRoomCount: __t.u8(),
  maxHiddenRoomCount: __t.u8(),
  get questSpawns() {
    return __t.array(QuestSpawnAsset);
  },
  get questRoomClaims() {
    return __t.array(QuestRoomClaimAsset);
  },
  get roomLocation() {
    return __t.option(RoomLocationAsset);
  },
});
export type LocationMapAsset = __Infer<typeof LocationMapAsset>;

export const LocationMapComponent = __t.object("LocationMapComponent", {
  entityId: __t.u64(),
  locationMapEntityId: __t.u64(),
});
export type LocationMapComponent = __Infer<typeof LocationMapComponent>;

export const LocationMapComponentBlob = __t.object("LocationMapComponentBlob", {
  get locationMapEntityId() {
    return EntityIdSelector;
  },
});
export type LocationMapComponentBlob = __Infer<typeof LocationMapComponentBlob>;

export const LocationMapConnection = __t.object("LocationMapConnection", {
  id: __t.u32(),
  exitLocationMapId: __t.u32(),
  destinationLocationMapId: __t.u32(),
  get exitAnchor() {
    return ConnectionAnchor;
  },
  get destinationAnchor() {
    return ConnectionAnchor;
  },
  get pathBlob() {
    return __t.option(EntityBlob);
  },
});
export type LocationMapConnection = __Infer<typeof LocationMapConnection>;

export const LocationMapConnectionAsset = __t.object("LocationMapConnectionAsset", {
  exitLocationMapName: __t.string(),
  destinationLocationMapName: __t.string(),
  get exitAnchor() {
    return ConnectionAnchor;
  },
  get destinationAnchor() {
    return ConnectionAnchor;
  },
  bothWays: __t.bool(),
  get pathPair() {
    return __t.option(PathBlobPairAsset);
  },
});
export type LocationMapConnectionAsset = __Infer<typeof LocationMapConnectionAsset>;

export const LocationMapTheme = __t.object("LocationMapTheme", {
  id: __t.u32(),
  name: __t.string(),
  get decorationsSelector() {
    return EntityBlobsSampler;
  },
  minDecorationCount: __t.u8(),
  maxDecorationCount: __t.u8(),
  get pathsSelector() {
    return PathBlobPairsSampler;
  },
  get roomsSelector() {
    return EntityBlobsSampler;
  },
  get checkpointsSelector() {
    return EntityBlobsSampler;
  },
  get containersSelector() {
    return EntityBlobsSampler;
  },
  minContainerCount: __t.u8(),
  maxContainerCount: __t.u8(),
  get blockersSelector() {
    return EntityBlobsSampler;
  },
  pathVariationTraitIds: __t.array(__t.u32()),
  pathVariationCountWeights: __t.byteArray(),
});
export type LocationMapTheme = __Infer<typeof LocationMapTheme>;

export const LocationMapThemeAsset = __t.object("LocationMapThemeAsset", {
  get decorationsSelector() {
    return EntityBlobsSamplerAsset;
  },
  minDecorationCount: __t.u8(),
  maxDecorationCount: __t.u8(),
  get pathsSelector() {
    return PathBlobPairsSamplerAsset;
  },
  get roomsSelector() {
    return EntityBlobsSamplerAsset;
  },
  get checkpointsSelector() {
    return EntityBlobsSamplerAsset;
  },
  get containersSelector() {
    return EntityBlobsSamplerAsset;
  },
  minContainerCount: __t.u8(),
  maxContainerCount: __t.u8(),
  get blockersSelector() {
    return EntityBlobsSamplerAsset;
  },
  pathVariationTraitNames: __t.array(__t.string()),
  pathVariationCountWeights: __t.byteArray(),
});
export type LocationMapThemeAsset = __Infer<typeof LocationMapThemeAsset>;

export const LoginFinalizeTimer = __t.object("LoginFinalizeTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  loginRequestId: __t.u64(),
});
export type LoginFinalizeTimer = __Infer<typeof LoginFinalizeTimer>;

export const LoginRequest = __t.object("LoginRequest", {
  id: __t.u64(),
  accountId: __t.u64(),
  identity: __t.identity(),
  requestedAt: __t.timestamp(),
  get status() {
    return LoginRequestStatus;
  },
  quorumReachedAt: __t.option(__t.timestamp()),
  resolvedAt: __t.option(__t.timestamp()),
});
export type LoginRequest = __Infer<typeof LoginRequest>;

export const LoginRequestCode = __t.object("LoginRequestCode", {
  loginRequestId: __t.u64(),
  verificationCode: __t.string(),
});
export type LoginRequestCode = __Infer<typeof LoginRequestCode>;

// The tagged union or sum type for the algebraic type `LoginRequestStatus`.
export const LoginRequestStatus = __t.enum("LoginRequestStatus", {
  Pending: __t.unit(),
  Accepted: __t.unit(),
  Refused: __t.unit(),
});
export type LoginRequestStatus = __Infer<typeof LoginRequestStatus>;

export const LoginRequestVoter = __t.object("LoginRequestVoter", {
  id: __t.u64(),
  loginRequestId: __t.u64(),
  identity: __t.identity(),
});
export type LoginRequestVoter = __Infer<typeof LoginRequestVoter>;

export const LoginResponse = __t.object("LoginResponse", {
  id: __t.u64(),
  loginRequestId: __t.u64(),
  identity: __t.identity(),
  accepted: __t.bool(),
  respondedAt: __t.timestamp(),
});
export type LoginResponse = __Infer<typeof LoginResponse>;

export const MapCheckpointsComponent = __t.object("MapCheckpointsComponent", {
  entityId: __t.u64(),
  checkpointRoomEntityIds: __t.array(__t.u64()),
});
export type MapCheckpointsComponent = __Infer<typeof MapCheckpointsComponent>;

export const MapCheckpointsComponentBlob = __t.object("MapCheckpointsComponentBlob", {
  checkpointRoomEntityIds: __t.array(__t.u64()),
});
export type MapCheckpointsComponentBlob = __Infer<typeof MapCheckpointsComponentBlob>;

export const MapInstanceComponent = __t.object("MapInstanceComponent", {
  entityId: __t.u64(),
  locationMapId: __t.u32(),
});
export type MapInstanceComponent = __Infer<typeof MapInstanceComponent>;

export const MapInstanceComponentBlob = __t.object("MapInstanceComponentBlob", {
  locationMapId: __t.u32(),
});
export type MapInstanceComponentBlob = __Infer<typeof MapInstanceComponentBlob>;

export const MapRoomsComponent = __t.object("MapRoomsComponent", {
  entityId: __t.u64(),
  mainRoomEntityIds: __t.array(__t.u64()),
  extraRoomEntityIds: __t.array(__t.u64()),
});
export type MapRoomsComponent = __Infer<typeof MapRoomsComponent>;

export const MapRoomsComponentBlob = __t.object("MapRoomsComponentBlob", {
  mainRoomEntityIds: __t.array(__t.u64()),
  extraRoomEntityIds: __t.array(__t.u64()),
});
export type MapRoomsComponentBlob = __Infer<typeof MapRoomsComponentBlob>;

export const NameComponent = __t.object("NameComponent", {
  entityId: __t.u64(),
  name: __t.string(),
});
export type NameComponent = __Infer<typeof NameComponent>;

export const NameComponentBlob = __t.object("NameComponentBlob", {
  name: __t.string(),
});
export type NameComponentBlob = __Infer<typeof NameComponentBlob>;

export const NamedActionAsset = __t.object("NamedActionAsset", {
  name: __t.string(),
  get value() {
    return ActionAsset;
  },
});
export type NamedActionAsset = __Infer<typeof NamedActionAsset>;

export const NamedAppearanceFeatureAsset = __t.object("NamedAppearanceFeatureAsset", {
  name: __t.string(),
  get value() {
    return AppearanceFeatureAsset;
  },
});
export type NamedAppearanceFeatureAsset = __Infer<typeof NamedAppearanceFeatureAsset>;

export const NamedEncounterAsset = __t.object("NamedEncounterAsset", {
  name: __t.string(),
  get value() {
    return EncounterAsset;
  },
});
export type NamedEncounterAsset = __Infer<typeof NamedEncounterAsset>;

export const NamedEntity = __t.object("NamedEntity", {
  name: __t.string(),
  entityId: __t.u64(),
});
export type NamedEntity = __Infer<typeof NamedEntity>;

export const NamedEntityBlobAsset = __t.object("NamedEntityBlobAsset", {
  name: __t.string(),
  get value() {
    return EntityBlobAsset;
  },
});
export type NamedEntityBlobAsset = __Infer<typeof NamedEntityBlobAsset>;

export const NamedLocationMapAsset = __t.object("NamedLocationMapAsset", {
  name: __t.string(),
  get value() {
    return LocationMapAsset;
  },
});
export type NamedLocationMapAsset = __Infer<typeof NamedLocationMapAsset>;

export const NamedLocationMapThemeAsset = __t.object("NamedLocationMapThemeAsset", {
  name: __t.string(),
  get value() {
    return LocationMapThemeAsset;
  },
});
export type NamedLocationMapThemeAsset = __Infer<typeof NamedLocationMapThemeAsset>;

export const NamedQuestAsset = __t.object("NamedQuestAsset", {
  name: __t.string(),
  get value() {
    return QuestAsset;
  },
});
export type NamedQuestAsset = __Infer<typeof NamedQuestAsset>;

export const NamedStanceAsset = __t.object("NamedStanceAsset", {
  name: __t.string(),
  get value() {
    return StanceAsset;
  },
});
export type NamedStanceAsset = __Infer<typeof NamedStanceAsset>;

export const NamedStatBlockAsset = __t.object("NamedStatBlockAsset", {
  name: __t.string(),
  get value() {
    return StatBlockAsset;
  },
});
export type NamedStatBlockAsset = __Infer<typeof NamedStatBlockAsset>;

export const NamedTraitPaletteAsset = __t.object("NamedTraitPaletteAsset", {
  name: __t.string(),
  get value() {
    return TraitPaletteAsset;
  },
});
export type NamedTraitPaletteAsset = __Infer<typeof NamedTraitPaletteAsset>;

export const PartyComponent = __t.object("PartyComponent", {
  entityId: __t.u64(),
  partyLeader: __t.u64(),
});
export type PartyComponent = __Infer<typeof PartyComponent>;

export const PartyComponentBlob = __t.object("PartyComponentBlob", {
  get partyLeader() {
    return EntityIdSelector;
  },
});
export type PartyComponentBlob = __Infer<typeof PartyComponentBlob>;

export const PathBlobPair = __t.object("PathBlobPair", {
  get forward() {
    return EntityBlob;
  },
  get backward() {
    return EntityBlob;
  },
});
export type PathBlobPair = __Infer<typeof PathBlobPair>;

export const PathBlobPairAsset = __t.object("PathBlobPairAsset", {
  get forward() {
    return EntityBlobAsset;
  },
  get backward() {
    return EntityBlobAsset;
  },
});
export type PathBlobPairAsset = __Infer<typeof PathBlobPairAsset>;

export const PathBlobPairSample = __t.object("PathBlobPairSample", {
  weight: __t.u8(),
  get pair() {
    return PathBlobPair;
  },
});
export type PathBlobPairSample = __Infer<typeof PathBlobPairSample>;

export const PathBlobPairSampleAsset = __t.object("PathBlobPairSampleAsset", {
  weight: __t.u8(),
  get pair() {
    return PathBlobPairAsset;
  },
});
export type PathBlobPairSampleAsset = __Infer<typeof PathBlobPairSampleAsset>;

export const PathBlobPairsSampler = __t.object("PathBlobPairsSampler", {
  get selections() {
    return __t.array(PathBlobPairSample);
  },
});
export type PathBlobPairsSampler = __Infer<typeof PathBlobPairsSampler>;

export const PathBlobPairsSamplerAsset = __t.object("PathBlobPairsSamplerAsset", {
  get selections() {
    return __t.array(PathBlobPairSampleAsset);
  },
});
export type PathBlobPairsSamplerAsset = __Infer<typeof PathBlobPairsSamplerAsset>;

export const PathBlockerComponent = __t.object("PathBlockerComponent", {
  entityId: __t.u64(),
  blockerEntityId: __t.u64(),
});
export type PathBlockerComponent = __Infer<typeof PathBlockerComponent>;

export const PathBlockerComponentBlob = __t.object("PathBlockerComponentBlob", {
  get blockerEntityId() {
    return EntityIdSelector;
  },
});
export type PathBlockerComponentBlob = __Infer<typeof PathBlockerComponentBlob>;

export const PathComponent = __t.object("PathComponent", {
  entityId: __t.u64(),
  destinationEntityId: __t.u64(),
  get destinationKind() {
    return LocationKind;
  },
});
export type PathComponent = __Infer<typeof PathComponent>;

export const PathComponentBlob = __t.object("PathComponentBlob", {
  get destinationEntityId() {
    return EntityIdSelector;
  },
  get destinationKind() {
    return LocationKind;
  },
});
export type PathComponentBlob = __Infer<typeof PathComponentBlob>;

export const PendingConnectionsComponent = __t.object("PendingConnectionsComponent", {
  entityId: __t.u64(),
  connectionIds: __t.array(__t.u32()),
});
export type PendingConnectionsComponent = __Infer<typeof PendingConnectionsComponent>;

export const PendingConnectionsComponentBlob = __t.object("PendingConnectionsComponentBlob", {
  connectionIds: __t.array(__t.u32()),
});
export type PendingConnectionsComponentBlob = __Infer<typeof PendingConnectionsComponentBlob>;

export const PinnedActionsComponent = __t.object("PinnedActionsComponent", {
  entityId: __t.u64(),
  actionIds: __t.array(__t.u32()),
});
export type PinnedActionsComponent = __Infer<typeof PinnedActionsComponent>;

export const PinnedActionsComponentBlob = __t.object("PinnedActionsComponentBlob", {
  actionIds: __t.array(__t.u32()),
});
export type PinnedActionsComponentBlob = __Infer<typeof PinnedActionsComponentBlob>;

export const PlayerControllerComponent = __t.object("PlayerControllerComponent", {
  entityId: __t.u64(),
  accountId: __t.u64(),
});
export type PlayerControllerComponent = __Infer<typeof PlayerControllerComponent>;

export const PlayerControllerComponentBlob = __t.object("PlayerControllerComponentBlob", {
  accountId: __t.u64(),
});
export type PlayerControllerComponentBlob = __Infer<typeof PlayerControllerComponentBlob>;

export const Quest = __t.object("Quest", {
  id: __t.u32(),
  name: __t.string(),
  get perBitStatBlock() {
    return StatBlock;
  },
  bitCount: __t.u32(),
});
export type Quest = __Infer<typeof Quest>;

export const QuestAsset = __t.object("QuestAsset", {
  get perBitStatBlock() {
    return StatBlockAsset;
  },
  bitCount: __t.u32(),
});
export type QuestAsset = __Infer<typeof QuestAsset>;

export const QuestDefeatDrop = __t.object("QuestDefeatDrop", {
  questId: __t.u32(),
  index: __t.u32(),
  get itemBlob() {
    return EntityBlob;
  },
});
export type QuestDefeatDrop = __Infer<typeof QuestDefeatDrop>;

export const QuestDefeatDropAsset = __t.object("QuestDefeatDropAsset", {
  questName: __t.string(),
  index: __t.u32(),
  get itemBlob() {
    return EntityBlobAsset;
  },
});
export type QuestDefeatDropAsset = __Infer<typeof QuestDefeatDropAsset>;

export const QuestItemRef = __t.object("QuestItemRef", {
  questId: __t.u32(),
  index: __t.u32(),
});
export type QuestItemRef = __Infer<typeof QuestItemRef>;

export const QuestItemRefAsset = __t.object("QuestItemRefAsset", {
  questName: __t.string(),
  index: __t.u32(),
});
export type QuestItemRefAsset = __Infer<typeof QuestItemRefAsset>;

export const QuestRoomClaim = __t.object("QuestRoomClaim", {
  questId: __t.u32(),
  get role() {
    return QuestRoomRole;
  },
  encounterId: __t.u32(),
  spawnCheckpointBefore: __t.bool(),
  get defeatDrop() {
    return __t.option(QuestDefeatDrop);
  },
});
export type QuestRoomClaim = __Infer<typeof QuestRoomClaim>;

export const QuestRoomClaimAsset = __t.object("QuestRoomClaimAsset", {
  questName: __t.string(),
  get role() {
    return QuestRoomRole;
  },
  encounterName: __t.string(),
  spawnCheckpointBefore: __t.bool(),
  get defeatDrop() {
    return __t.option(QuestDefeatDropAsset);
  },
});
export type QuestRoomClaimAsset = __Infer<typeof QuestRoomClaimAsset>;

// The tagged union or sum type for the algebraic type `QuestRoomRole`.
export const QuestRoomRole = __t.enum("QuestRoomRole", {
  Boss: __t.unit(),
});
export type QuestRoomRole = __Infer<typeof QuestRoomRole>;

export const QuestSpawn = __t.object("QuestSpawn", {
  questId: __t.u32(),
  get itemBlob() {
    return EntityBlob;
  },
  get guaranteedIndexes() {
    return Bitset;
  },
  get eligibleIndexes() {
    return Bitset;
  },
  minEligibleCount: __t.u8(),
  maxEligibleCount: __t.u8(),
});
export type QuestSpawn = __Infer<typeof QuestSpawn>;

export const QuestSpawnAsset = __t.object("QuestSpawnAsset", {
  questName: __t.string(),
  get itemBlob() {
    return EntityBlobAsset;
  },
  guaranteedIndexes: __t.array(__t.u32()),
  eligibleIndexes: __t.array(__t.u32()),
  minEligibleCount: __t.u8(),
  maxEligibleCount: __t.u8(),
});
export type QuestSpawnAsset = __Infer<typeof QuestSpawnAsset>;

export const QuestsRoomsRole = __t.object("QuestsRoomsRole", {
  id: __t.u64(),
  questId: __t.u32(),
  roomEntityId: __t.u64(),
  get role() {
    return QuestRoomRole;
  },
});
export type QuestsRoomsRole = __Infer<typeof QuestsRoomsRole>;

export const QueuedAction = __t.object("QueuedAction", {
  actionId: __t.u32(),
  targetEntityId: __t.u64(),
  automatic: __t.bool(),
});
export type QueuedAction = __Infer<typeof QueuedAction>;

export const Relic = __t.object("Relic", {
  id: __t.u32(),
  name: __t.string(),
  get statBlock() {
    return StatBlock;
  },
});
export type Relic = __Infer<typeof Relic>;

export const RelicsComponent = __t.object("RelicsComponent", {
  entityId: __t.u64(),
  relicIds: __t.array(__t.u32()),
});
export type RelicsComponent = __Infer<typeof RelicsComponent>;

export const RelicsComponentBlob = __t.object("RelicsComponentBlob", {
  relicIds: __t.array(__t.u32()),
});
export type RelicsComponentBlob = __Infer<typeof RelicsComponentBlob>;

export const RemainsComponent = __t.object("RemainsComponent", {
  entityId: __t.u64(),
  appearanceFeatureIds: __t.array(__t.u32()),
});
export type RemainsComponent = __Infer<typeof RemainsComponent>;

export const RemainsComponentBlob = __t.object("RemainsComponentBlob", {
  appearanceFeatureIds: __t.array(__t.u32()),
});
export type RemainsComponentBlob = __Infer<typeof RemainsComponentBlob>;

export const Role = __t.object("Role", {
  id: __t.u32(),
  name: __t.string(),
});
export type Role = __Infer<typeof Role>;

export const RoomLocationAsset = __t.object("RoomLocationAsset", {
  locationName: __t.string(),
  get kind() {
    return LocationKind;
  },
});
export type RoomLocationAsset = __Infer<typeof RoomLocationAsset>;

export const SpecialAction = __t.object("SpecialAction", {
  get key() {
    return SpecialActionKey;
  },
  actionId: __t.u32(),
});
export type SpecialAction = __Infer<typeof SpecialAction>;

// The tagged union or sum type for the algebraic type `SpecialActionKey`.
export const SpecialActionKey = __t.enum("SpecialActionKey", {
  Take: __t.unit(),
  Drop: __t.unit(),
  Equip: __t.unit(),
  Unequip: __t.unit(),
  Eat: __t.unit(),
  Rearm: __t.unit(),
  Move: __t.unit(),
});
export type SpecialActionKey = __Infer<typeof SpecialActionKey>;

export const SpecialEntityBlob = __t.object("SpecialEntityBlob", {
  get key() {
    return SpecialEntityBlobKey;
  },
  get blob() {
    return EntityBlob;
  },
});
export type SpecialEntityBlob = __Infer<typeof SpecialEntityBlob>;

// The tagged union or sum type for the algebraic type `SpecialEntityBlobKey`.
export const SpecialEntityBlobKey = __t.enum("SpecialEntityBlobKey", {
  NewPlayer: __t.unit(),
});
export type SpecialEntityBlobKey = __Infer<typeof SpecialEntityBlobKey>;

export const SpecialStance = __t.object("SpecialStance", {
  get key() {
    return SpecialStanceKey;
  },
  stanceId: __t.u32(),
});
export type SpecialStance = __Infer<typeof SpecialStance>;

// The tagged union or sum type for the algebraic type `SpecialStanceKey`.
export const SpecialStanceKey = __t.enum("SpecialStanceKey", {
  Cowering: __t.unit(),
  Prone: __t.unit(),
});
export type SpecialStanceKey = __Infer<typeof SpecialStanceKey>;

export const Stance = __t.object("Stance", {
  id: __t.u32(),
  name: __t.string(),
  get requirements() {
    return StatRequirements;
  },
  get statBlock() {
    return StatBlock;
  },
});
export type Stance = __Infer<typeof Stance>;

export const StanceAsset = __t.object("StanceAsset", {
  get requirements() {
    return StatRequirements;
  },
  get statBlock() {
    return StatBlockAsset;
  },
});
export type StanceAsset = __Infer<typeof StanceAsset>;

export const StanceLoadout = __t.object("StanceLoadout", {
  stanceId: __t.u32(),
  armamentIds: __t.option(__t.array(__t.u32())),
  actionIds: __t.option(__t.array(__t.u32())),
});
export type StanceLoadout = __Infer<typeof StanceLoadout>;

export const StanceLoadoutsComponent = __t.object("StanceLoadoutsComponent", {
  entityId: __t.u64(),
  get assignments() {
    return __t.array(StanceLoadout);
  },
});
export type StanceLoadoutsComponent = __Infer<typeof StanceLoadoutsComponent>;

export const StanceLoadoutsComponentBlob = __t.object("StanceLoadoutsComponentBlob", {
  get assignments() {
    return __t.array(StanceLoadout);
  },
});
export type StanceLoadoutsComponentBlob = __Infer<typeof StanceLoadoutsComponentBlob>;

export const StatBlock = __t.object("StatBlock", {
  attack: __t.i8(),
  defense: __t.i8(),
  hand: __t.i8(),
  gait: __t.i8(),
  reach: __t.i8(),
  blunt: __t.i8(),
  bladed: __t.i8(),
  pole: __t.i8(),
  ward: __t.i8(),
  focus: __t.i8(),
  wing: __t.i8(),
  upright: __t.i8(),
  size: __t.i8(),
  morale: __t.i8(),
  mhp: __t.i16(),
  mep: __t.i16(),
  actionIds: __t.array(__t.u32()),
  appearanceFeatureIds: __t.array(__t.u32()),
});
export type StatBlock = __Infer<typeof StatBlock>;

export const StatBlockAsset = __t.object("StatBlockAsset", {
  attack: __t.i8(),
  mhp: __t.i16(),
  defense: __t.i8(),
  mep: __t.i16(),
  hand: __t.i8(),
  gait: __t.i8(),
  reach: __t.i8(),
  blunt: __t.i8(),
  bladed: __t.i8(),
  pole: __t.i8(),
  ward: __t.i8(),
  focus: __t.i8(),
  wing: __t.i8(),
  upright: __t.i8(),
  size: __t.i8(),
  morale: __t.i8(),
  actionNames: __t.array(__t.string()),
  appearanceFeatureNames: __t.array(__t.string()),
});
export type StatBlockAsset = __Infer<typeof StatBlockAsset>;

export const StatBlockCacheComponent = __t.object("StatBlockCacheComponent", {
  entityId: __t.u64(),
  get statBlock() {
    return StatBlock;
  },
});
export type StatBlockCacheComponent = __Infer<typeof StatBlockCacheComponent>;

export const StatBlockCacheComponentBlob = __t.object("StatBlockCacheComponentBlob", {
  get statBlock() {
    return StatBlock;
  },
});
export type StatBlockCacheComponentBlob = __Infer<typeof StatBlockCacheComponentBlob>;

export const StatRequirements = __t.object("StatRequirements", {
  attack: __t.option(__t.i8()),
  defense: __t.option(__t.i8()),
  hand: __t.option(__t.i8()),
  gait: __t.option(__t.i8()),
  reach: __t.option(__t.i8()),
  blunt: __t.option(__t.i8()),
  bladed: __t.option(__t.i8()),
  pole: __t.option(__t.i8()),
  ward: __t.option(__t.i8()),
  focus: __t.option(__t.i8()),
  wing: __t.option(__t.i8()),
  upright: __t.option(__t.i8()),
  size: __t.option(__t.i8()),
  morale: __t.option(__t.i8()),
  mhp: __t.option(__t.i16()),
  mep: __t.option(__t.i16()),
});
export type StatRequirements = __Infer<typeof StatRequirements>;

export const SystemTimer = __t.object("SystemTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type SystemTimer = __Infer<typeof SystemTimer>;

export const TimerComponent = __t.object("TimerComponent", {
  entityId: __t.u64(),
  timestamp: __t.timestamp(),
});
export type TimerComponent = __Infer<typeof TimerComponent>;

export const TimerComponentBlob = __t.object("TimerComponentBlob", {
  timestamp: __t.timestamp(),
});
export type TimerComponentBlob = __Infer<typeof TimerComponentBlob>;

export const TotalStatBlockComponent = __t.object("TotalStatBlockComponent", {
  entityId: __t.u64(),
  get statBlock() {
    return StatBlock;
  },
});
export type TotalStatBlockComponent = __Infer<typeof TotalStatBlockComponent>;

export const TotalStatBlockComponentBlob = __t.object("TotalStatBlockComponentBlob", {
  get statBlock() {
    return StatBlock;
  },
});
export type TotalStatBlockComponentBlob = __Infer<typeof TotalStatBlockComponentBlob>;

export const Trait = __t.object("Trait", {
  id: __t.u32(),
  name: __t.string(),
  get statBlock() {
    return StatBlock;
  },
});
export type Trait = __Infer<typeof Trait>;

export const TraitPalette = __t.object("TraitPalette", {
  id: __t.u32(),
  name: __t.string(),
  traitIds: __t.array(__t.u32()),
  countWeights: __t.byteArray(),
});
export type TraitPalette = __Infer<typeof TraitPalette>;

export const TraitPaletteAsset = __t.object("TraitPaletteAsset", {
  traitNames: __t.array(__t.string()),
  countWeights: __t.byteArray(),
});
export type TraitPaletteAsset = __Infer<typeof TraitPaletteAsset>;

export const TraitsComponent = __t.object("TraitsComponent", {
  entityId: __t.u64(),
  traitIds: __t.array(__t.u32()),
});
export type TraitsComponent = __Infer<typeof TraitsComponent>;

export const TraitsComponentBlob = __t.object("TraitsComponentBlob", {
  traitIds: __t.array(__t.u32()),
});
export type TraitsComponentBlob = __Infer<typeof TraitsComponentBlob>;

export const WeightedNameAsset = __t.object("WeightedNameAsset", {
  weight: __t.u8(),
  name: __t.string(),
});
export type WeightedNameAsset = __Infer<typeof WeightedNameAsset>;

// The tagged union or sum type for the algebraic type `ZoneKind`.
export const ZoneKind = __t.enum("ZoneKind", {
  Private: __t.unit(),
  Common: __t.unit(),
});
export type ZoneKind = __Infer<typeof ZoneKind>;

