// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Action = __t.object("Action", {
  id: __t.u32(),
  name: __t.string(),
  get actionType() {
    return ActionType;
  },
});
export type Action = __Infer<typeof Action>;

// The tagged union or sum type for the algebraic type `ActionEffect`.
export const ActionEffect = __t.enum("ActionEffect", {
  get Buff() {
    return Buff;
  },
  Attack: __t.i32(),
  Heal: __t.i32(),
  Rest: __t.unit(),
  Move: __t.unit(),
  Take: __t.unit(),
  Drop: __t.unit(),
  Equip: __t.unit(),
  Unequip: __t.unit(),
});
export type ActionEffect = __Infer<typeof ActionEffect>;

export const ActionHotkey = __t.object("ActionHotkey", {
  actionId: __t.u32(),
  characterCode: __t.u32(),
});
export type ActionHotkey = __Infer<typeof ActionHotkey>;

export const ActionHotkeysComponent = __t.object("ActionHotkeysComponent", {
  entityId: __t.u64(),
  get actionHotkeys() {
    return __t.array(ActionHotkey);
  },
});
export type ActionHotkeysComponent = __Infer<typeof ActionHotkeysComponent>;

export const ActionHotkeysComponentBlob = __t.object("ActionHotkeysComponentBlob", {
  get actionHotkeys() {
    return __t.array(ActionHotkey);
  },
});
export type ActionHotkeysComponentBlob = __Infer<typeof ActionHotkeysComponentBlob>;

export const ActionStateComponent = __t.object("ActionStateComponent", {
  entityId: __t.u64(),
  targetEntityId: __t.u64(),
  actionId: __t.u32(),
  sequenceIndex: __t.i32(),
});
export type ActionStateComponent = __Infer<typeof ActionStateComponent>;

export const ActionStateComponentBlob = __t.object("ActionStateComponentBlob", {
  get targetEntityId() {
    return EntityIdSelector;
  },
  actionId: __t.u32(),
  sequenceIndex: __t.i32(),
});
export type ActionStateComponentBlob = __Infer<typeof ActionStateComponentBlob>;

export const ActionStep = __t.object("ActionStep", {
  id: __t.u64(),
  actionId: __t.u32(),
  sequenceIndex: __t.i32(),
  get actionEffect() {
    return ActionEffect;
  },
});
export type ActionStep = __Infer<typeof ActionStep>;

// The tagged union or sum type for the algebraic type `ActionType`.
export const ActionType = __t.enum("ActionType", {
  Buff: __t.unit(),
  Attack: __t.unit(),
  Move: __t.unit(),
  Inventory: __t.unit(),
  Equip: __t.unit(),
});
export type ActionType = __Infer<typeof ActionType>;

export const ActionsComponent = __t.object("ActionsComponent", {
  entityId: __t.u64(),
  actionIds: __t.array(__t.u32()),
});
export type ActionsComponent = __Infer<typeof ActionsComponent>;

export const ActionsComponentBlob = __t.object("ActionsComponentBlob", {
  actionIds: __t.array(__t.u32()),
});
export type ActionsComponentBlob = __Infer<typeof ActionsComponentBlob>;

export const AllegianceComponent = __t.object("AllegianceComponent", {
  entityId: __t.u64(),
  allegianceEntityId: __t.u64(),
});
export type AllegianceComponent = __Infer<typeof AllegianceComponent>;

export const AllegianceComponentBlob = __t.object("AllegianceComponentBlob", {
  get allegianceEntityId() {
    return EntityIdSelector;
  },
});
export type AllegianceComponentBlob = __Infer<typeof AllegianceComponentBlob>;

export const AppearanceFeature = __t.object("AppearanceFeature", {
  index: __t.u32(),
  text: __t.string(),
  get appearanceFeatureType() {
    return AppearanceFeatureType;
  },
  priority: __t.i32(),
});
export type AppearanceFeature = __Infer<typeof AppearanceFeature>;

// The tagged union or sum type for the algebraic type `AppearanceFeatureType`.
export const AppearanceFeatureType = __t.enum("AppearanceFeatureType", {
  Noun: __t.unit(),
  Adjective: __t.unit(),
});
export type AppearanceFeatureType = __Infer<typeof AppearanceFeatureType>;

export const AppearanceFeaturesComponent = __t.object("AppearanceFeaturesComponent", {
  entityId: __t.u64(),
  appearanceFeatureIndexes: __t.array(__t.u32()),
});
export type AppearanceFeaturesComponent = __Infer<typeof AppearanceFeaturesComponent>;

export const AppearanceFeaturesComponentBlob = __t.object("AppearanceFeaturesComponentBlob", {
  appearanceFeatureIndexes: __t.array(__t.u32()),
});
export type AppearanceFeaturesComponentBlob = __Infer<typeof AppearanceFeaturesComponentBlob>;

export const AssetPack = __t.object("AssetPack", {
  get actions() {
    return __t.array(Action);
  },
  get actionSteps() {
    return __t.array(ActionStep);
  },
  get appearanceFeatures() {
    return __t.array(AppearanceFeature);
  },
  get baselines() {
    return __t.array(Baseline);
  },
  get traits() {
    return __t.array(Trait);
  },
  get encounterBlobs() {
    return __t.array(EncounterBlob);
  },
  get encounters() {
    return __t.array(Encounter);
  },
  get locationMapThemes() {
    return __t.array(LocationMapTheme);
  },
  get locationMaps() {
    return __t.array(LocationMap);
  },
  get locationMapConnections() {
    return __t.array(LocationMapConnection);
  },
  get namedInstantiateEntityBlobs() {
    return __t.array(NamedEntityBlob);
  },
  get instantiateEntityBlobs() {
    return __t.array(EntityBlob);
  },
  get newPlayerBlob() {
    return EntityBlob;
  },
});
export type AssetPack = __Infer<typeof AssetPack>;

export const AttackComponent = __t.object("AttackComponent", {
  entityId: __t.u64(),
  attack: __t.i32(),
});
export type AttackComponent = __Infer<typeof AttackComponent>;

export const AttackComponentBlob = __t.object("AttackComponentBlob", {
  attack: __t.i32(),
});
export type AttackComponentBlob = __Infer<typeof AttackComponentBlob>;

export const Baseline = __t.object("Baseline", {
  id: __t.u32(),
  name: __t.string(),
  get statBlock() {
    return StatBlock;
  },
});
export type Baseline = __Infer<typeof Baseline>;

export const BaselineComponent = __t.object("BaselineComponent", {
  entityId: __t.u64(),
  baselineId: __t.u32(),
});
export type BaselineComponent = __Infer<typeof BaselineComponent>;

export const BaselineComponentBlob = __t.object("BaselineComponentBlob", {
  baselineId: __t.u32(),
});
export type BaselineComponentBlob = __Infer<typeof BaselineComponentBlob>;

// The tagged union or sum type for the algebraic type `Buff`.
export const Buff = __t.enum("Buff", {
  Guard: __t.i32(),
});
export type Buff = __Infer<typeof Buff>;

export const Encounter = __t.object("Encounter", {
  id: __t.u32(),
  categoricBlobId: __t.u32(),
  blobIds: __t.array(__t.u32()),
});
export type Encounter = __Infer<typeof Encounter>;

export const EncounterBlob = __t.object("EncounterBlob", {
  id: __t.u32(),
  get blob() {
    return EntityBlob;
  },
});
export type EncounterBlob = __Infer<typeof EncounterBlob>;

export const EncounterIdSample = __t.object("EncounterIdSample", {
  weight: __t.u8(),
  id: __t.u32(),
});
export type EncounterIdSample = __Infer<typeof EncounterIdSample>;

export const EncounterIdsSampler = __t.object("EncounterIdsSampler", {
  get selections() {
    return __t.array(EncounterIdSample);
  },
});
export type EncounterIdsSampler = __Infer<typeof EncounterIdsSampler>;

export const EnemyControllerComponent = __t.object("EnemyControllerComponent", {
  entityId: __t.u64(),
});
export type EnemyControllerComponent = __Infer<typeof EnemyControllerComponent>;

export const EnemyControllerComponentBlob = __t.object("EnemyControllerComponentBlob", {});
export type EnemyControllerComponentBlob = __Infer<typeof EnemyControllerComponentBlob>;

export const Entity = __t.object("Entity", {
  id: __t.u64(),
});
export type Entity = __Infer<typeof Entity>;

export const EntityBlob = __t.object("EntityBlob", {
  get name() {
    return __t.option(NameComponentBlob);
  },
  get location() {
    return __t.option(LocationComponentBlob);
  },
  get path() {
    return __t.option(PathComponentBlob);
  },
  get allegiance() {
    return __t.option(AllegianceComponentBlob);
  },
  get baseline() {
    return __t.option(BaselineComponentBlob);
  },
  get traits() {
    return __t.option(TraitsComponentBlob);
  },
  get equipmentStatBlockCache() {
    return __t.option(StatBlockCacheComponentBlob);
  },
  get statusStatBlockCache() {
    return __t.option(StatBlockCacheComponentBlob);
  },
  get traitsStatBlockCache() {
    return __t.option(StatBlockCacheComponentBlob);
  },
  get traitsStatBlockDirtyFlag() {
    return __t.option(FlagComponentBlob);
  },
  get totalStatBlockDirtyFlag() {
    return __t.option(FlagComponentBlob);
  },
  get attack() {
    return __t.option(AttackComponentBlob);
  },
  get hp() {
    return __t.option(HpComponentBlob);
  },
  get ep() {
    return __t.option(EpComponentBlob);
  },
  get playerController() {
    return __t.option(PlayerControllerComponentBlob);
  },
  get enemyController() {
    return __t.option(EnemyControllerComponentBlob);
  },
  get actionState() {
    return __t.option(ActionStateComponentBlob);
  },
  get queuedActionState() {
    return __t.option(ActionStateComponentBlob);
  },
  get actions() {
    return __t.option(ActionsComponentBlob);
  },
  get actionHotkeys() {
    return __t.option(ActionHotkeysComponentBlob);
  },
  get entityProminence() {
    return __t.option(EntityProminenceComponentBlob);
  },
  get entityDeletionTimer() {
    return __t.option(TimerComponentBlob);
  },
  get playerDeactivationTimer() {
    return __t.option(TimerComponentBlob);
  },
  get locationMap() {
    return __t.option(LocationMapComponentBlob);
  },
  get appearanceFeatures() {
    return __t.option(AppearanceFeaturesComponentBlob);
  },
});
export type EntityBlob = __Infer<typeof EntityBlob>;

export const EntityBlobSample = __t.object("EntityBlobSample", {
  weight: __t.u8(),
  get blob() {
    return EntityBlob;
  },
});
export type EntityBlobSample = __Infer<typeof EntityBlobSample>;

export const EntityBlobsSampler = __t.object("EntityBlobsSampler", {
  get selections() {
    return __t.array(EntityBlobSample);
  },
});
export type EntityBlobsSampler = __Infer<typeof EntityBlobsSampler>;

export const EntityEvent = __t.object("EntityEvent", {
  id: __t.u64(),
  time: __t.timestamp(),
  ownerEntityId: __t.u64(),
  get eventType() {
    return EventType;
  },
  targetEntityId: __t.u64(),
});
export type EntityEvent = __Infer<typeof EntityEvent>;

// The tagged union or sum type for the algebraic type `EntityIdSelector`.
export const EntityIdSelector = __t.enum("EntityIdSelector", {
  Literal: __t.u64(),
  Local: __t.u32(),
  Named: __t.string(),
});
export type EntityIdSelector = __Infer<typeof EntityIdSelector>;

export const EntityProminenceComponent = __t.object("EntityProminenceComponent", {
  entityId: __t.u64(),
  prominence: __t.i32(),
});
export type EntityProminenceComponent = __Infer<typeof EntityProminenceComponent>;

export const EntityProminenceComponentBlob = __t.object("EntityProminenceComponentBlob", {
  prominence: __t.i32(),
});
export type EntityProminenceComponentBlob = __Infer<typeof EntityProminenceComponentBlob>;

export const EpComponent = __t.object("EpComponent", {
  entityId: __t.u64(),
  ep: __t.i32(),
  mep: __t.i32(),
});
export type EpComponent = __Infer<typeof EpComponent>;

export const EpComponentBlob = __t.object("EpComponentBlob", {
  ep: __t.i32(),
  mep: __t.i32(),
});
export type EpComponentBlob = __Infer<typeof EpComponentBlob>;

// The tagged union or sum type for the algebraic type `EventType`.
export const EventType = __t.enum("EventType", {
  StartAction: __t.u32(),
  get ActionEffect() {
    return ActionEffect;
  },
});
export type EventType = __Infer<typeof EventType>;

export const FlagComponent = __t.object("FlagComponent", {
  entityId: __t.u64(),
});
export type FlagComponent = __Infer<typeof FlagComponent>;

export const FlagComponentBlob = __t.object("FlagComponentBlob", {});
export type FlagComponentBlob = __Infer<typeof FlagComponentBlob>;

export const HpComponent = __t.object("HpComponent", {
  entityId: __t.u64(),
  hp: __t.i32(),
  mhp: __t.i32(),
  defense: __t.i32(),
  accumulatedDamage: __t.i32(),
  accumulatedHealing: __t.i32(),
});
export type HpComponent = __Infer<typeof HpComponent>;

export const HpComponentBlob = __t.object("HpComponentBlob", {
  hp: __t.i32(),
  mhp: __t.i32(),
  defense: __t.i32(),
  accumulatedDamage: __t.i32(),
  accumulatedHealing: __t.i32(),
});
export type HpComponentBlob = __Infer<typeof HpComponentBlob>;

// The tagged union or sum type for the algebraic type `Layout`.
export const Layout = __t.enum("Layout", {
  Path: __t.unit(),
  Hub: __t.unit(),
});
export type Layout = __Infer<typeof Layout>;

export const LocationComponent = __t.object("LocationComponent", {
  entityId: __t.u64(),
  locationEntityId: __t.u64(),
});
export type LocationComponent = __Infer<typeof LocationComponent>;

export const LocationComponentBlob = __t.object("LocationComponentBlob", {
  get locationEntityId() {
    return EntityIdSelector;
  },
});
export type LocationComponentBlob = __Infer<typeof LocationComponentBlob>;

export const LocationMap = __t.object("LocationMap", {
  id: __t.u32(),
  name: __t.string(),
  themeId: __t.u32(),
  get layout() {
    return Layout;
  },
  rngSeed: __t.option(__t.u64()),
  extraRoomCount: __t.u8(),
  mainRoomCount: __t.u8(),
  loopCount: __t.u8(),
  get encounterIdsSampler() {
    return EncounterIdsSampler;
  },
  minEncounterCount: __t.u8(),
  maxEncounterCount: __t.u8(),
});
export type LocationMap = __Infer<typeof LocationMap>;

export const LocationMapComponent = __t.object("LocationMapComponent", {
  entityId: __t.u64(),
  locationMapEntityId: __t.u64(),
});
export type LocationMapComponent = __Infer<typeof LocationMapComponent>;

export const LocationMapComponentBlob = __t.object("LocationMapComponentBlob", {
  get locationMapEntityId() {
    return EntityIdSelector;
  },
});
export type LocationMapComponentBlob = __Infer<typeof LocationMapComponentBlob>;

export const LocationMapConnection = __t.object("LocationMapConnection", {
  id: __t.u32(),
  exitLocationMapId: __t.u32(),
  destinationLocationMapId: __t.u32(),
});
export type LocationMapConnection = __Infer<typeof LocationMapConnection>;

export const LocationMapTheme = __t.object("LocationMapTheme", {
  id: __t.u32(),
  get decorationsSelector() {
    return EntityBlobsSampler;
  },
  minDecorationCount: __t.u8(),
  maxDecorationCount: __t.u8(),
  get pathsSelector() {
    return EntityBlobsSampler;
  },
  get roomsSelector() {
    return EntityBlobsSampler;
  },
});
export type LocationMapTheme = __Infer<typeof LocationMapTheme>;

export const NameComponent = __t.object("NameComponent", {
  entityId: __t.u64(),
  name: __t.string(),
});
export type NameComponent = __Infer<typeof NameComponent>;

export const NameComponentBlob = __t.object("NameComponentBlob", {
  name: __t.string(),
});
export type NameComponentBlob = __Infer<typeof NameComponentBlob>;

export const NamedEntity = __t.object("NamedEntity", {
  name: __t.string(),
  entityId: __t.u64(),
});
export type NamedEntity = __Infer<typeof NamedEntity>;

export const NamedEntityBlob = __t.object("NamedEntityBlob", {
  name: __t.string(),
  get blob() {
    return EntityBlob;
  },
});
export type NamedEntityBlob = __Infer<typeof NamedEntityBlob>;

export const PathComponent = __t.object("PathComponent", {
  entityId: __t.u64(),
  destinationEntityId: __t.u64(),
});
export type PathComponent = __Infer<typeof PathComponent>;

export const PathComponentBlob = __t.object("PathComponentBlob", {
  get destinationEntityId() {
    return EntityIdSelector;
  },
});
export type PathComponentBlob = __Infer<typeof PathComponentBlob>;

export const PlayerControllerComponent = __t.object("PlayerControllerComponent", {
  entityId: __t.u64(),
  identity: __t.identity(),
});
export type PlayerControllerComponent = __Infer<typeof PlayerControllerComponent>;

export const PlayerControllerComponentBlob = __t.object("PlayerControllerComponentBlob", {
  identity: __t.identity(),
});
export type PlayerControllerComponentBlob = __Infer<typeof PlayerControllerComponentBlob>;

export const SpecialEntityBlob = __t.object("SpecialEntityBlob", {
  get key() {
    return SpecialEntityBlobKey;
  },
  get blob() {
    return EntityBlob;
  },
});
export type SpecialEntityBlob = __Infer<typeof SpecialEntityBlob>;

// The tagged union or sum type for the algebraic type `SpecialEntityBlobKey`.
export const SpecialEntityBlobKey = __t.enum("SpecialEntityBlobKey", {
  NewPlayer: __t.unit(),
});
export type SpecialEntityBlobKey = __Infer<typeof SpecialEntityBlobKey>;

export const StatBlock = __t.object("StatBlock", {
  attack: __t.i32(),
  mhp: __t.i32(),
  defense: __t.i32(),
  mep: __t.i32(),
  actionIds: __t.array(__t.u32()),
  appearanceFeatureIds: __t.array(__t.u32()),
});
export type StatBlock = __Infer<typeof StatBlock>;

export const StatBlockCacheComponent = __t.object("StatBlockCacheComponent", {
  entityId: __t.u64(),
  get statBlock() {
    return StatBlock;
  },
});
export type StatBlockCacheComponent = __Infer<typeof StatBlockCacheComponent>;

export const StatBlockCacheComponentBlob = __t.object("StatBlockCacheComponentBlob", {
  get statBlock() {
    return StatBlock;
  },
});
export type StatBlockCacheComponentBlob = __Infer<typeof StatBlockCacheComponentBlob>;

export const SystemTimer = __t.object("SystemTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type SystemTimer = __Infer<typeof SystemTimer>;

export const TimerComponent = __t.object("TimerComponent", {
  entityId: __t.u64(),
  timestamp: __t.timestamp(),
});
export type TimerComponent = __Infer<typeof TimerComponent>;

export const TimerComponentBlob = __t.object("TimerComponentBlob", {
  timestamp: __t.timestamp(),
});
export type TimerComponentBlob = __Infer<typeof TimerComponentBlob>;

export const Trait = __t.object("Trait", {
  id: __t.u32(),
  name: __t.string(),
  get statBlock() {
    return StatBlock;
  },
});
export type Trait = __Infer<typeof Trait>;

export const TraitsComponent = __t.object("TraitsComponent", {
  entityId: __t.u64(),
  traitIds: __t.array(__t.u32()),
});
export type TraitsComponent = __Infer<typeof TraitsComponent>;

export const TraitsComponentBlob = __t.object("TraitsComponentBlob", {
  traitIds: __t.array(__t.u32()),
});
export type TraitsComponentBlob = __Infer<typeof TraitsComponentBlob>;

