// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ActReducer from "../act_reducer";
import PushAssetsReducer from "../push_assets_reducer";

export type ActParams = __Infer<typeof ActReducer>;
export type PushAssetsParams = __Infer<typeof PushAssetsReducer>;

